### ISSUE TITLE
Publish crate

### ISSUE THREAD

**Issue by alichtman** [Rigellute/spotify-tui#1]
Would be great if you could ` $ cargo install spotify-tui`.

Looks like a sweet project.

**Comment by Rigellute** [comment]
Thank you. And I do intend to do this!

**Comment by Rigellute** [comment]
Have now published to `cargo`!

```bash
cargo install spotify-tui
```

In addition, you can also install a prebuilt binary using `brew`
```bash
brew install Rigellute/tap/spotify-tui
```
