### ISSUE TITLE
scroll not in view

### ISSUE THREAD

**Issue by estysdesu** [Rigellute/spotify-tui#10]
When moving cursor up and down, it doesn't show selected/highlighted choice when terminal window is resized. I use tmux, and the pane resizes great to fit the proper space, but it doesn't update the scroll buffer of what is visible to select. 
I am selecting songs below the visible song list, because they are still selectable in the current scroll buffer from the tmux resize.

![Scroll not in view](https://user-images.githubusercontent.com/37026871/66340711-c927f400-e913-11e9-8171-b1ba3ed11a75.gif)

**Comment by Rigellute** [comment]
Ah good point, this needs to be fixed.

**Comment by sputnick1124** [comment]
I can take this if no one else is working on it!

**Comment by Rigellute** [comment]
Please do @sputnick1124 
I think the fix would entail figuring out how many rows would fit in the current window and also using that number as the spotify limit for results.

**Comment by Rigellute** [comment]
Fixed by @sputnick1124
