### ISSUE TITLE
Volume controll does not seem to work (correctly)

### ISSUE THREAD

**Issue by johandegn** [Rigellute/spotify-tui#101]
_Using version 0.7.0 and playing from spotify app on android._
Pressing '+' has no effect and '-' opens the error screen.
(Pressing '-' multiple times stacks error screens so you need to press Esc multiple times to exit.)

**Comment by johandegn** [comment]
While it works then streaming from the desktop application on a windows 10 pc, the volume acts weird.
Switching between + and - makes it jump to a, seemingly, random percentage.
It also seems that the volume first changes to the shown after the next change. 
For example, say the volume is 65%. Pressing either + or - might make it jump to 37% but actually changing the volume to the 65%. Next change would make it jump to another number, but setting the volume to the 37%.

**Comment by Rigellute** [comment]
The volume controls are quite janky. Will investigate.

**Comment by Rigellute** [comment]
Fixed in https://github.com/Rigellute/spotify-tui/pull/166
