### ISSUE TITLE
AUR build error

### ISSUE THREAD

**Issue by TH3-S4LM0N** [Rigellute/spotify-tui#1027]
I installed `spotify-tui` from the aur with `yay`. During the compile, this error occured:
```
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
   --> /home/salmon/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.12/src/sockaddr.rs:176:9
    |
176 |         mem::transmute::<SocketAddrV4, sockaddr_in>(v4);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: source type: `SocketAddrV4` (48 bits)
    = note: target type: `sockaddr_in` (128 bits)

For more information about this error, try `rustc --explain E0512`.
error: could not compile `socket2` due to previous error
```
Searched for "transmutate" type keywords, didn't see any issues, my bad if this is a dupe.

Edit: 3 months later I realized I put `sporify-tui`

**Comment by loremol** [comment]
This happens also to me.

**Comment by w1sq** [comment]
I also got this issue

**Comment by lalovzg** [comment]
Just wanted to add into this issue:

Rust in its version 1.64.0 made changes to Ipv4Addr, Ipv6Addr, SocketAddrV4 and SocketAddrV6. Also, when using `std::mem::transmute` it results in invalid memory accesses.
[Rust 1.64.0 Compatibility Notes](https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#compatibility-notes)

With all of these, the newest version of Rust broke some *crates*, and now spotify-tui has problems with memory and different bit sizes and stuff.
So they recommend doing `cargo update` to mitigate for now, and it works as a workaround (adding the cargo update somewhere before it reads the *Cargo.lock* and *Cargo.toml* files and *.patches*.

I had to manually do the editing, building and compiling from ["source"](https://aur.archlinux.org/packages/spotify-tui) (AUR in Arch Linux).

Also, after running `makepkg si` with the cargo update command already in place, it updates the files but after that it is required to download updated versions of some of the dependencies/creates and 1 or 2 required http and also, obviously for all the update, network connection is required so the `--frozen` option had to be temporary removed.

For me, it built succesfully after that even using this PKGBUILD.

**Comment by nurhaziq97** [comment]
https://github.com/Rigellute/spotify-tui/issues/1027#issuecomment-1259853785 suggested workaround work for me. Thank you

**Comment by K-wachira** [comment]
> I had to manually do the editing, building, and compiling

Hi, I have little to no knowledge when it comes to rust, 
What files are you editing or updating before doing the build? I am stuck there. 

I tried doing the `cargo update`, but I do not have `Cargo.toml ` on spotify-tui root folder. 
I extracted the ` rspotify-0.10.0` and ran `cargo update`  in that directory but still got the error when building.

**Comment by nurhaziq97** [comment]
For me, I just clone the [AUR}(https://aur.archlinux.org/packages/spotify-tui) git. Then, I edit the PKGBUILD file on line 38-46 into this.
```
build() {
  cd "$pkgname-$pkgver"
  export RUSTUP_TOOLCHAIN=stable
  export CARGO_TARGET_DIR=target
  cargo update
  cargo build  --release
  ./target/release/spt --completions bash > target/release/spt-completion.bash
  ./target/release/spt --completions zsh > target/release/spt-completion.zsh
  ./target/release/spt --completions fish > target/release/spt-completion.fish
}
```
I don't know if this is the correct approach.

**Comment by K-wachira** [comment]
Thanks, this worked for me too. :)

**Comment by Gianfra1002** [comment]
> For me, I just clone the [AUR}(https://aur.archlinux.org/packages/spotify-tui) git. Then, I edit the PKGBUILD file on line 38-46 into this.
> 
> ```
> build() {
>   cd "$pkgname-$pkgver"
>   export RUSTUP_TOOLCHAIN=stable
>   export CARGO_TARGET_DIR=target
>   cargo update
>   cargo build  --release
>   ./target/release/spt --completions bash > target/release/spt-completion.bash
>   ./target/release/spt --completions zsh > target/release/spt-completion.zsh
>   ./target/release/spt --completions fish > target/release/spt-completion.fish
> }
> ```
> 
> I don't know if this is the correct approach.

That worked, thank you so much!

**Comment by 0xFAC0** [comment]
> For me, I just clone the [AUR}(https://aur.archlinux.org/packages/spotify-tui) git. Then, I edit the PKGBUILD file on line 38-46 into this.
> 
> ```
> build() {
>   cd "$pkgname-$pkgver"
>   export RUSTUP_TOOLCHAIN=stable
>   export CARGO_TARGET_DIR=target
>   cargo update
>   cargo build  --release
>   ./target/release/spt --completions bash > target/release/spt-completion.bash
>   ./target/release/spt --completions zsh > target/release/spt-completion.zsh
>   ./target/release/spt --completions fish > target/release/spt-completion.fish
> }
> ```
> 
> I don't know if this is the correct approach.

Also fixed the issue on a nearly fresh arch install.

**Comment by TH3-S4LM0N** [comment]
Came back and it is building now so no reason for this to stay open.
