### ISSUE TITLE
Is there a way to change fonts? 

### ISSUE THREAD

**Issue by moosyu** [Rigellute/spotify-tui#1034]
I'm on windows and a lot of the emojis break with the default font. I have installed a nerdfont like recommended but I'm unsure on how to set the font on spotify-tui.

**Comment by nopeless** [comment]
If you are talking about spt developers having to create multiple emoji configurations for this terminal app, I don't think its going to happen.

You can always configure your terminal, and if you don't like the monospace from nerdfont, you can merge your font with nerdfont and use that combined fontfile for terminal

**Comment by moosyu** [comment]
I did find out you could customize fonts with [Windows Terminal](https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701?hl=en-nz&gl=nz) but I just snapped and switched to linux 😅
