### ISSUE TITLE
Failed to find OpenSSL development headers.

### ISSUE THREAD

**Issue by kerbless** [Rigellute/spotify-tui#1042]
I'm trying to build from AUR, but `makepkg` runs into:
```
--- stderr
  thread 'main' panicked at '
  Header expansion error:
  Error { kind: ToolExecError, message: "Command \"cc\" \"-O3\" \"-ffunction-sections\" \"-fdata-sections\" \"-fPIC\" \"-m64\" \"-march=x86-64\" \"-mtune=generic\" \"-O2\" \"-pipe\" \"-fno-plt\" \"-fexceptions\" \"-Wp,-D_FORTIFY_SOURCE=2\" \"-Wformat\" \"-Werror=format-security\" \"-fstack-clash-protection\" \"-fcf-protection\" \"-I\" \"/usr/include\" \"-E\" \"build/expando.c\" with args \"cc\" did not execute successfully (status code exit status: 1)." }

  Failed to find OpenSSL development headers.
```
The arch wiki states: 

> On Arch Linux the OPENSSLDIR is /etc/ssl

But in my system I have:
```
/usr/bin/openssl
/usr/include/openssl
```

The [openssl documentation](https://docs.rs/openssl/latest/openssl/) states:

> OPENSSL_LIB_DIR and OPENSSL_INCLUDE_DIR - If specified, the directories containing the OpenSSL libraries and headers respectively. This can be used if the OpenSSL installation is split in a nonstandard directory layout.

But setting those two environment variables respectively to `/usr/bin/openssl` and `/usr/include/openssl` doesn't change anything.

If this is not a spotify-tui issue, sorry.

**Comment by lahwaacz** [comment]
Arch Linux has recently upgraded to OpenSSL 3.0, see https://lists.archlinux.org/archives/list/arch-dev-public@lists.archlinux.org/thread/IZT6ADWS5YUUNC7IFBUVYIB7O4QIJGZV/

**Comment by Quadrubo** [comment]
I also encounter this problem, what do I have to do to fix this

**Comment by maya-doshi** [comment]
you can install the `openssl-1.1` and `openssl-1.0` packages along with the new one.

**Comment by modMars** [comment]
How to fix this issue? 
I can't get the app to work :(.

**Comment by toh995** [comment]
Hi @kerbless I noticed you closed this issue. Would you be able to share with us what you did to make it work? :sweat_smile:

**Comment by kerbless** [comment]
Hi @toh995, I ended up installing the normal version of Spotify, I closed the issue because it's not an issue of spotify-tui but more about how you handle the openssl package.

> you can install the `openssl-1.1` and `openssl-1.0` packages along with the new one.

Have you tried this?

**Comment by toh995** [comment]
Thanks for the response @kerbless!

Yes, I tried it, no luck. Also doing `yay -S spotify` doesn't work for me either - seems like the AUR package needs to be updated.

I guess I'll stick with the web client for now haha

**Comment by mrtztg** [comment]
I have the same problem. I installed `openssl-1.1` and `openssl-1.0`. But still not success.
