### ISSUE TITLE
App crashes when pressing 'down' after removing focus 

### ISSUE THREAD

**Issue by jfaltis** [Rigellute/spotify-tui#105]
Steps to reproduce:
- launch `spotify-tui`
- press `enter` -> `q` -> `j`

Things I noticed:
- It does not happen when pressing `escape` instead of `q`
- It also does not happen when pressing `k` instead of `j`

**Comment by Rigellute** [comment]
Ah I know a fix for this. 

My intention is that `q` should quit the app when you're at the bottom of the navigation stack.

Will PR a fix
