### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by Autobeing** [Rigellute/spotify-tui#1053]
I reinstalled Spotify-TUI and now when trying to start spt after correctly inserting Spotify creds and setting up redirect URI, I get this error every time from the link that opens in the browser and can't give permission to access the extension.

I have tried different ports, recreating the extension and tried connecting on three different computers. In the client.yml file the device_id is not filled in, I have never needed to set that up manually before and don't know what should be there, is there something I'm missing?

**Comment by cyberfeign** [comment]
I have the same issue! Did something change with how authentication works?

**Comment by mcopik** [comment]
Same issue here - fresh install of spt, I followed default configuration steps, and I ended up with this error.

**Comment by mcopik** [comment]
@cyberfeign @Autobeing I resolved my issue - it seems that the callback URI was not added correctly in my Spotify settings. You must click both 'Add' and 'Save' in the settings window.

**Comment by Autobeing** [comment]
I have verified the callback URI multiple times, and have tried with different ports. So it is not the same fix in my case, unfortunately.

**Comment by cyberfeign** [comment]
I checked my URI and it seems to be correctly set up as well. I haven't been able to use spt at all for a month or so, really miss it.

**Comment by lindblandro** [comment]
Followed the instructions for a fresh install and encountered this. Adding `http://localhost:8888/callback` to redirect uri allowlist in the newly created spotify-tui application settings in spotify dashboard solved the "Invalid redirect URI" issue for me. Don't know if Spotify has changed this part of their authorization flow recently, but the installation instructions must be updated.

**Comment by Autobeing** [comment]
My URI has always been `http://localhost:8888/callback`, or with a different port, which I then of course changed in the spt config as well. Still does not work for me and I get the error regardless.

**Comment by Autobeing** [comment]
I think there was something wrong with my Spotify account. I made a new one to get way from Facebook, and when I tried doing it exactly the same way with the new one, it worked. I am certain I set everything up correctly every time. No idea what could have been the issue with the account.
