### ISSUE TITLE
Exceeded API request limit #779

### ISSUE THREAD

**Issue by aleksejkrueger** [Rigellute/spotify-tui#1065]
Reopen of #779 

The problem still persist for me.

      System Version: macOS 12.6.2 (21G320)
      Kernel Version: Darwin 21.6.0
      spotify-tui 0.25.0

**Comment by sewnie** [comment]
can't reproduce

**Comment by aleksejkrueger** [comment]
This userscript [get_actual_song.sh](https://github.com/alexchaichan/tmux-spotify-tui/blob/main/scripts/get_actual_song.sh) is requesting permanently if a song is playing to output it in the tmux status.

I think that this overextending the app?

**Comment by sewnie** [comment]
By using spt to get the playback, I assume spt constantly sends requests with the Spotify API. I suggest you get the playback and name with `playerctl` via MPRIS.

**Comment by aleksejkrueger** [comment]
This would be a solution for Linux only

**Comment by sewnie** [comment]
then wait for https://github.com/aome510/spotify-player/pull/159
