### ISSUE TITLE
Help does not display the action

### ISSUE THREAD

**Issue by Valansch** [Rigellute/spotify-tui#108]
I think this is supposed to display what the keys actually do. I compiled the latest 

![image](https://user-images.githubusercontent.com/10226478/67530951-17cde000-f6c1-11e9-9a1a-19bca594fea3.png)

<pre>
spotify-tui 0.7.5

██████████████████  ████████   user@host 
██████████████████  ████████   ---------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Host: MS-7970 1.0 
████████            ████████   Kernel: 5.3.7-2-MANJARO 
████████  ████████  ████████   Uptime: 3 hours, 42 mins 
████████  ████████  ████████   Packages: 1506 (pacman) 
████████  ████████  ████████   Shell: zsh 5.7.1 
████████  ████████  ████████   Resolution: 1440x900, 3840x2160, 3840x2160, 1920x1080 
████████  ████████  ████████   WM: i3 
████████  ████████  ████████   Theme: Breath [GTK3] 
████████  ████████  ████████   Icons: maia [GTK3] 
████████  ████████  ████████   Terminal: konsole 19.08.2
████████  ████████  ████████   Terminal Font: Noto Mono 10 
                               CPU: Intel i7-6700 (8) @ 4.000GHz 
                               GPU: NVIDIA GeForce GTX 970 
                               Memory: 1702MiB / 15973MiB 
</pre>

**Comment by Rigellute** [comment]
Ah looks like this is a scrolling issue (the screen is not large enough to contain all the rows).

Needs to be fixed 👍

**Comment by Valansch** [comment]
Actually its the same on my 4k monitors. No matter the scrolling in konsole. Also tried xterm and terminator. Same issue. Please tell me how i can assist you figure this out.

**Comment by Rigellute** [comment]
When I say scrolling I mean from within `spotiify-tui`, not the terminal emulator. If you increase the height of your terminal window, you should see the rest of the list.

The fix is for `spotify-tui` to handle scrolling within table views (like the help menu).

**Comment by Valansch** [comment]
You are right it appears when i zoom. Also appears on my 4k monitors with bigger terminal, what i said before about it not appearing on 4k is false.
Keep up the good work :+1:

**Comment by AlexanderDavid** [comment]
@Rigellute is this being worked on?

**Comment by Rigellute** [comment]
@AlexanderDavid ah yes it looks like this was fixed here https://github.com/Rigellute/spotify-tui/pull/302

Thanks for looking for this though
