### ISSUE TITLE
`like` macro functionality redundant

### ISSUE THREAD

**Issue by H4ppy-04** [Rigellute/spotify-tui#1085]
The `w` key to follow doesn't like the song. When `ctrl+?` is pressed, `w` is bound to both:
 - save album to library
 - follow artist

**Comment by sewnie** [comment]
spotify-tui's librespot is outdated, please consider using [spotify-player](https://github.com/aome510/spotify-player)

**Comment by H4ppy-04** [comment]
> spotify-tui's librespot is outdated, please consider using [spotify-player](https://github.com/aome510/spotify-player)

Issue closed. Thank you for your response.
