### ISSUE TITLE
API Error when playing from liked songs playlist 

### ISSUE THREAD

**Issue by pxndey** [Rigellute/spotify-tui#1093]
This bug comes up when im playing a song from my liked songs playlist, but goes away when i play songs from a playlist and re-run spt
![image](https://github.com/Rigellute/spotify-tui/assets/98946689/ab6d507f-3b39-40fe-86de-ecf5e3b886c1)

**Comment by sewnie** [comment]
solution: https://github.com/aome510/spotify-player
