### ISSUE TITLE
line30: patch: command not found

### ISSUE THREAD

**Issue by Moa-Kikuchi** [Rigellute/spotify-tui#1094]
Installing spotify-tui manually using aur. Running the PKGBUILD results in the error 
"/home/USER/spotify-tui/PKGBUILD: line 30: patch: command not found
==> ERROR: A failure occurred in prepare().
    Aborting..."

**Comment by sewnie** [comment]
well a guy with a brain would `pacman -S patch`

and use
https://github.com/aome510/spotify-player

**Comment by Moa-Kikuchi** [comment]
> 

thanks bro. i dont have a brain.

**Comment by sewnie** [comment]
I MEANT IT AS AN INSULT IM SORRY

**Comment by sewnie** [comment]
# :sob:

**Comment by Moa-Kikuchi** [comment]
I'm newer to linux and overall just kinda dumb. I'm fine with admitting it. thanks for the help :)
