### ISSUE TITLE
(Arch Linux) Installing brings this warning, thought I could point it out and maybe understand?

### ISSUE THREAD

**Issue by XDuskAshes** [Rigellute/spotify-tui#1099]
![image](https://github.com/Rigellute/spotify-tui/assets/101196233/5b1f3c1f-13b6-4ddb-9d8c-83f41a0677ef)
When I install `spotify-tui` via `sudo pacman -S spotify-tui`, it comes up with this warning. What this means is unknown to me, as the most I've done in rust is "Hello World". Just thought I could point it out.

**Comment by sewnie** [comment]
spotify-tui is abandonware, which is why such an error appears, and why it uses completely out of date packages. please consider https://github.com/aome510/spotify-player
