### ISSUE TITLE
Unable to scroll past first page of songs in playlist

### ISSUE THREAD

**Issue by VerbTheNoun95** [Rigellute/spotify-tui#11]
After selecting a playlist, I can only view the first 30 or so songs and can't scroll beyond that. Scrolling using vim keys or arrow keys brings me back to the top of the list, and ctl+d/u doesn't do anything (although I'm not too sure ctl+d/u should do). Hopefully I'm not missing something easy in the help section.

**Comment by Rigellute** [comment]
You're right that `ctrl+d/u` should scroll through pages, but this has only been implemented in the "Liked Songs" view.

Will implement scrolling in other views!

**Comment by daphen** [comment]
Or maybe you should be able to just scroll further down the list like in the "playlists-view"? Instead of jumping up when you get to the bottom I mean?

**Comment by jessebett** [comment]
I agree with @daphen the behaviour inside the `Songs` view should be the same as the behaviour inside the `Playlists` view, not like the current `Liked Songs`. `Liked Songs` should also behave like this.

That is, once the `Songs` view has been selected,hitting `j` to the bottom should not cycle to the top, but should continue going down the view, like `Playlists`. 

`ctrl+d/u` will still be useful for scrolling up and down whole pages.

**Comment by nikolaevigor** [comment]
Hi, what if I have `ctrl-d` bound to i3wm dmenu, can i remap it somehow? If yes, what key should I use in `keybindings:` part of `client.yml`?

**Comment by Rigellute** [comment]
@nikolaevigor in the next release you'll be able to configure `ctrl-d/u` through the keybindings config https://github.com/Rigellute/spotify-tui/pull/566
