### ISSUE TITLE
Crashes and closes terminal when run in st

### ISSUE THREAD

**Issue by Valansch** [Rigellute/spotify-tui#110]
When running spt in [st](https://st.suckless.org/) i get the error:

<pre>
Error: Os { code: 25, kind: Other, message: "Inappropriate ioctl for device" }
</pre>

**1. What I expect to happen**
<pre>
spotify-tui to launch
</pre>

**2. What happends**
<pre>
Spt crashes
</pre>

**3. What i expect to happen in case of 2.**
<pre>
Print error to terminal, exit with status 1 and not kill terminal.
</pre>

**4. What whappends**
<pre>
Prints error to terminal, exit with status 1 and kill terminal.
</pre>

<pre>
spotify-tui 0.7.5

██████████████████  ████████   user@host
██████████████████  ████████   ----------
██████████████████  ████████   OS: Manjaro Linux x86_64
██████████████████  ████████   Host: MS-7970 1.0
████████            ████████   Kernel: 5.3.7-2-MANJARO
████████  ████████  ████████   Uptime: 19 mins
████████  ████████  ████████   Packages: 1510 (pacman)
████████  ████████  ████████   Shell: zsh 5.7.1
████████  ████████  ████████   Resolution: 1440x900, 3840x2160, 3840x2160, 1920x1080
████████  ████████  ████████   WM: i3
████████  ████████  ████████   Theme: Breath [GTK3]
████████  ████████  ████████   Icons: maia [GTK3]
████████  ████████  ████████   Terminal: st
████████  ████████  ████████   Terminal Font: xos4 Terminus
                               CPU: Intel i7-6700 (8) @ 4.000GHz
                               GPU: NVIDIA GeForce GTX 970
                               Memory: 1833MiB / 15973MiB

</pre>

I'm not sure if this is a spotify-tui issue or st issue.

**Comment by LU15W1R7H** [comment]
I've been experiencing the same problem. Turned out that the terminal crashed, because it couldn't display some emojis (which I had in some playlist names) or some other unicode symbol. I fixed it by installing the ttf-symbola font ([AUR](https://aur.archlinux.org/packages/ttf-symbola/) if you're using arch), as recommended by the ArchWiki. This fixed the issue for me.

**Comment by Valansch** [comment]
That's it. I have the emoji issue too. ttf-symbola fixed it.

**Comment by Rigellute** [comment]
Thanks for this @LU15W1R7H. Sounds like this isn't an issue with spotify-tui

**Comment by Rigellute** [comment]
Snap @Valansch closed the issue. Thanks all!

**Comment by 00ms** [comment]
How do i install ttf-symbola on gentoo ? cant seem to find any package
