### ISSUE TITLE
Disabled in `brew` because of deprecated `openssl@1.1`

### ISSUE THREAD

**Issue by Neved4** [Rigellute/spotify-tui#1102]
`Warning: spotify-tui has been deprecated because it uses deprecated 'openssl@1.1'!`

See: https://github.com/Homebrew/homebrew-core/commit/d09e2a433e9095074aac1eac217c4ea86bfa0785

**Comment by sewnie** [comment]
https://github.com/aome510/spotify-player

Spotify-tui is dead

**Comment by Neved4** [comment]
Have the maintainers considered turning it into an archive?

**Comment by sewnie** [comment]
There's only one maintainer and they said 'I'll get back to this' Without giving anyone else some form of control over the project while they don't do anything...
