### ISSUE TITLE
wezterm terminal issue

### ISSUE THREAD

**Issue by zvbt** [Rigellute/spotify-tui#1113]
Whenever I use Spotify-TUI in the Wezterm terminal, it freezes after a certain amount of time.

**Comment by sewnie** [comment]
This may be an issue related with your terminal and not spt. To verify, please try [spotify_player](https://github.com/aome510/spotify-player) and see if the issue happens there.

**Comment by zvbt** [comment]
I tried Spotify_player and it did the same thing, I later found out the problem was with my wezterm config.

**Comment by sewnie** [comment]
What was the exact issue?

**Comment by zvbt** [comment]
In my config, I was using the keybind "n" for a certain function. After I removed it, there were no more freezing issues.
