### ISSUE TITLE
Can't Access Artist Page

### ISSUE THREAD

**Issue by teowelton** [Rigellute/spotify-tui#1116]
Hello! Previously, (~a month or two ago) when I was using Spotify-TUI and I searched for an artist, I was able to select an artist from the "artists" panel of the search results page. 

When I did this, I was able to access a "artist page", where I could see top songs, albums, etc.

However, as of recently, I have not been able to access this page, and instead when I hit `enter` on the artist, it just displays a black page.

Does anyone have any fixes / or is this a bug?

Thanks! :D

**Comment by DavidHospital** [comment]
Seems to be caused by https://github.com/ramsayleung/rspotify/issues/452 from `rspotify`

**Comment by teowelton** [comment]
Yeah! Looking through that issue it seems that they have submitted it to Spotify, and they are resolving it. Closing issue now :D

**Comment by L3P3** [comment]
I just want to confirm it is that issue. When opening artists with few followers, it works.
