### ISSUE TITLE
Spotify TUI only works when a song is selected that I have never heard before.

### ISSUE THREAD

**Issue by Brazlucas** [Rigellute/spotify-tui#1117]
Spotify TUI only works when a song is selected that I have never heard before. If I open the provider with a song that I have already listened to, an error message is displayed. 

Sorry for my English, it's not my native language.

![Screenshot 2024-01-25 225935](https://github.com/Rigellute/spotify-tui/assets/107437261/ee79a40e-686b-4b12-875a-a8e58fc49c46)

**Comment by TornaxO7** [comment]
Hi! Maybe you can give [spotify-player](https://github.com/aome510/spotify-player) a try.

**Comment by Brazlucas** [comment]
@TornaxO7 thank u bro, I'll give it a chance
