### ISSUE TITLE
Unable to install in Mac 

### ISSUE THREAD

**Issue by adityjoshi** [Rigellute/spotify-tui#1129]
Hey guys I am trying to install Spotify-tui in Mac but it's not installing. I am getting this openssl error I have downgraded my version to but still it's not installing 
<img width="1440" alt="Screenshot 2024-05-04 at 10 18 07 AM" src="https://github.com/Rigellute/spotify-tui/assets/111140014/e96b4b2d-083c-4db9-9218-0db1e0e75368">

**Comment by sewnie** [comment]
https://github.com/aome510/spotify-player

**Comment by sewnie** [comment]
There is a reason why it was deprecated. Because it is abandoned.

**Comment by adityjoshi** [comment]
hey @apprehensions when I run Spotify_player it is asking for username. Can you tell me how to add username ?

**Comment by sewnie** [comment]
You login there just like how you login your Spotify. E-mail and password.

**Comment by adityjoshi** [comment]
Thank u for the help
