### ISSUE TITLE
Playlist window doesn't show all songs

### ISSUE THREAD

**Issue by GarthTheChicken** [Rigellute/spotify-tui#113]
The playlist window only shows about 40 songs no matter how resize the terminal and /or restart. I did have a problem when I first tried spotify-tui where is wouldn't show all my playlists but that resolved itself after a few restarts.

I don't know if the playlists get paged but Ctrl-u/d doesn't do anything. 

Tried in UXTerm, URXVT and ST with the same behaviour.

Making the terminal smaller actually shows less songs, by that i mean I scroll to the bottom of the playlist listing (showing 15 songs instead of 40) and it will jump back to the first song instead of still scrolling down. Making the terminal larger that the UI just shows the 40 ish songs with a gap at the bottom but still goes to the top once I scroll to the bottom song.

Spotify says there's 147 songs. It happens with all long playlists. Am i missing a command to show the next set of songs?

![2019-10-26-100110_3840x1200_scrot](https://user-images.githubusercontent.com/16607045/67617111-a896df80-f7d7-11e9-8455-23ca819d6dfc.png)

**Comment by Rigellute** [comment]
Yes sorry for confusion, I've not implemented paginated scrolling for the playlist view yet!

**Comment by GarthTheChicken** [comment]
Not to worry, I wasn't sure if I was doing anything wrong. Is paging your preferred method for long playlists or is it down to the API?

**Comment by Rigellute** [comment]
Pagination is indeed required by the API.

**Comment by LennyPenny** [comment]
Did https://github.com/Rigellute/spotify-tui/pull/150 and https://github.com/Rigellute/spotify-tui/pull/133 not try to address this?

**Comment by Rigellute** [comment]
You're right @LennyPenny! Thank you for pointing that out 👍

**Comment by LennyPenny** [comment]
Uh wait a second, while scrolling/pagination in the "Playlists" view works for me on the latest master build, scrolling in the "Songs" view does not when the playlist has more songs that fit on the screen. Which is what this issue is about

This might need to be reopened. Did anything break that feature or was it never implemented?

**Comment by Rigellute** [comment]
Pagination scrolling using `ctrl-d/u` seems to work for me when viewing the "songs" in a playlist?

**Comment by LennyPenny** [comment]
ooh I didn't know I had to press that combo for it to work. 
I think that seems pretty weird, as you can just use the arrow keys to scroll in the playlist view. 

Would you accept a feature that also implements pagination with the arrow keys similar to the paylist view?

**Comment by GarthTheChicken** [comment]
Sorry but I just can't seem to get ctrl-d/u to work for me. Maybe I'm doing it wrong. I pulled the latest version available from github and compiled as usual.

I use the arrow keys to select the playlist block, press enter. Scroll to select the playlist and press enter. The songs in the playlist are then viewable in the songs block. I've tried pressing ctrl-d (and u) from here, scrolling to the last viewable track and pressing ctrl-d/u but nothing happens. 

Playing the last viewable song and them hitting n for the next song will play the next song on the list gets me to the next song and I can keep going but they won't show up on the songs block, although the now playing block does get updated.

I've switched window managers and other terminals just in case it but still have the same problem.

**Comment by Rigellute** [comment]
@LennyPenny I would be open to going to the next page when selection is on last viewable item in the list. The reason this is not yet implemented is that it adds some complexity to state management, totally doable though.

The thinking behind `ctrl-d` (down) and `ctrl-u` (up) are that these are used when scrolling (large jumps) in vim/terminal in general. 

@GarthTheChicken hmm... strange. I've just double checked again and it's working for me. Only thing I can think of is that the playlist you're viewing doesn't have any more pages of tracks?

**Comment by GarthTheChicken** [comment]
Just to let you know 0.10.0 seems to have fixed this with ctrl-d/u now working. Thank you for your support
