### ISSUE TITLE
Bluetooth output devices not working playing spotify(d) sound

### ISSUE THREAD

**Issue by kataklasm** [Rigellute/spotify-tui#120]
spotify-tui is working great out of the box with spotifyd. One issue I have is that playback on bluetooth devices isn't working. I am on popOS 19.04 and tested spotify-tui with spotifyd with two devices: Bose SoundLink Mini and Apple AirPods Gen2, after successfully connecting either of the two they start outputting system sounds as intended, only spotify-tui/spotifyd sounds aren't being played. Something to note is that this issue only surfaces when using spotify-tui with spotifyd, normal Spotify client+spotify-tui is working just fine with both my Bluetooth devices. This isn't anything crucial or urgent for me, just logging this bug in an issue.
Thank you for this great CLI utility!

**Comment by AivreeG** [comment]
Are you sure it isn't something to do with your Spotifyd config? What backend are you running with it?

**Comment by cramermarius** [comment]
I'm honestly not sure. I'm running the pulseaudio backend, which according to spotifyd issue #277 (https://github.com/Spotifyd/spotifyd/issues/277) should be used. If you guys think this is a spotifyd issue feel free to close this and I'll make an issue over there.
