### ISSUE TITLE
Reccomended feature not implemented

### ISSUE THREAD

**Issue by ZigTag** [Rigellute/spotify-tui#129]
I am going to attempt to implement it

**Comment by Rigellute** [comment]
@ZigTag sounds good. Could you outline your ideas for what this might look like?

**Comment by ZigTag** [comment]
I'm going to work on this over the weekend, but I'm thinking of just having the 'r' key bounded to the recommended feature, and it will fetch whatever song is currently highlighted, possibly with playlists as well, could also maybe add a recommended playlist binding

**Comment by ZigTag** [comment]
I have lost interest in trying to implement it, if anyone else wants to try go right ahead

**Comment by Rigellute** [comment]
@neriglissar's work #200 closes this
