### ISSUE TITLE
tui not using space efficiently

### ISSUE THREAD

**Issue by iMarv** [Rigellute/spotify-tui#138]
The tui is not extending over the complete terminal window, leaving a lot of space empty.

![spotify_tui_screnshot](https://user-images.githubusercontent.com/2131339/68188503-95d79400-ffa9-11e9-954e-b2111d6fda05.png)

**Comment by Rigellute** [comment]
That space at the bottom is meant for the playbar. When nothing is playing, the playbar doesn't render. 
I keep meaning to address this.

**Comment by iMarv** [comment]
Even with the playbar there is a lot of unused space:

![spotify_tui_screnshot2](https://user-images.githubusercontent.com/2131339/68206664-997d1200-ffcd-11e9-8df1-ef1cfbe4b4b1.png)

**Comment by synth-ruiner** [comment]
I second this. I don't tend to have terminals any bigger than 1/4 of the screen (tiling window manager...) and spotify-tui doesn't make the most of the space available. I can only fit 11 tracks on screen that way. having 2 whole rows of padding at the top and bottom seems excessive!

**Comment by Rigellute** [comment]
As a quick fix, I could remove the margin entirely?

<img width="1017" alt="Screenshot 2019-11-06 at 09 30 24" src="https://user-images.githubusercontent.com/12150276/68285917-149b0280-0078-11ea-9183-1280c44c7829.png">

**Comment by synth-ruiner** [comment]
looks awesome to me! I can see how fullscreen you might want a small margin but that could be a job for later? :)
