### ISSUE TITLE
Wrong key binding reported in help for repeat

### ISSUE THREAD

**Issue by sputnick1124** [Rigellute/spotify-tui#140]
It appears that when user configurable key bindings was implemented, the binding for `repeat` was changed from `Ctrl('r')` to simply `Char('r')`. 
https://github.com/Rigellute/spotify-tui/commit/2c7884ec24e9ac9689ed916893e48bc6277a67d3#diff-895ee444320b8451df36e6c622e6a9a2L93
https://github.com/Rigellute/spotify-tui/commit/2c7884ec24e9ac9689ed916893e48bc6277a67d3#diff-ffb0462e0846bb6f9c2eb982ac760038R107

This change is a good one in my books, but ought to be documented correctly as the help menu still reports `Ctrl-R`
https://github.com/Rigellute/spotify-tui/blob/master/src/ui/help.rs#L16

As a stretch goal, ought we consider displaying the current bindings in the help menu? Or we could simply specify which values have defaults but are also configurable.

**Comment by Rigellute** [comment]
Oh good catch. That sounds like a mistake. I personally prefer `Ctrl-r`, (but now it's configurable anyway).

And yes, it would be nice if the help menu could read the config file to show the currently active user bindings (be they default or custom).

**Comment by Rigellute** [comment]
Have reverted it to `Ctrl-r` here 22dd33c4495ee53d2ee0f3758a2a637b8f529491
