### ISSUE TITLE
Complexity in selection indexes

### ISSUE THREAD

**Issue by GrudgeDuck** [Rigellute/spotify-tui#144]
Selection indexes is common feature in paging, playing tracks, and cursor motion. However, it is difficult to understand when or where an index will be changed. This difficulty cause some unexpected behaviors found in #133 and #137. In addition, i found following error . After i opened `AlbumList` block from `Artists` block, went back to `Library` and open `AlbumList` block from the `Library` and select an album, wrong album was selected.

One  solution for these problms is to reset states of indexes or pages when `pop_navigation_stack` is called but this seems to be a temporary one and better solution might exist.

**Comment by echoSayonara** [comment]
Sorry, the behavior i reported in the previous comment behavior seems to be fixed.

**Comment by sputnick1124** [comment]
Can this be closed, then?

**Comment by GrudgeDuck** [comment]
Sorry, i forgot to close this issue. I've closed this.
