### ISSUE TITLE
Feature request: add song to playlist

### ISSUE THREAD

**Issue by bevensteven** [Rigellute/spotify-tui#15]

**Comment by bevensteven** [comment]
Just noticed you have this on your road map already, retracting.

**Comment by lilgreggy** [comment]
I know this is still on the roadmap and seems near the top of priorities. Wondering if there is currently work being done on this? Open to tinkering with it myself, but would be a learning experience. Eager and motivated as this is one of my most-used features in the client.

**Comment by sewnie** [comment]
2 years.
