### ISSUE TITLE
Implement methods to control playback

### ISSUE THREAD

**Issue by Ciavarella** [Rigellute/spotify-tui#16]
Would be awsome if you could add next and previous track. 

I know that there is some issues with: 
"The auth token does not currently automatically refresh - when you leave spotify-tui running for a while, you won't be able to control playback. And you'll need to quit and restart to get it working again."

I had the same issue, i checked if the current token is valid. You could probably do this in a nicer way but when a user signs in the first time you get:
```
{
 "access_token" : "NgAagA...Um_SHo",
 "expires_in" : "3600",
 "refresh_token" : "NgCXRK...MzYjw"
}
```
The expires_in tells you when the access_token expires. You can use it to decide when to get a new access_token. Then use the refresh_token to get a new access_token.

You can renew the access_token by using a refresh_token. This token is provided to you when you first make the request to authenticate the user. You should save that refresh_token if you don't already do so. The refresh_token is valid forever but you can't control playback with the refresh_token.

To get a new access_token with the refresh_token: (JavaScript)
```
    const res = await fetch(
      `${this.baseUrl}/auth/refresh_token?refresh_token=${refreshKey}`,
      {
        method: 'GET'
      }
    );
```

You will then get a new access_token that you can use to control playback.

Documentation from Spotify on how to use the refresh_token to access a new access_token.

https://developer.spotify.com/documentation/ios/guides/token-swap-and-refresh/

btw, love what you have made! Great work!

**Comment by jq-rs** [comment]
Yes, next and previous song keyboard shortcuts would be awesome!

**Comment by Rigellute** [comment]
I absolutely need to implement this. 

In keeping with vim style key bindings, which do you think would work best?

1. `;` for next and `,` for previous
1. `n` for next and `N` for previous

If you have any preferences, let me know!

**Comment by Rigellute** [comment]
And regarding implementing auto refresh of tokens, I have a plan for it.

**Comment by tommilligan** [comment]
Would like to help with this, I can either dive in or you can let me know when you have specific tasks that need doing.

My vote would be for `n` and `N` for playback bindings

**Comment by Ciavarella** [comment]
> I absolutely need to implement this.
> 
> In keeping with vim style key bindings, which do you think would work best?
> 
> 1. `;` for next and `,` for previous
> 2. `n` for next and `N` for previous
> 
> If you have any preferences, let me know!

I would go with 2. `n` for next and `N` for previous.
Or why not `n` for next and `p` for previous? Im not really a fan of uppercase commands.

**Comment by gallagth** [comment]
Following this, another vote for `n` and `p`!

**Comment by jq-rs** [comment]
Another vote for `n` and `p`.

These are the Github peer review shortcuts too, so many of us know them by heart. As @Ciavarella  already mentions.

**Comment by OscarVianValles** [comment]
I vote for 'n' and 'N' in keeping with vim style bindings.

**Comment by Rigellute** [comment]
Token refresh has now been implemented! https://github.com/Rigellute/spotify-tui/commit/df34c321439bfb82af093c5010b7ec94e255f3c7

Huge thanks to @fangyi-zhou

**Comment by jq-rs** [comment]
I am now missing also volume controls..

Token refresh and repeat works great!

**Comment by Rigellute** [comment]
Playback controls update:

- @samcal has implemented skipping tracks https://github.com/Rigellute/spotify-tui/pull/51
- PR here implementing seek functionality https://github.com/Rigellute/spotify-tui/pull/56

I'm going to close this issue and reopen one for controlling volume.
