### ISSUE TITLE
Starting song / artist / album radio

### ISSUE THREAD

**Issue by Bios-Marcel** [Rigellute/spotify-tui#171]
Hey,

it'd be pretty cool to start the radio (automatic music suggestion / playback) for a certain song, album or artist. Might be available for playlists too, not sure. Maybe there should be a global shortcut that simply uses the selection in the currently focus container.

**Comment by Rigellute** [comment]
Yes this would be cool. Spotify offer is a "recommendation" API which takes a "seed" - https://developer.spotify.com/documentation/web-api/reference/browse/get-recommendations/

This should be a straight forward one to implement. 

Perhaps we could use the keypress `r`?

**Comment by Bios-Marcel** [comment]
Cool, nice to hear.

So, I was actually thinking about something else considering the keystrokes. Maybe keystrokes should exclusively be non-character keyinputs. So `Ctrl+?` and `Ctrl+Shift+?` instead of `R, `S`, `?` and so on` .I'd prefer this because navigation within lists somewhat annoys me right now. I know there's already certain shortcuts that would be different to this. What do you think about this in general? I can make a new issue for this if you will.

I have written a terminal client for discord and in order to easily navigate the server / channel tree you can just start typing the first characters of the name and it will jump to the corresponding node in the tree. I'd really like something like this for spotify-tui. Anyway, I have found that to be very useful and it allows me to navigate the data without even looking at it.

**Comment by Rigellute** [comment]
Searching within a list would be a great feature - something I find myself wanting.

This wouldn't require us redefining existing bindings to be exclusively non-character keys - we could implement a keypress that puts you into search/filter mode.

Feel free to raise this as an additional issue.

**Comment by Rigellute** [comment]
@neriglissar's work #200 closes this

**Comment by Joelius300** [comment]
Is it correct that this doesn't work for playlists? In the official app there's a radio for those too (not for albums though) but pressing r on a playlist doesn't seem to play the radio in spt.

Also is there a way to go to the radio without immediately starting playback?
