### ISSUE TITLE
Typing 'q' to exit focuses search bar

### ISSUE THREAD

**Issue by stevensonmt** [Rigellute/spotify-tui#174]
After playing some tracks, typing q to get back to the main screen and then q to quit the application puts the cursor in the search bar. Hitting 'esc' and then 'q' typically then exits the application.

**Comment by Rigellute** [comment]
Hi @stevensonmt, you are right. I had originally intended this to be that way, however I myself don't like it.

If anyone want to have a crack at fixing, we could possibly do this: when we are `pop`ing the navigation stack via `q` we can check if the `pop`ed route is `Search` and then immediately `pop` again - essentially bypassing the search route.

**Comment by stevensonmt** [comment]
I can have a go at that this evening. Seems pretty straightforward to match on the pop result of Some(Search) and pop again.

**Comment by samcal** [comment]
@Rigellute I think this issue can be closed as fixed.

**Comment by Rigellute** [comment]
Thanks @samcal 👍
