### ISSUE TITLE
after upgrade cursor in search bar not aligned vertically correctly

### ISSUE THREAD

**Issue by stevensonmt** [Rigellute/spotify-tui#175]
Updated to latest release with cargo. After update the cursor in the search box is vertically centered on the bottom of the search box border while text appears centered vertically in the search box. See screenshot:
![image](https://user-images.githubusercontent.com/8891908/69906347-fffc1280-1376-11ea-93cc-b0a3962ade16.png)

**Comment by Rigellute** [comment]
Hmm... strange. Looks okay to me. 
<img width="843" alt="image" src="https://user-images.githubusercontent.com/12150276/69947962-a74b8780-14e6-11ea-854c-05ad7d394f87.png">

Not yet sure which commit might have messed with cursor position in your case.

**Comment by echoSayonara** [comment]
I'm not sure what caused this behavior but it seems to occur depending on terminal size.

51 lines in the window:
![spt_01](https://user-images.githubusercontent.com/54503126/69951921-87917f00-1539-11ea-8635-7a3e9d50599c.png)

43 lines in the window:
![spt_02](https://user-images.githubusercontent.com/54503126/69951932-8bbd9c80-1539-11ea-83b1-d23f4c47ea14.png)

**Comment by echoSayonara** [comment]
I found that the margin of main layout is set to 1 or 0 depending on terminal height (line 142 in `src/ui/mod.rs`) and this seems to cause the problem. To fix it, fix margin size to 0 or 1 regardless of terminal height or change cursor position when terminal height is lower than 45. If anyone does not fix it, I will do.

**Comment by stevensonmt** [comment]
Can confirm that larger terminal height fixes the cursor alignment. As for which commit, I don't know but I've got version 0.10.0 - 2019-11-30 showing up on the initial screen.

**Comment by Rigellute** [comment]
@echoSayonara ah yes of course!! I will PR a fix a bit later today
