### ISSUE TITLE
Album track list (Title list) only returns 40 entries

### ISSUE THREAD

**Issue by trames57** [Rigellute/spotify-tui#176]
When retrieving an album after a search that has a large number of tracks, the track list for the album only returns 40 entries.  I tried the Ctrl-d and it did not page to more tracks. Examples:

https://open.spotify.com/album/2SiUY7fgTpAxZk6H3Lya6t
https://open.spotify.com/album/40qIrKzta1myNjmhYKB9nf

Not sure it this is a limitation of the web API or not.

**Comment by Rigellute** [comment]
The web api has a max limit of 50 and `spotify-tui` attempts to set the limit to whatever your screen can hold (but still has a max of 50 on large screens).

Pagination (triggered by `ctrl-d` is not yet implemented in all screens)
