### ISSUE TITLE
Pagination of playlists

### ISSUE THREAD

**Issue by screamuch** [Rigellute/spotify-tui#181]
I cannot scroll past the "first page" of any playlist, meaning instead of scrolling through every song in the playlist, the UI loops through whatever is on the screen.

Example:
When I go to my Library/Playlist section and scroll down, everything is fine, I can scroll through all the entries. When I try to do so in the Songs section and reach the bottom entry, it just loops me back to the first song in a given playlist.

P.S.
I've looked into #150 but it doesn't seem to support actual playlists, rather lists of playlists.

**Comment by Rigellute** [comment]
This is confusing for sure - essentially there are two types of scrolling at the moment
1. Purely UI based
1. Spotify result `page` based

The first type currently wraps when you get to the last result. This is not intuitive for sure. When the user gets to the last result in the list, pressing down should send a request for the next result page.

I have made a bit of a mess when it comes to handling pagination, so not every screen currently supports it.

See here for more info https://github.com/Rigellute/spotify-tui/issues/113#issuecomment-559456942

**Comment by screamuch** [comment]
Oh, thanks for referring me to the right place, @Rigellute!

Couldn't find this info in any of the docs. I've tried `README.md`, `?` in-app. Are there any other places that describe user controls? I could make a PR that adds this info to the docs.

**Comment by Rigellute** [comment]
This is in the help menu, but I agree it is not that clear or obvious.
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/12150276/70048005-2ca36a80-15c1-11ea-8878-c0dcc03470ae.png">

**Comment by Rigellute** [comment]
Anyway, thanks for confirming that this works! Will think about how to make this more obvious.
