### ISSUE TITLE
add a config option to specify what port to listen on

### ISSUE THREAD

**Issue by ztmr** [Rigellute/spotify-tui#187]
While initializing the spt, webserver cannot be started because I have something else listening on the 8888 port. The URL seems to be hardcoded in the code.

It would be great if this port number was configurable.

**Comment by Rigellute** [comment]
Ah dang! Great idea, this would be fairly straightforward to implement if anyone wants to have a go.

**Comment by radogost** [comment]
I hope it's ok that I created a PR for this.

**Comment by UltraWelfare** [comment]
I think this should be closed as it is fixed by PR #204

**Comment by Rigellute** [comment]
Indeed you are right, thanks @UltraWelfare
