### ISSUE TITLE
Disallow scrolling past the end of a playlist

### ISSUE THREAD

**Issue by alichtman** [Rigellute/spotify-tui#192]
If you hammer on `Ctrl-D` for a while, you'll see that you can scroll past the end of a playlist. You need to press `Ctrl-U` as many times as you pressed `Ctrl-D` after the playlist had already been scrolled past in order to get back to the bottom.

I'd expect scrolling down to bottom out at the end of a playlist.

**Comment by Rigellute** [comment]
You're right. Needs fixing 👍

**Comment by Monkeyanator** [comment]
Took a swing at this in #216

**Comment by Rigellute** [comment]
#216 closes this
