### ISSUE TITLE
Not working in tty

### ISSUE THREAD

**Issue by jzbor** [Rigellute/spotify-tui#195]
I would really like running spt in the tty. Unfortunately I get 
`Error: ErrorMessage { msg: "failed to intialize clipboard context: XCB connection error: ClosedParseErr" }`
when I try to run it from tty. 
Is the application itself dependent on the X server? If so would it be considerable to change that?

Thanks though for your great work so far :)

**Comment by Rigellute** [comment]
Ah sorry to hear this! I think we need a way of disabling the clipboard via the config to avoid errors like this.

X server is required for clipboard support on Linux. 

There are some X server install instructions [here](https://github.com/aweinstock314/rust-clipboard#prerequisites) if you'd like to get it working for now.

**Comment by jzbor** [comment]
Thank you. I have X already installed - I just wanted to suggest it as a kind of "feature" for further development... :)

**Comment by telmotrooper** [comment]
Just started using the tool today and faced the same issue. I wonder if you can check if you're outside a X session to automatically disable the clipboard.
