### ISSUE TITLE
Text is invisible on white backgrounds

### ISSUE THREAD

**Issue by ayosec** [Rigellute/spotify-tui#196]
Most text is forced to be white on default background, so it is invisible if background is already white:

Example:

![shot](https://user-images.githubusercontent.com/37484/71383322-b6988f00-25d3-11ea-9727-eaae1088e7b9.png)

**Comment by Rigellute** [comment]
Ah! You're right, the colors are currently hardcoded for a dark theme.

**Comment by mdylanbell** [comment]
Are there any current efforts to expose color configuration to users?  Would you accept a PR for this (no promises!)?

**Comment by Rigellute** [comment]
I don't believe anyone is working on exposing the theme to user configuration. 

I absolutely would accept a PR for this! 

Let me know if you want to take a crack at it 👍 .

**Comment by Rigellute** [comment]
Users can now configure their own theme!
