### ISSUE TITLE
Authentication Error. INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by alichtman** [Rigellute/spotify-tui#2]
I have followed the instructions in the README and created the file in `~/.config/spotify-tui/client.yml` with the correct credentials, and it's being read correctly.

Here is the request being made with important parts removed:

```
$ spotify-tui
Opened https://accounts.spotify.com/authorize?scope=user-modify-playback-state%20user-read-playback-state%20user-read-private%20user-read-currently-playing%20playlist-read-private%20user-library-read%20user-read-recently-played&client_id=CLIENT_ID&redirect_uri=http:%2F%2Flocalhost:8888%2Fcallback&response_type=code&state=xvlgXiO7MBaweLQ6& in your browser
Enter the URL you were redirected to: 
```

Here's the error page I get:

<img width="588" alt="image" src="https://user-images.githubusercontent.com/20600565/64984378-05db6f00-d8c3-11e9-9f27-8f9d9bc19aca.png">

I'm noticing that the secret isn't included in the request. Should it be?

**Comment by Rigellute** [comment]
Ah sorry, there is an extra step I hadn't documented yet.

Go to your application you created in spotify -> click "Edit settings" and add `http://localhost:8888/callback` to the `Redirect URIs`

<img width="603" alt="Screenshot 2019-09-17 at 09 31 15" src="https://user-images.githubusercontent.com/12150276/65025104-fd6c4e00-d92d-11e9-9604-17794e579a1b.png">

**Comment by alichtman** [comment]
That worked for me. Thanks!

**Comment by steakknife** [comment]
Ran into this.

**Comment by Pi-George** [comment]
Can you please add this step to the setup instructions? This is still an issue

**Comment by Rigellute** [comment]
This step is documented in the [README](https://github.com/Rigellute/spotify-tui#connecting-to-spotifys-api)

**Comment by gmy77** [comment]
I have initially the same problem, only related to port... than i added but not i receive a page "Impossible to reach the page..."

**Comment by gmy77** [comment]
> I have initially the same problem, only related to port... than i added but now i receive a page "Impossible to reach the page..."

PS.... For an unknow reason... i tryed various times... now WORK...

Now perfetct.

**Comment by Watskebuurd** [comment]
sorry I have to reopen this again but since 9th of April 2025 it is not allowed anymore to use the localhost. Does somebody knows a workaround for this?

**Comment by sewnie** [comment]
Spotify-tui has unfortunately been abandoned by the author, and since then, the Spotify API changed signficantly, breaking this project.

Please use spotify_player: https://github.com/aome510/spotify-player, which is more feature-packed and more convenient.
