### ISSUE TITLE
No device_id selected

### ISSUE THREAD

**Issue by linuxundich** [Rigellute/spotify-tui#20]
I installed spt under Ubuntu 19.04 inside a virtualbox. I was able to connect spt to spotify. E.g. I can see a couple of play lists, I added. But as soon as I tray to play a song, I get the following error message.

Api response: No device_id selected
If you are trying to play a track, make sure the official

![spt](https://user-images.githubusercontent.com/1716643/66365836-aab30e80-e98e-11e9-8e20-fff2c273eafd.png)

```
$ spt --version
spotify-tui 0.4.0
```
//EDIT: After I started the spotify desktop app on one of my computers, this computer showed up as a device i can select. After that I can control the playback on that device, but I can't play music where I installed spotify tui. I do have a couple of connected sonos devices here in my network, they don't get detected.

![spt2](https://user-images.githubusercontent.com/1716643/66367819-0a60e800-e996-11e9-8a70-147d28ec7035.png)

//EDIT2: Ahaaaaa, when you maximize the terminal with spotify tui some explanations get shown. It's like responsive website. But the problem is, that the wrapping doesn't work properly. With a small window, there's no text at all. If you make the window bigger, the text will be cut. Only when you maximize the terminal application, you'll see the whole text.

![spt3](https://user-images.githubusercontent.com/1716643/66369587-54999780-e99d-11e9-955b-ad5f74bbaced.png)

**Comment by Rigellute** [comment]
Need to figure out how to make the text wrap.

**Comment by Rigellute** [comment]
I might reduce the amount of margin in this view, to accomodate small terminal sizes.
