### ISSUE TITLE
Extremely slow

### ISSUE THREAD

**Issue by gcantieni** [Rigellute/spotify-tui#207]
The app barely responds for me. I'll type `?` and it will take a minute or more before anything happens. It seems to work, e.g. connect to Spotify and has all my music, but it is delayed heavily with every action. I'm not sure if this is known, it might be the same bug as #92 but for me it was never "unfrozen".

I got spotifyd and spotify-tui from the AUR. 

Versions:
Operating System: Arch Linux
Kernel: Linux 5.4.8-arch1-1
spotifyd 0.2.20
spotify-tui 0.11.0

**Comment by EduRenesto** [comment]
It's running very slow to me as well. I'm on a very similar setup:

- Arch Linux
- Linux 5.4.7-arch1-1
- spotifyd 0.0.23
- spotify-tui 0.10.0

I'm using Alacritty and zsh.

**Comment by Rigellute** [comment]
Sorry to hear this.

I've just released a new version (0.12.0) which changes the terminal rendering backend (to support Windows).

Are you able to try again?

**Comment by echoSayonara** [comment]
Latest `rspotify` (added `async/await` support) may solve this problem.
https://github.com/ramsayleung/rspotify/issues/68
https://github.com/ramsayleung/rspotify/pull/70

**Comment by Rigellute** [comment]
I'm looking forward to this! It seems `rspotify` is still using the `blocking` variant of `reqwest` so we won't be able to use `async/await` just yet.

I do think this will improve performance.

**Comment by giorod** [comment]
FYI, extremely slow on my system aswell.

Arch Linux
Linux 5.4.7-arch1-1
spotifyd 0.2.24
spotify-tui 0.13.0

**Comment by Rigellute** [comment]
This is looking like an issue with Arch Linux, I don't have an Arch machine to hand to debug this unfortunately.

**Comment by Timvde** [comment]
FWIW: also an Arch user, and spotify-tui has always been snappy for me. So I don't think it's _just_ Arch.

**Comment by Rayqan** [comment]
Also running Arch and I have seen pretty smooth  performance on shorter lists but some "input" lag when scrolling through larger lists like my Liked Songs.

**Comment by roma41** [comment]
Same issue. Thought syslogs would hint me on what the cause of these lags were, but turns out - nothing odd. Also tried switching from Gnome to I3, but no result either. As of now am going to test application via Manjaro, to make sure whether it is specifically Arch Linux only issue.

**Comment by EduRenesto** [comment]
Maybe the problem isn't even in `spotify-tui` itself. I've been (non-scientifically) observing stuff, and `spotifyd` tends to crash after the freezing has stopped in `spt`. Also, I use `sp` to get metadata info for my bar, and it also tends to block. So, I'd look into `spotifyd` or even `rspotify` aside from `spt`. 

I'm going to look further into this when I have more free time.

**Comment by augustinreille** [comment]
Don't think this is an Arch-related problem, I have the same problem on MacOS (Mojave). I Installed spotify-tui with Homebrew.

**Comment by SimonSchubert** [comment]
I can confirm slow behaviour on macOS(Catalina), too. It happens sometimes and I couldn't figure out how to reproduce it. After waiting for a bit or restating spt it's running fine again.

OSX: 10.15.3
Terminal: 2.10 (433)
zsh: 5.7.1
spotifyd: 0.2.24

**Comment by Goahnary** [comment]
I'm having the same issue on a fresh installation. Very slow at times. I left my desk and when I came back it is totally unresponsive. Ctrl+c doesn't exit. Works after restarting though.

Anecdotally: Any time I make an action such as play/pause or anything else I am unable to do anything until that action is complete. More specifically I CAN still scroll through the list of songs but the UI does not update until my request to play/pause/whatever completes.

OSX: 10.14.2
iTerm: 3.3.9

**Comment by cornoctopus** [comment]
Hi, I've very similar issue,
Ubuntu 18.04
zsh 5.4.2
gnome-terminal 3.28.2
spotify-tui from snap store
Can't use app with zsh session (totally frozen), with bash session it's very, very slow

**Comment by Rigellute** [comment]
See this comment here for likely cause and solution for this issue https://github.com/Rigellute/spotify-tui/issues/92#issuecomment-590750383
