### ISSUE TITLE
Proxy settings are not used on Linux

### ISSUE THREAD

**Issue by kunerd** [Rigellute/spotify-tui#211]
Hi, 

while trying to open `spt` I get the following error:
```
thread '<unnamed>' panicked at 'send request failed: Error(Hyper(Error(Connect, Custom { kind: Other, error: "failed to lookup address information: Name or service not known" })), "https://accounts.spotify.com/api/token")', src/libcore/result.rs:1165:5
```

I think `spt` does not use my proxy. When using curl to request https://accounts.spotify.com/api/token I get a response.

**Comment by kunerd** [comment]
There is already an open ticket for rspotify:
https://github.com/ramsayleung/rspotify/issues/59

**Comment by Rigellute** [comment]
This linked issue from rspotify is now closed - looks like this was fixed when upgrading the reqwest library.

spotify-tui uses the updated version of rspotify so can we assume it is fixed?

Reopen if not!
