### ISSUE TITLE
Can I play all songs from an artist?

### ISSUE THREAD

**Issue by NeverI** [Rigellute/spotify-tui#213]
I think this feature is missing from the official app too and I do not understand why :sweat_smile: 

Okay, I can create a playlist with all her/hist album, but it would be awesome just hit a button and start playing all songs without bothering whatever album on its.

**Comment by Rigellute** [comment]
This should be fairly easy for us to implement. We just need to pass in the `artist_uri` to the `start_playback` context parameter. 

We also need to create a new binding to trigger this.

Contributions welcome!

**Comment by AlexandreSi** [comment]
Hi there,
I would be keen on opening my first PR on your repo!
Do you have some indications maybe?

**Comment by Rigellute** [comment]
Closed in #228
