### ISSUE TITLE
Don't close application when pressing q inside the playlist pane

### ISSUE THREAD

**Issue by worldpotato** [Rigellute/spotify-tui#221]
When I'm inside the "Playlist" pane and scrolling through the playlists, but want to switch to the "Library" pane I have to switch to the pane on the right (welcome or the current playlist) and than back to the left side. Because pressing `q` inside the playlist pane would close the application. 

I think not closing the application but switching to the pane selection mode would be a more intuitive behavior.

**Comment by Rigellute** [comment]
To switch panes you should be able to use `Escape` to enter "hover mode" which then lets you navigate around to select again.

`q` is meant to be the equivalent of the back button.

Hope that makes sense?
