### ISSUE TITLE
Can't access the search bar

### ISSUE THREAD

**Issue by watzon** [Rigellute/spotify-tui#276]
Don't know if this is actually a bug or if I'm just doing something wrong, but I'm on Fedora and have tried every way I can think of to go up to the search bar, but it never gets highlighted. All other panes are focusable.

I've tried several different terminal emulators including kitty, gnome terminal, and terminator, so I don't think that's it.

**Comment by watzon** [comment]
Nvm found the keybaord shortcut. It might be nice to be able to access the search bar the same way you do the other panels though.

**Comment by Rigellute** [comment]
Could be a good idea allow the search bar to be "hoverable" and then enter it

**Comment by snahmod** [comment]
For anyone with the same issue, the magic shortcut is `/`
