### ISSUE TITLE
`ctrl+j` does not work in latest version

### ISSUE THREAD

**Issue by echoSayonara** [Rigellute/spotify-tui#277]
I can use `ctrl + j` instead of `Enter` key to select albums, artists, and tracks selection in previous version(`v. 0.12.0`). However, latest version (unreleased) does not support this behavior. Does other behavior have been assigned to `ctrl + j`? If not and anyone does not dislike this behavior, I will reassign `Enter`'s behavior to `ctrl + j`.

**Comment by Rigellute** [comment]
Hmm... I've not seen `ctrl + j` as `Enter` in the codebase. `Enter` is a reserved key and is not user configurable at the moment. I would be open to letting `Enter` become user configurable, but not hardcoded to `ctrl + j`. 

Not sure how it was previously working?

**Comment by echoSayonara** [comment]
I found that this seems to be a `crossterm`'s problem.
https://github.com/crossterm-rs/crossterm/pull/373
