### ISSUE TITLE
Not working with spotifyd

### ISSUE THREAD

**Issue by wojciechkepka** [Rigellute/spotify-tui#28]
Hi, I'm currently trying to get `spotify-tui` to work with `spotifyd`. `spt` sees the currently playing song by `spotifyd`@mypc but won't allow me to control the daemon because of this error:
```
Error
Api response: Spotify API reported an error
If you are trying to play a track make sure the official spotify app is open
```

My `spotifyd` is installed from **AUR**.
kernel: `5.3.4-arch1-1-ARCH`
```
↳spotifyd --version
spotifyd 0.2.18
```
```
↳spt --version
spotify-tui 0.4.0
```
```
↳systemctl status --user spotifyd
● spotifyd.service - A spotify playing daemon
   Loaded: loaded (/etc/systemd/user/spotifyd.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-10-08 20:15:26 CEST; 9min ago
     Docs: https://github.com/Spotifyd/spotifyd
 Main PID: 81601 (spotifyd)
   CGroup: /user.slice/user-1000.slice/user@1000.service/spotifyd.service
           └─81601 /usr/bin/spotifyd --no-daemon

Oct 08 20:15:26 wojtas-arch spotifyd[81601]: 18:15:26 [INFO] Using alsa volume controller.
Oct 08 20:15:26 wojtas-arch spotifyd[81601]: 18:15:26 [INFO] Connecting to AP ""
Oct 08 20:15:26 wojtas-arch spotifyd[81601]: 18:15:26 [INFO] Authenticated as "" !
Oct 08 20:15:26 wojtas-arch spotifyd[81601]: 18:15:26 [INFO] Country: "PL"
Oct 08 20:15:36 wojtas-arch spotifyd[81601]: 18:15:36 [INFO] Loading track "I Hear A Rhapsody" with Spotify URI "spotify:track:2oEvw0AfrT2fPNpEnBwVml"
Oct 08 20:15:37 wojtas-arch spotifyd[81601]: 18:15:37 [INFO] Track "I Hear A Rhapsody" loaded
```

**Comment by Rigellute** [comment]
Hmm... I need to try myself.

Perhaps you've already done this, but have you selected `spotifyd` as a "device"?

Does `spotifyd` show up when you press `d`?

**Comment by wojciechkepka** [comment]
Well now it is indeed working as intended :) thanks for the quick reply! Love the idea behind the app and how snappy it is! I've been wanting to write one like this myself one day  :)

**Comment by Rigellute** [comment]
Great to hear! And thank you 🙏

**Comment by KennethAshley** [comment]
Do we have to select the device on each use? 

Great software thanks!

**Comment by Rigellute** [comment]
The last selected device ID is cached (you can see it in `~/.config/spotify-tui/client/yml`), so you shouldn't need to select it on each use.

Just make sure that device is active if you're having playback issues.

And thank you!
