### ISSUE TITLE
Possibility to define color-scheme?

### ISSUE THREAD

**Issue by kharann** [Rigellute/spotify-tui#283]
Is it possible to configure which colors spotify-tui uses? It seems like the colors it chose from my terminal is kinda too dark for my taste. A tad hard to read for my taste

![image](https://user-images.githubusercontent.com/41551253/73893560-ec3ac400-4871-11ea-826d-848824814860.png)

**Comment by Rigellute** [comment]
This is not currently possible, I do plan to look into it though.

**Comment by kharann** [comment]
Thanks man!
