### ISSUE TITLE
stuck after "Enter port of redirect uri (default 8888):"

### ISSUE THREAD

**Issue by hedich** [Rigellute/spotify-tui#297]
expected this: "You will be redirected to an official Spotify webpage to ask you for permissions."
however nothing happens at all (no webpage opens), what am i missing? 

using spotify-tui-0.14.0-1 from AUR

**Comment by hedich** [comment]
i had for some reason not setup a browser properly for the terminal i was using, fixed now.

**Comment by hongkongkiwi** [comment]
Can you have a headless option? It does produce a URL but it seems to not be listening for a response on it if it can't open a browser (I'm trying to setup a docker).

**Comment by Rigellute** [comment]
The closest thing we have to a headless option at the moment is to take the url returned by the redirect uri and making a curl get request to spotify-tui server
