### ISSUE TITLE
Help menu is clipped if terminal height is not large enough

### ISSUE THREAD

**Issue by pedrohva** [Rigellute/spotify-tui#301]
The full help menu is not displayed if the terminal is too small and there is no way to scroll down to see the other commands without having to resize the terminal window. 
![spt_help_menu_screnshot](https://user-images.githubusercontent.com/33297928/74845997-90ab1480-530e-11ea-80c8-cca17a7d6ce7.png)

**Comment by Rigellute** [comment]
You're right, this is an issue that needs fixing!
