### ISSUE TITLE
Add to Queue command

### ISSUE THREAD

**Issue by mikeboiko** [Rigellute/spotify-tui#304]
Would it be possible to add a command for "Add to Queue"?
I use this feature all the time on my Android phone.
I love spotify-tui, thanks for allowing me to live in my terminal even more!

**Comment by pedrohva** [comment]
I'm pretty interested in this feature as well but [rspotify](https://docs.rs/rspotify/0.8.0/rspotify/spotify/client/struct.Spotify.html) doesn't seem to have any options to add a song to a queue. I can't seem to find anything on the Spotify Web API Reference either.

**Comment by mikeboiko** [comment]
Yea you're right, everyone is still waiting on Spotify to add the API endpoint:
https://github.com/spotify/web-api/issues/462

**Comment by Rigellute** [comment]
I'd love this feature too

**Comment by Bios-Marcel** [comment]
Doesn't look like spotify gives a damn about this. Alternatively a local queue could be added.

Something like "OnSongEnd: if queue.size > 0; play(queue.pop)". The queue could be completly unrelated to playing playlists, albums or radios, just the like the official queue. I think this would be a great compromise.

**Comment by Rigellute** [comment]
Ah cool! Looks like this is a new endpoint not yet covered by `rspotify`, I will look into adding it there so we can start supporting queues!

**Comment by austenmyers** [comment]
Any updates on the queuing feature?

**Comment by Rigellute** [comment]
Looks like `rspotify` has added this endpoint as of yesterday 🎉  https://github.com/ramsayleung/rspotify/commits/master

Once `rspotify` has released we can start working on it 👍

**Comment by tonitch** [comment]
it seems implemented in rspotify now. I really wanted to try implementing it but... 
I neved did rust before :'(
any update for this tho?

**Comment by Rigellute** [comment]
Thanks to @BeneCollyridam this is now possible!

**Comment by mikeboiko** [comment]
Awesome, good work everybody!
