### ISSUE TITLE
Exiting the audio visualizer messes up focus and layout

### ISSUE THREAD

**Issue by Bios-Marcel** [Rigellute/spotify-tui#314]
When quiting the audo visualizer with "ESC", the center panel gets removed, there's not even a border left, so I assume the component is gone. The focus is also gone, meaning that you can't navigate back to any other components using the arrow keys. A workaround is entering the searchbar via it's shortcut for example.

![grafik](https://user-images.githubusercontent.com/19377618/75338270-ba27eb00-588e-11ea-9cba-c61a181df642.png)

**Comment by Rigellute** [comment]
Oops! Good find, will fix.
