### ISSUE TITLE
a playback device must be either an spotify client

### ISSUE THREAD

**Issue by JGcarvajal** [Rigellute/spotify-tui#316]
Hi, how are you?
Thank you for the great effort in creating spotify tui.
I am using to implement but I encountered a problem, I already created my Client ID and link my spotify developer secret key, and when playing from the official apps what I am hearing is displayed in your app, but when trying to play from your app is throwing me error 403, and the help it throws at me is "a playback device must be either an official spotify client or a light weight alternative such as spotifyd". 
Thank you and I hope you can help me solve

**Comment by JGcarvajal** [comment]
By the way, the client I'm using is windows

**Comment by Rigellute** [comment]
Hi @JGcarvajal, sounds like you need to press `d` to select a device that will control playback (`spotify-tui` doesn't handle streaming audio, instead you'll need something like `spotifyd` or the official client running and you need to select that device from within `spotify-tui`)

**Comment by Colocasian** [comment]
I'm also trying to use `spotify-tui`, although I have selected my phone within the list of devices, it is still not playing it on my phone, but rather calling the same error 403. Btw, is Spotify Premium necessary for playing songs on my phone from tui?

**Comment by MrPoliteGrizlyM** [comment]
Hi, have the same issue but I'm using MAC. However, when I play music on my phone, I see title of the song that I'm playing.

**Comment by JGcarvajal** [comment]
Hello @Rigellute, I know that Spotify-tui will be only the controller and I must have my account linked to an official app, desktop or mobile, and although I have it in reproduction in my official app, spotify-tui continues to throw error 403, saying that I must link a device with the app even if I already have it.
Attached error image in case it helps
Thanks for your help
![Error 403 spotify-tui](https://user-images.githubusercontent.com/43095913/75676131-a3024800-5c56-11ea-8934-7270f2e62d54.PNG)

**Comment by Rigellute** [comment]
To confirm, spotify premium is needed to control playback,

@JGcarvajal what do you see when you type `d`? This will bring up the device selection menu

**Comment by Rigellute** [comment]
Still having any issues with this? Please reopen if there is still an issue
