### ISSUE TITLE
Basic view

### ISSUE THREAD

**Issue by boardfish** [Rigellute/spotify-tui#320]
This would go really nicely with #158 for me - I've got a spare screen in the room I'm staying in for the rest of the year, and it'd be really nice to devote it purely to showing the current state of Spotify using a Raspberry Pi. I'd like to be able to switch to a view in which the playbar pane at the bottom is centered in the middle of the screen.

Ideally, I'd have liked to have seen the Play Queue beneath it too as in #145, but that doesn't seem possible, especially given the recency of the issue.

**Comment by Rigellute** [comment]
I've just looked into implementing this basic view (centered playbar without the queue)

What do you think?

<img width="1113" alt="Screenshot 2020-03-17 at 16 01 06" src="https://user-images.githubusercontent.com/12150276/76875876-0e5c3480-6869-11ea-8b94-3e2247137466.png">

**Comment by boardfish** [comment]
The irony that I've had to leave said room due to COVID-19 isn't lost on me one bit. Regardless, this is just what I wanted. Thanks!
