### ISSUE TITLE
Lags after long runtime

### ISSUE THREAD

**Issue by Bios-Marcel** [Rigellute/spotify-tui#323]
After having the application open for a while, without doing anything, everything gets laggy. Even down to the keyinputs. I am not sure what is happening here and i don't know how to debug it. The CPU usage barely hits 5% and the memory usage is rather low too. 20MB actually used with 360MB~ VIRT memory. There doesn't seem to be network traffic either. So I really don't know. It doesn't show what song is playing though. So, maybe there is no connection and that's why it's having troubles?

Is there anything simple I can do further investigate this?

**Comment by Rigellute** [comment]
My guess is that the machine's internet changed whilst `spotify-tui` was running and this blocked the UI thread from running.

I am working on this exact issue in #322 - I still need to check the behaviour of leaving the app open for a while letting the computer sleep/losing internet connection.

**Comment by Bios-Marcel** [comment]
Wdym "the internet" changed?

**Comment by Rigellute** [comment]
From the #322 PR I let it run for 3 hours and it doesn't get stuck/lag.

**Comment by Rigellute** [comment]
Should be fixed in 0.16.0

**Comment by Bios-Marcel** [comment]
Nice, glad to hear that. Thanks :)
