### ISSUE TITLE
How to return to the previous view?

### ISSUE THREAD

**Issue by Bios-Marcel** [Rigellute/spotify-tui#326]
Hey,

I was wondering whether it's possible to go back a step. For example I open the artist "GoGo Penguin" and then chose the album "Man Made Object", I decide that it's not what I want to listen to and want to go back to the album overview. Currently I have to hit "Ctrl+Shift+/" to get into the searchbar, hit enter, choose the artist and then go to albums.

**Comment by Rigellute** [comment]
To jump back to previous view you can press `q`!

**Comment by Bios-Marcel** [comment]
Oh, I didn't find this in the shortcut overview, my bad :)

thanks

**Comment by Bios-Marcel** [comment]
Maybe a search would be cool 🤷‍♂
