### ISSUE TITLE
It's possible to accidentaly quit the application while trying to quit the audio analysis screen

### ISSUE THREAD

**Issue by ericonr** [Rigellute/spotify-tui#332]
As mentioned in #322 

>When I press `v` to open the audio visualizer, if I press `q` before it loads the visualizer, the quit action is passed to whatever context I'm in, meaning it can even close the application. Testing in the previous version, pressing `q` before the visualizer opened just means that the visualizer will quickly flash on the screen, because it's closed right after.

It still happens in latest master `c0adca85`.

**Comment by Rigellute** [comment]
Thanks for reporting @ericonr. 

This highlights a larger issue - async navigation.

To fix these problems, I think we should eagerly navigate to a screen before the network request has finished. Some screens already work like this.

If anyone wants to contribute, try to find places where `app.push_navigation_stack(...)` is invoked _after_ some `await`. Ideally, these navigation events should not happen within `network.rs`, but rather at the call site of `app.dispatch` (in `app.rs` for example).

You might encounter UI problems with this, however. To fix these, we need to have a fallback UI for when the data is not ready/not present.

**Comment by ericonr** [comment]
@Rigellute have you noticed this issue anywhere else? Otherwise I believe I can close it already.

**Comment by Rigellute** [comment]
Not noticed this anywhere else, will close.

Thanks @ericonr 👍
