### ISSUE TITLE
Continue playing music from songs pane once started

### ISSUE THREAD

**Issue by gregf** [Rigellute/spotify-tui#334]
When I start playing songs from a artist in the Songs pane, it would be nice if it kept playing through what is in the list till it reaches the end. This would be like in the official spottily client when you play the top songs from the artist, it continues to play through them. 

I know about the recommended section, this is a different list of songs all together.

![2020-03-14_08-19](https://user-images.githubusercontent.com/980/76681745-b4d7d980-65cc-11ea-9e3c-b9d2ec192cc0.png)

Lastly, thank you so much. This has been amazing. I can finally use my spottily in FreeBSD.

**Comment by Rigellute** [comment]
Thank you @gregf, so great to hear that you're enjoying `spotify-tui`!

I will look into this
