### ISSUE TITLE
spt only playing songs from "Recently Played" or "Liked Songs"

### ISSUE THREAD

**Issue by hshackle** [Rigellute/spotify-tui#336]
Title is pretty self-explanatory, although it seems like a very weird bug. If I try to play any song from my "Recently Played" or "Liked Songs" list, they'll play fine. However, if I try to play anything else - from my playlists, from my saved albums, from searching for an album - nothing happens. If a song was playing currently, attempting to play a song from any of these groups will stop the current song from playing, but the new song will not come on, nor will the bar at the bottom of the window reflect the fact that a new song has been selected. I've also tried the "play all tracks for artist" command, and nothing happens with that as well. I installed spotify-tui on Arch via the AUR, and am using the standard Spotify app as a client.

**Comment by Rigellute** [comment]
Hmm... strange indeed! 

I've seen this myself. Which version of spotify-tui are you running?

```sh
spt --version
```

**Comment by hshackle** [comment]
v0.16.0

**Comment by Rigellute** [comment]
Do you still experience this as of release v0.17.1?

**Comment by hshackle** [comment]
Nope! It works now, thanks a lot.
