### ISSUE TITLE
Can't play tracks from spotify-tui

### ISSUE THREAD

**Issue by warmerspy** [Rigellute/spotify-tui#34]
When I try to launch a start a track I get an error message saying:
"Api response: Spotify API reported an error. 
If you are trying to play a track, make sure the offical spotify app is open"

And it is open I can even see what song is currently playing.

**Comment by Rigellute** [comment]
I should probably add more info to that error. Make sure your device is selected (press `d` to bring up device list and select your device), then it should start working.

**Comment by warmerspy** [comment]
I have done that but still it doesn't want to play.

**Comment by Rigellute** [comment]
Try following these debugging points from `spotifyd` https://github.com/Spotifyd/spotifyd#logging

I can choose `spotifyd` from my device list and play tracks on it with no issue

**Comment by kylecarbs** [comment]
It's listed as a limitation in the README.

> This app uses the Web API from Spotify, which doesn't handle streaming itself. So you'll need either an official Spotify client open or a lighter weight alternative such as spotifyd. <br>
If you want to play tracks, Spotify requires that you have a Premium account.

https://github.com/Rigellute/spotify-tui#limitations

**Comment by Rigellute** [comment]
The next release will contain a slightly better error message to reflect this https://github.com/Rigellute/spotify-tui/commit/163a4b22ef3eec4b503aa586d1b64f02b1ea755c
