### ISSUE TITLE
Allow Specifying Alternative Config File Path

### ISSUE THREAD

**Issue by Rayqan** [Rigellute/spotify-tui#355]
Just noticed this project doesn't have an option to use a different config path, would be fantastic if that could be implemented.

**Comment by Rigellute** [comment]
We could implement passing the alternate config file path via a command line argument? You could then alias `spt` so that it includes your alternate path?

e.g.
```sh
spt --config=path/to/config.yml
```

**Comment by Rayqan** [comment]
Yep, that's perfect.
