### ISSUE TITLE
unable to use the application with spotifyd

### ISSUE THREAD

**Issue by turing753** [Rigellute/spotify-tui#36]
I do have a Premium account. Spotifyd is able to connect to Spotify, and I am using pulseaudio as the backend. But spotify-tui just says that I need to have the official app open.

**Comment by Rigellute** [comment]
I need to update that error message as `spotifyd` somewhat "qualifies" as an "official" spotify client.

Make sure that your `spotifyd` device appears in the device list - press `d` to see the list and select it.

Then try to play a track?

**Comment by Rigellute** [comment]
Try following these debugging points from spotifyd https://github.com/Spotifyd/spotifyd#logging

Namely, see the logs using `./spotifyd --no-daemon` and ensure that

1. You've given your username and password to `spotifyd` and can see the auth success log
1. Your device name has no spaces

I can choose spotifyd from my device list and play tracks on it with no issue

**Comment by turing753** [comment]
> I need to update that error message as `spotifyd` somewhat "qualifies" as an "official" spotify client.
> 
> Make sure that your `spotifyd` device appears in the device list - press `d` to see the list and select it.
> 
> Then try to play a track?

Pressing d and selecting the device was the key! I guess I missed that option. Thank you! Now I can get rid of the bloatfilled default Spotify app.
