### ISSUE TITLE
Os

### ISSUE THREAD

**Issue by xkrido** [Rigellute/spotify-tui#360]
Can the Spotify Tui application be used on Windows 7?

**Comment by InfInt** [comment]
I do not advise doing so, but if you have the Microsoft Windows Visual C++ Redistributable for Visual Studio (2015,2017,2019) installed. It sure runs on Windows 7. Well, it started without errors, at least. I urge you to update to a more modern operating system if you can.

**Comment by Rigellute** [comment]
No plans to get spotify-tui working on Windows 7. Thank you for the suggestion @InfInt 👍
