### ISSUE TITLE
Help menu doesn't include basic mode

### ISSUE THREAD

**Issue by The-Bob** [Rigellute/spotify-tui#361]
Version: `spotify-tui 0.17.0`
`spotify-tui` package from aur via yay

My help menu is missing the 'B' shortcut to enter the basic view added in #320. According to [this commit](https://github.com/Rigellute/spotify-tui/commit/fcde7fe24d48e6038603a725ff20e3330e94061f) it should be between "v" (audio analysis) and "q" (Go back)

![image](https://user-images.githubusercontent.com/31973884/77712694-c5575f00-6f91-11ea-8ce0-4254f413f63a.png)

Edit: I installed the `spotify-tui-git` package, and it is displaying the option correctly, despite reporting the same version number of 0.17.0
![image](https://user-images.githubusercontent.com/31973884/77713085-b6bd7780-6f92-11ea-889e-1471ee64779f.png)

**Comment by Rigellute** [comment]
Sorry yes, I cut the 0.17.0 release before adding that commit. Will be fixed in the next release!

**Comment by Rigellute** [comment]
Fixed in 0.17.1
