### ISSUE TITLE
How to integrate with NCSpot player?

### ISSUE THREAD

**Issue by slaveofcode** [Rigellute/spotify-tui#363]
Hi thank you for this awesome tool, I have some question about integrating to ncspot player, is there any way to do that?

**Comment by Rigellute** [comment]
There's no way to integrate `spotify-tui` with `ncspot` currently - `spotify-tui` uses the Connect API from Spotify and provices no audio playback backend, whereas `ncspot`does bring an audio backend with it (which is very cool!)
