### ISSUE TITLE
Artist name not showing in Songs pane when searching 

### ISSUE THREAD

**Issue by maxim-sm** [Rigellute/spotify-tui#364]
**Issue:** The name of the artist doesn't show in the song pane when searching. Only the names of the songs are present.
**spotify-tui Version**: 0.17.0 installed with snap
**OS:** Ubuntu Mate 18.04
**Spotify Client:** Official Spotify client for Linux

**Screenshot when searching for "Metallica":**
![Screenshot at 2020-03-27 12-13-26](https://user-images.githubusercontent.com/17222086/77740663-89f97680-700b-11ea-86fe-b2f9248bddb2.png)

I'm sorry if I missed anything and it isn't a bug.
Thanks!

**Comment by GrudgeDuck** [comment]
I'm not sure why I deleted artist name from song pane in [previous commit](https://github.com/Rigellute/spotify-tui/commit/527982b1c71769b0c7bebee61fe1a3c3682f9fbb#diff-6dc45dfc736c715dfe4e91a675f9b22e). I'm sorry and thank you for reporting this bug. I've fixed it in #365 .

**Comment by maxim-sm** [comment]
Thanks for the quick fix!
