### ISSUE TITLE
Cargo.lock is invalid

### ISSUE THREAD

**Issue by Jannik2099** [Rigellute/spotify-tui#375]
Affected version: v0.17.1 , possibly others

The Cargo.lock file is invalid, it contains wrong package versions. This causes an issue with offline builds. Regenerating the lock file with `cargo generate-lockfile` fixes this.

Not a high priority fix by any means, but confused me when I tried to package the new version.

**Comment by Rigellute** [comment]
Thanks for letting me know! Not sure how this happened!
