### ISSUE TITLE
Exit code 101

### ISSUE THREAD

**Issue by tom-doerr** [Rigellute/spotify-tui#378]
When I execute `spt` it fails to start, although it used to work with version `0.16.0` I tested different versions but the error remains the same.
```
➜  ~ .cargo/bin/spt -V
spotify-tui 0.17.1
➜  ~ .cargo/bin/spt   
➜  ~ echo $?          
101
➜  ~ 
➜  ~ spt -V
spotify-tui 0.16.0
➜  ~ spt
➜  ~ echo $?
101
```
Creating a new Client ID didn't help either. 
Any ideas?

**Comment by Rigellute** [comment]
Hmm... not sure.

Which OS are you using?

**Comment by tom-doerr** [comment]
Linux Mint - it's based on Ubuntu 18.04.
I just remembered that it stopped working right after my computer ran out of storage, is it possible that spt tried to write to some file which resulted in that file becoming corrupted?

**Comment by Rigellute** [comment]
That is possible yes! On every launch, authentication is performed and might attempt to persist the auth token to the file system. It's possible that this was the cause of your exit code.

**Comment by tom-doerr** [comment]
Do you know where auth token is stored?  I couldn't find anything on my file system.

**Comment by Rigellute** [comment]
The auth tokens are persisted here `${HOME}/.config/spotify-tui/client.yml`

**Comment by tom-doerr** [comment]
There were other files in that directory that seemed to be related to caching. After I deleted those and started spotify-tui, I was prompted to log into Spotify.

**Comment by Rigellute** [comment]
Thanks @tom-doerr
