### ISSUE TITLE
Not redrawing in tmux

### ISSUE THREAD

**Issue by danjenson** [Rigellute/spotify-tui#382]
I run spotify-tui in a tmux pane and I find that it often doesn't redraw itself/gets out of sync switching between windows. Here is a screenshot of what it looks like only a few minutes/few switches after starting: 
![screenshot-2020-04-07-08:11:36](https://user-images.githubusercontent.com/4793438/78686290-b6cd4980-78a7-11ea-8efb-692f5f88988e.png)

**Comment by danjenson** [comment]
this was actually caused by my image compositor and was fixed in picom with `xrender-sync = true` and `xrender-sync-fence = true` if anyone else stumbles upon this

**Comment by Rigellute** [comment]
Thanks for posting the solution @danjenson 👍
