### ISSUE TITLE
Artists names in featurings of album mixes

### ISSUE THREAD

**Issue by MrZeroo00** [Rigellute/spotify-tui#387]
Issue: the name of the artists doesn't appear in the album view. This can be an issue when there are multiple authors for a song or when it's a mix album by various artists.
spotify-tui Version: 0.17.1 
OS: macOS Catalina 10.15.4
Spotify Client: Official Spotify client for macOS

Screenshot for album 'Music For Containment' :
<img width="1439" alt="Screenshot 2020-04-08 at 15 20 10" src="https://user-images.githubusercontent.com/7818591/78788704-71467480-79ac-11ea-8810-a2640f75263e.png">

Would it be possible to add artists names like in the official client?
<img width="1439" alt="Screenshot 2020-04-08 at 15 21 34" src="https://user-images.githubusercontent.com/7818591/78788851-a357d680-79ac-11ea-8110-102151061d15.png">

I'm sorry if I missed anything and it isn't a bug.
Thanks!

**Comment by Rigellute** [comment]
Sounds like a good idea 👍 . 

Contributions welcome!
