### ISSUE TITLE
Crash when opening a playlist.

### ISSUE THREAD

**Issue by slumber** [Rigellute/spotify-tui#394]
I have found a single playlist which causes a crash so far, but still it seems weird.
OS: ArchLinux 5.6.3-arch1-1
Steps to reproduce:
search for 'eminem' and try to open 'This is Eminem' playlist.
The stacktrace states that this is caused by `unwrap()` call at src/network.rs:361.

I don't have a premium account yet, but other playlists can be opened just fine, so I believe some kind of check is necessary to avoid such behavior.

```thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/network.rs:361:23```

**Comment by Rigellute** [comment]
Thanks for reporting @slumber
