### ISSUE TITLE
.cached_device_id.txt and .spotify_token_cache.json files created in same directory as $ spotify-tui command

### ISSUE THREAD

**Issue by alichtman** [Rigellute/spotify-tui#4]
I think these should be created in the config directory. If you run `$ spotify-tui` in a directory, and then move directories and do it again, it makes you reauth since it can't find the cached tokens.

**Comment by alichtman** [comment]
Temporary fix: `alias spotify='(cd ~/.config/spotify-tui && spotify-tui)'`

**Comment by Rigellute** [comment]
I think you're right. 

Currently, I am just leveraging the underlying spotify library to handle the caching of the token. But I can manually implement this and put it all into the config. Same goes for the cached `device_id`.

**Comment by Rigellute** [comment]
The latest release has moved all credentials to `~/.config/spotify-tui`. Please check it out.

That release also lets you install via `brew`

```
brew install Rigellute/tap/spotify-tui
```

You can then run it with `spt`.
