### ISSUE TITLE
missing client.yml

### ISSUE THREAD

**Issue by 3l0w** [Rigellute/spotify-tui#403]
I install spotify-tui as snap `snap install spt --edge`
but i enter wrong clientID and client secret so i wanna change but client.yml located in $HOME/.config/spotify-tui/client.yml doesn't exist.
I find this path with spt --help.

**Comment by 3l0w** [comment]
i found the file in : `/home/fl0w/snap/spt/212/.config/spotify-tui/client.yml`

**Comment by Rigellute** [comment]
Thanks for updating the solution, looks like this is a quirk of installing via snap.
