### ISSUE TITLE
Analysis Menu API error

### ISSUE THREAD

**Issue by Just-Insane** [Rigellute/spotify-tui#416]
When trying to open the analysis menu (default key "v"), I get an API error:

```
Api response: convert result failed, reason: Error("invalid type: string \"1585453096\", expected u64", line: 6, column: 29); content: ...
```
![Screen Shot 2020-04-25 at 9 52 26 PM](https://user-images.githubusercontent.com/15903884/80295229-1f894280-873f-11ea-9daf-926226d70d75.png)

Notes:
MacOS 10.15.4
Using spotifyd
Installed via Brew - version:  v0.18.0

Everything else seems to be working fine.

**Comment by Rigellute** [comment]
Oh good catch. Looks like this the spotify API has recently started returning the `timestamp` property as a string rather than `u64`. 

The fix for this will need to be in `rspotify`.

**Comment by Just-Insane** [comment]
Awesome, I will open an issue over there then.

**Comment by Rigellute** [comment]
I created a potential fix in rspotify, but the author correctly suggests the upstream spotify API needs to fix their docs/implementation first https://github.com/ramsayleung/rspotify/pull/94

Whilst we are waiting for a better fix, I can try using my fork of rspotify to fix the audio feature

**Comment by Crowly34** [comment]
Hello, 0.19.0 still is failing me, thanks for the great tool btw, loving it!.

![image](https://user-images.githubusercontent.com/29908764/83091422-c58edc00-a060-11ea-9fa1-378a7d686b85.png)

**Comment by Rigellute** [comment]
This is now fixed in master, I will cut a new release shortly.
