### ISSUE TITLE
Config broken

### ISSUE THREAD

**Issue by jerozerbib** [Rigellute/spotify-tui#42]
It seems that after downloading the binary from `cargo`, I do not have a working config file

Posting a blank config working could solve this issue.

```Error: Message("invalid type: unit value, expected struct ClientConfig", Some(Pos { marker: Marker { index: 6, line: 4, col: 0 }, path: "." }))```

This is my error message.

**Comment by jerozerbib** [comment]
```


---
```


That's the config


But deleting it fixed it !

**Comment by Rigellute** [comment]
Hmm... something must have gone wrong during first setup. 

Great that it's fixed 👍
