### ISSUE TITLE
Slow connection leads to large delay between tracks

### ISSUE THREAD

**Issue by Wulfsta** [Rigellute/spotify-tui#423]
I've noticed that (while using a spotifyd backend) there can be large delays between tracks with a slow internet connection. I don't know what the architecture of this code looks like, but is there anywhere that caching of the next track expected to play can be introduced to prevent these delays? I know that spotifyd has a cache directory, so I suspect this is probably a feature to request on their side and use here.

**Comment by Rigellute** [comment]
This sounds like a an issue for `spotifyd`.

Worth noting that this issue is not seen when using the official spotify client as playback device whilst on a slow connection.
