### ISSUE TITLE
Jump to current playlist command

### ISSUE THREAD

**Issue by maujim** [Rigellute/spotify-tui#424]
Is it possible to add in a command to jump to the current playlist, similar to the jump to album and jump to artist's album commands?

**Comment by Rigellute** [comment]
That is not currently possible, but sounds like it would be a nice feature. 

I just had a quick look through the spotify docs and didn't find a "playlist_id" in the playback context which we would need to jump to the playlist. 

However, a workaround might be to parse out the id from the context uri when the `type` property `== "playlist"`.

Example context from the api

```json
"context": {
    "external_urls" : {
      "spotify" : "http://open.spotify.com/user/spotify/playlist/49znshcYJROspEqBoHg3Sv"
    },
    "href" : "https://api.spotify.com/v1/users/spotify/playlists/49znshcYJROspEqBoHg3Sv",
    "type" : "playlist",
    "uri" : "spotify:user:spotify:playlist:49znshcYJROspEqBoHg3Sv"
  }
}
```

This could be a good first issue!

**Comment by Drewsapple** [comment]
I think #474 implemented this feature. Ready to close?

**Comment by Rigellute** [comment]
Yep, thanks @Drewsapple
