### ISSUE TITLE
Provide a cli arg based interface

### ISSUE THREAD

**Issue by clearnote01** [Rigellute/spotify-tui#429]
I want to trigger commands that goes through spotify-tui but doesn't open the UI. For starters support for search/play/pause through command line would be really good to have.

spt -s --search "a man of wire"  // returns top n results
spt -p --play "song name" // based on closest match, start playing this song
spt -t --toggle // toggle play pause

**Comment by Rigellute** [comment]
Could be an interesting addition 👍 , will require some architectural changes but is doable

**Comment by dvdmuckle** [comment]
It would also be great to have something like `spt --status` to show the currently playing song. 

As an aside, there are several tools that allow a CLI arg based interface for Spotify, but they're very fragmented and aren't all mutliplatform, and generally control Spotify in different ways (DBUS/MPRIS for Linux or oascript for Mac) as opposed to interfacing with the Spotify API.

**Comment by Dragonsong3k** [comment]
> I want to trigger commands that goes through spotify-tui but doesn't open the UI. For starters support for search/play/pause through command line would be really good to have.
> 
> spt -s --search "a man of wire" // returns top n results
> spt -p --play "song name" // based on closest match, start playing this song
> spt -t --toggle // toggle play pause

Launching a playlist in shuffle mode would be great!
spt -p "some playlist name" -s ( --shuffle)

**Comment by dann-merlin** [comment]
I think that sounds more like a separate program. Something like this [script](https://gist.github.com/wandernauta/6800547) referenced by spotifyd's README, but more powerful.

**Comment by OrangeFran** [comment]
I picked this up yesterday. Expect a demo this evening :)

**Comment by OrangeFran** [comment]
Never used imgur, I hope it works: [here](https://imgur.com/a/eE7ft1g).

**Comment by OrangeFran** [comment]
I actually did not have to change anything internally. Currently I'm not really happy with the cli.rs file, it seems so unordered. I have to look into that. If you want to try it out, you can use the cli branch on my fork.

**Comment by OrangeFran** [comment]
I did some huge changes to the cli:

There are three main subcommands: `play` to play a song, `playback` to interact with the playback and `query` to list and search categories. One of my favourite things is the fact that you can format almost any output with a simple string where `%a` -> artist, `%b` -> album, `%t` -> track, `%h` -> show, `%f` -> flags (like, shuffle, repeat), `%p` -> playlist, `%d` -> current device and `%s` -> playing status. I really hope it is intuitive enough.

**Comment by spenat28** [comment]
Good work, thanks i have one problem
--like does toggle the like
which makes it dangerous to use without looking into app first - which makes it unusable

Solution is:
--like to always add to liked songs not toggle like - to unlike them and add --dislike
OR:
provide any command to tell if song is already liked
spt pb --is_liked

**Comment by OrangeFran** [comment]
Would just updating the help menu be sufficient? In the tui `s` toggles the like as well.

**Comment by spenat28** [comment]
Well,
the thing is, you are listening to the song, and you are in terminal. You like it, so you want to add it to liked songs. More often than not, it is already in your liked songs. And you dislike it by accident.

So i would really prefer to have an option to alway like the song instead of a toggle or any way to find out from terminal command if song is already liked and skip the like programmatically.

**Comment by OrangeFran** [comment]
This makes sense. I just remembered that it actually happened to me once. I'm working on it.

**Comment by spenat28** [comment]
@OrangeFran Thank you!

**Comment by clearnote01** [comment]
Thanks @OrangeFran ! Closing this ticket!
