### ISSUE TITLE
help menu has pagination key too far down (hen/egg problem)

### ISSUE THREAD

**Issue by mhellwig** [Rigellute/spotify-tui#439]
when looking at the help menu, the key for pagination (ctrl-d) is only mentioned so far down that on regular terminals, you won't see it on the first page. Meaning that if you don't know that ctrl-d is for pagination and head to help to find out all the keys, you'll never know that there's more than one page of content there (or anywhere else for that matter). Trying space or pg-down (which I did) obviously doesn't help. Only reading some (as far as I could tell) unrelated issue about playlists here caused me to realize that ctrl-d was for pagination (since it's not really discoverable - I mean UNIX convention would dictate a different meaning to ctrl-D, right?).

So .. put it in the first line of the help, maybe?

**Comment by Rigellute** [comment]
Could be a good idea. 

Contributions welcome! This will simply a matter of moving the "Pagination" related items in the help menu vector to the start of that vector (see [here](https://github.com/Rigellute/spotify-tui/blob/master/src/ui/help.rs#L103))

I also like the idea to make the help menu searchable https://github.com/Rigellute/spotify-tui/issues/431
