### ISSUE TITLE
add a song to liked playlist | like / love / ❤️ a song

### ISSUE THREAD

**Issue by CochinoChingon** [Rigellute/spotify-tui#440]
## forgive me if my search-Fu has failed me

the only thing I can think of that is missing, IMO, is the ability to like a song from the `spt` or am I misreading/missing something in the `?` help menu?

**Comment by Rigellute** [comment]
You can like a song by pressing `s` when hovered over that song. You can also select the playbar and press `s` to like the currently played song.

**Comment by emmanuelanaya** [comment]
What could be a reason for this not working? 
Currently in 0.19.0 and pressing ```s``` doesn't seem to have any effect either hovering or in playbar.

**Comment by mredaelli** [comment]
It does work for me! However, why is the help text "save track in list or table"? If it just "likes", it might be better to say it like that in the help.

Otherwise clarify the actual action (what list/table?).
