### ISSUE TITLE
Can't scroll through all playlist items

### ISSUE THREAD

**Issue by teleportex** [Rigellute/spotify-tui#441]
I have been looking through implemented and not implemented things and i'm not sure if this is a bug that ocurrs to me or it's the current implementation or i can't find the correct key, sorry if its the case :(

I have a playlist with about 500 songs. Spotify tui shows me just the last added songs of the playlist and when i scroll down (using the down arrow, the ctrl-n or j key bindings) it goes down until the bottom of the terminal, when it reaches the bottom it returns back to the top.

Even when I'm in shuffle mode, the only songs played are the songs shown in the screen.

I haven't find a way to scroll through all the songs of the playlist, and even to play them. I hope this is helpfull and not anoying.

Thanks!

**Comment by Rigellute** [comment]
Sorry for the confusion! Pagination is not fully implemented in all views, but the keys to navigate between result pages is `Ctrl+d` (down) and `Ctrl+u` (up)

**Comment by teleportex** [comment]
Thanks now I'm able to scrollt through the playlist :D
In a future update It will be included support for playing random the whole playlist?

Thanks!!!

**Comment by Rigellute** [comment]
Shuffling tracks within "made for you", playlist search, and any playlist should work as expected.

The only place where shuffle _doesn't_ work as expected is within the "liked songs" or "recently played" playlists - Spotify don't give us a playback context, which is needed so they can shuffle playback on their end.

**Comment by EsmailELBoBDev2** [comment]
@Rigellute (Sorry for the tab but its closed ticket so seeing it chance will be low) i can't use ctrl + d or ctrl + u, all i can use j/k and arrow buttons and i can't see all of my playlists, just around first 11 playlists only!
I'm a debian 10 user

**Comment by jradek** [comment]
Hi,
Same error here (on MacOS).
I also created a comment below another issue, which should have fixed this bug https://github.com/Rigellute/spotify-tui/pull/531#issuecomment-693323519

JR
