### ISSUE TITLE
[FEATURE REQUEST] Add save album on album view

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [Rigellute/spotify-tui#444]
Currently, album save (current_user_saved_album_add) works from a [album search](https://github.com/GrudgeDuck/spotify-tui/blob/4f0c516791be95a85fb29bcf8325eee9672cc86e/src/handlers/search_results.rs#L432) but I frequently want to save the album of the current song playing after opening the "album" view with "a".

The workaround I am currently using is just searching for the album and it works fine, so this is more of a extra feature.

PS: Thank you for the great project :)

**Comment by Rigellute** [comment]
Good idea, and thank you 👍

**Comment by RicardoHE97** [comment]
Hi! I just discovered this project and I think is really cool! I would like to contribute to it, and this seems like a good issue to start. Can I work on it?
