### ISSUE TITLE
show_loading_indicator: false doesn't do anything

### ISSUE THREAD

**Issue by hihiyes** [Rigellute/spotify-tui#458]
Putting `behavior:
  show_loading_indicator: false` into config.yml doesn't seem to have an effect, the loading indicator still shows. Changing shorcuts works, so the config.yml file is definitely loading.

**Comment by Rigellute** [comment]
Which verison of spotify-tui are you on? 

Disabling the loading indicator is not yet released, which might explain why you're not seeing it.

Or are you compiling spotify-tui yourself?

**Comment by hihiyes** [comment]
Oh that explains it, I'm on 0.18. Thanks!
