### ISSUE TITLE
Scrolling after config?

### ISSUE THREAD

**Issue by lilgreggy** [Rigellute/spotify-tui#459]
Hello! 

I am yet another person struggling to get scrolling to work. I'm not sure if ctrl-d/u was ever working on my initial install (AUR spt-full) as I immediately uploaded the sample config.yml and started hacking at it. I notice that the sample config listed doesn't include the pagination in its keybindings. Am I supposed to add that in? My assumption was that was a default setting located elsewhere. To clarify, the scrolling is looping in all the sections (I understand that there is not yet support for certain sections, e.g. Playlists). 

Edit: I'm not sure if this is typical behavior, but also my "Help" section keeps randomly flashing as active with my "Hint" color and with the notification of "Loading..."

**Comment by lilgreggy** [comment]
Well, it started working. Unsure what I did or perhaps I just wasn't waiting long enough after the ctrl + d as it does lag a bit, but I don't think that's it as I was fiddling with it quite a bit and could never get it to work. Will close this though. Love it so far with spotifyd.

**Comment by Rigellute** [comment]
Glad you got this working. Worth noting that pagination (crtl-d/u) is not implemented in every view yet.
