### ISSUE TITLE
[FEATURE REQUEST] Like song from playbar only/basic view

### ISSUE THREAD

**Issue by tomyrobichaud** [Rigellute/spotify-tui#478]
I often find my myself leaving it in playbar only screen / basic view while listening to new playlists/discover weekly, it would be nice to not have to back out of it and just tap s to like the currently playing song.

**Comment by Rigellute** [comment]
You're right, that would be good 👍

**Comment by tysaya123** [comment]
I was able to add the request in by taking a little code from playbar.rs. Should I fork and create a pull request?

**Comment by RicardoHE97** [comment]
I think you should submit a PR if you think you successfully added the feature. I was able to solve the issue as well, if you want I can submit the PR.
