### ISSUE TITLE
Playback via librespot?

### ISSUE THREAD

**Issue by burnoutberni** [Rigellute/spotify-tui#48]
Just gonna leave this here as a suggestion, there exists an on-going effort at an open source Spotify client in Rust over at [librespot](https://github.com/librespot-org/librespot) and there might be some way to collaborate (I'm only a user of librespot though, so don't expect anything from my side).

**Comment by Rigellute** [comment]
Interesting point - I'd love to collaborate with `librespot` somehow. 

I use and recommend [spotifyd](https://github.com/Spotifyd/spotifyd) which is a stripped down librespot UNIX daemon.

**Comment by Rigellute** [comment]
Playback via librespot should work as expected (though I've not verified this myself). 

Will lookout for any opportunities for future collaboration.
