### ISSUE TITLE
Request: Custom keybinding for pagination (scroll up, down, start, end)

### ISSUE THREAD

**Issue by AndydeCleyre** [Rigellute/spotify-tui#482]
As far as I can tell, the list of actions which can be bound to keys by the user are found [here](https://github.com/Rigellute/spotify-tui/blob/master/src/user_config.rs#L227). I'd like to be able to bind my `pageup`, `pagedown`, `home`, and `end` keys to: 

- "Scroll up to previous result page"
- "Scroll down to next result page"
- "Jump to start of playlist"
- "Jump to end of playlist"

Thanks for all work on this project!

**Comment by vidurb** [comment]
I would like to second this request. The default keybinding for 'jump to start' is what I use as my prefix for `tmux` (and I believe the default prefix for GNU `screen`). Would be great to be able to redefine it to something that is not caught by `tmux`.
