### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by Firoda** [Rigellute/spotify-tui#486]
Every time I try to install the spt and then enter the client ID and secret, it shows the link which on clicking is an invalid URI. Also, I did change the settings in the Spotify Dashboard but it still returns an invalid URI

I have tried changing the port number too.
My System -> Ubuntu 16.04LTS

**Comment by dimlucas** [comment]
Same here with Powershell 5 on Windows 10.
Tried setting "http://localhost:8888" on the Spotify Redirect URL whitelist but didn't work

**Comment by dimlucas** [comment]
This worked for me on Powershell 5

Spotify App Dashboard > Edit Settings > Redirect URIs
and add `http://localhost:8888/callback`

Don't forget to scroll down and click save.

8888 is the default port selected by spotify-tui.

Also if you enter the URL without the `/callback` part, it won't work

**Comment by Rigellute** [comment]
@Firoda does @dimlucas response help you?

Sounds like that should fix it?

**Comment by Jarel1337** [comment]
Fixed it for me :+1:

**Comment by ZurMaD** [comment]
So, we need to specify that in README.md
It's solved by adding URI on spotify side not in TUI

**Comment by macpijan** [comment]
To me the instructions in README are correct (https://github.com/Rigellute/spotify-tui#connecting-to-spotifys-api) and this could be closed probably.

**Comment by Rigellute** [comment]
Indeed, this is already in the README. If anyone thinks the existing instructions can be improved, please raise a PR!

**Comment by markstos** [comment]
I ran into this but was confused by Spotify's UI. I had clicked "Save", but it wasn't saving. Eventually I realized I needed to use the "Add" button next to the field.
