### ISSUE TITLE
[FEATURE REQUEST] Flags for skip, pause/play

### ISSUE THREAD

**Issue by tomkdale** [Rigellute/spotify-tui#496]
I would love it if I could do a couple of very simple commands without opening up the full tui. Play/pause, skip, prev songs using flags. Being apply to run a `spt -n` to just skip a song and keep working would be great.

**Comment by Utagai** [comment]
Look into things like `playerctl` if you're on Linux, which does what you want generically for various music players. The Spotify desktop client, `spotifyd`, etc, all listen to it.

If you're on OSX, you'll probably have to use some combination of `osascript` and the `AppleScript` dictionaries for your apps? That said, I imagine you may already have media keys to do this quicker.

Windows, no idea.

**Comment by deadlysyn** [comment]
I've used playerctl with the electron client, but the same key binds (playerctl {next,previous,etc}) don't seem to work out of the box for me on arch, spotifyd, spotify-tui. I'm sure it's a config tweak I'm missing. Will post back if tracked down.

**Comment by Utagai** [comment]
I don't have experience with `bspwm` so I can't really help you with what your system seems to be having issues with. You're most likely correct that it's a problem with your system (I have three Linux machines that have worked fine with this, Arch + i3, Debian + i3, and Ubuntu + i3).

You may be interested in opening up a tty or whatever it is called and looking at `~/.xsession-errors` for any noise when X freezes. I would imagine it may have something useful.

**Comment by Rigellute** [comment]
You can do this now using the new cli commands!

```
spt pb -n
```
