### ISSUE TITLE
Can't play tracks through Spotify TUI

### ISSUE THREAD

**Issue by ritiek** [Rigellute/spotify-tui#5]
Hi, thanks for working on this! Pretty interesting project.

I installed this with cargo (5eaecb095effa44a02ced67f520cfe197c098fde) but for some reason it won't detect that my Spotify Desktop is open and I always end up with this error whenever I try to play a track through TUI:
```
Api response: Spotify API reported an error
If you are trying to play a track, make sure the official spotify app is open
Press <Esc> to return
```

However, the TUI displays the current track playing and its position correctly.

Might it be that Spotify API requires a Spotify Premium account for this feature to work?

**Comment by Rigellute** [comment]
Have now updated the README and the error message itself. Sorry about that!

**Comment by ashwinchandran13** [comment]
Should have written with a headline *"Works only Spotify Premium Account"* in README. I knew about this premium thing when I'd reach the __limitations__ section in README.md.
Just a suggestion @Rigellute,  as most of the students are broke XD
BTW Awesome work mate
