### ISSUE TITLE
Repeat changes itself to "All" no matter how many times I choose "Track"

### ISSUE THREAD

**Issue by MonstrousOgre** [Rigellute/spotify-tui#504]
So literally 5 seconds after I select "Track" as the repeat option, it switches back to "All" without any input from me. I can't seem to set it to Track

**Comment by MonstrousOgre** [comment]
Turns out the problem is with Spotify

**Comment by Muirrum** [comment]
What solved this for you? I'm having this issue myself

**Comment by MonstrousOgre** [comment]
@Muirrum it's not solved. I'm just not using Spotifyd anymore

**Comment by fsevenm** [comment]
Me too
