### ISSUE TITLE
Basic view sacrifices content before margin in small terminals

### ISSUE THREAD

**Issue by fezboy** [Rigellute/spotify-tui#508]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/31973884/85483962-b4ab8a80-b57a-11ea-819b-b9e3ad9e8e8c.gif)

In a terminal with a small text size to terminal size ratio, the content of the basic view window is removed before the vertical margin/padding

**Comment by Rigellute** [comment]
Thanks for this issue - your gif really helps show the problem!

**Comment by Rigellute** [comment]
Closed by #664
