### ISSUE TITLE
This error even though I'm using the official Spotify application on Linux.

### ISSUE THREAD

**Issue by nickcorona** [Rigellute/spotify-tui#53]
This error even though I'm using the official Spotify application on Linux.
![Screenshot from 2019-10-12 17-05-15](https://user-images.githubusercontent.com/7490453/66707677-47203c80-ed12-11e9-9144-59a59de7a0b3.png)

**Comment by Rigellute** [comment]
A few things to check,
1. You have a Spotify Premium account
1. You have chosen a device to play tracks on - press `d` to go to the device selection menu, find and select your spotify client

**Comment by nickcorona** [comment]
I do have a spotify premium account. The device I use is `desktop`.
