### ISSUE TITLE
Feature Request: Add current selection to playqueue

### ISSUE THREAD

**Issue by isaacdchan** [Rigellute/spotify-tui#532]
I didn't see it in the help menu. Sorry I'd contribute but I don't know Rust. 

Looks like it's possible with API:
https://developer.spotify.com/documentation/web-api/reference/player/add-to-queue/

Thanks for such a cool project!

**Comment by Rigellute** [comment]
Thank you for using spotify-tui!

And we have an issue here to track this feature https://github.com/Rigellute/spotify-tui/issues/532 (closing this to avoid duplication)
