### ISSUE TITLE
How do you use this app in conjunction with spotifyd?

### ISSUE THREAD

**Issue by nickcorona** [Rigellute/spotify-tui#54]
There's no documentation on getting that setup.

**Comment by Rigellute** [comment]
Follow the spotifyd documentation to get set up.

After that there is not much to it.

1. Start running spotifyd daemon.
1. Start up `spotify-tui` 
1. Press `d` to go to the device selection menu and the spotifyd "device" should be there - if not check [these docs](https://github.com/Spotifyd/spotifyd#logging)

**Comment by Rigellute** [comment]
Have added these instructions to the README https://github.com/Rigellute/spotify-tui/commit/befb369d589636cecac3a4ee4cabe1d3dc4c9ac3
