### ISSUE TITLE
Add the ability to like the song !

### ISSUE THREAD

**Issue by Sacha-Ringenbach** [Rigellute/spotify-tui#553]
This spotify feature helps a lot with song recommendations, it's a shame it's not included in this program !

**Comment by x0rld** [comment]
the recommendation is a very complex algorithm it's not that easy to create it...

**Comment by Sacha-Ringenbach** [comment]
Understandable, my bad, have a nice day!

**Comment by jcro21** [comment]
@x0rld 
> the recommendation is a very complex algorithm it's not that easy to create it...

While that's likely true, I think @Sacha-Ringenbach was asking for the ability to 'like' a track, as seen in the official spotify client. Liking a track helps _educate_ spotify's recommendation algorithms, but doesn't actually require _implementing_ those algorithms.

Good news @Sacha-Ringenbach ! spotify-tui already has that feature! Pressing `s` with a track highlighted will 'like' that track :smiley: :+1: 

_Note: You can see a list of all the keyboard shortcuts by typing a `?` within spotify-tui. There are multiple pages, so use the up and down arrow keys to move between them_

**Comment by dann-merlin** [comment]
@jcro21 Actually what @Sacha-Ringenbach might be talking about, is a bug, I meant to issue a ticket for for a while.
You cannot use `s` on Songs in Playlists for example the "Discover Weekly" Playlists (I think that's maybe what Sacha meant). But it's also the case for all other Playlists. The workaround for me always was to press `a` to open the album view of the track and then save it there with `s`.

**Comment by jcro21** [comment]
@dann-merlin I just double checked by going to Library -> Made For You -> Discover Weekly and hitting `s` -- it saved the track as expected!

Strange it's not doing the same for you, are you using it with spotifyd? Anything in the logs?

**Comment by dann-merlin** [comment]
Strange, because it doesn't work on all my machine (they are setup quite similarly though). I use it with spotifyd. Do you mean the logs of spotifyd or spotify-tui? I run spotifyd as a systemd service. I can't see anything special in `systemctl status spotifyd.service`.

**Comment by dann-merlin** [comment]
Oh, well. I just tried the most obvious thing: updating the program. I use the spotify-tui-git package from the AUR, which doesn't get automatically updated. I wonder how old this feature is though, as I don't think it was too long ago I compiled it.
Anyways, works now.

**Comment by Rigellute** [comment]
Thanks everyone 👍

**Comment by Wael2727** [comment]
yeah uh, the keybind has changed to 'Toggle Shuffle' plus i can't seem to find the keybind for liking a song, only a artist/album.

**Comment by fsevenm** [comment]
> @dann-merlin I just double checked by going to Library -> Made For You -> Discover Weekly and hitting `s` -- it saved the track as expected!
> 
> Strange it's not doing the same for you, are you using it with spotifyd? Anything in the logs?

Oh, spotifyd doesn't support it yet?
