### ISSUE TITLE
Cannot type in the search bar

### ISSUE THREAD

**Issue by FeryET** [Rigellute/spotify-tui#554]
Hi.

I'm using Ubuntu 20.04 + KDE. My terminal is tilix but I've also tried using the program on gnome-terminal. The situation is no different. 

I cannot search through the seach bar, and when I hit "?" for the help menu, the keyboard column in the menu is jumping right and left. Overall the program is acting a little unstable.

**Comment by bartuortal** [comment]
Same issue with Arch KDE/i3wm

**Comment by 31j** [comment]
What keyboard layout are you using? Just curious if perhaps you need to use a modifier key to access the /. I personally haven't had issues with the two layouts I have enabled, ``ca(multix)`` as well as ``us``. 

If you're expecting it to be terminal related you could try qterminal, I have had it work perfectly fine with qterminal on Fedora 32 lxqt and that shouldn't make either of you install many unnecessary packages.

**Comment by bartuortal** [comment]
> What keyboard layout are you using? Just curious if perhaps you need to use a modifier key to access the /. I personally haven't had issues with the two layouts I have enabled, `ca(multix)` as well as `us`.
> 
> If you're expecting it to be terminal related you could try qterminal, I have had it work perfectly fine with qterminal on Fedora 32 lxqt and that shouldn't make either of you install many unnecessary packages.

Using us keyboard. Tried qterminal and it also does not work. However, '/' key works so it is fine.

**Comment by sputnick1124** [comment]
> ...when I hit "?" for the help menu, the keyboard column in the menu is jumping right and left.

I think this part of this issue is the same as previously reported in https://github.com/Rigellute/spotify-tui/issues/533. The search bar issue seems unique, though.

**Comment by Rigellute** [comment]
The flickering issue in the help menu is now fixed.
`/` is the command to start typing in the search bar.
Please reopen if `/` is not working
