### ISSUE TITLE
Spotify-tui does not initially recognise spotifyd

### ISSUE THREAD

**Issue by snst-p** [Rigellute/spotify-tui#560]
When i run spotifyd, spotify-tui does not list it as a device. However spotifyd is running correctly, because on my phone it is listed as a device.

When i play a song from my phone on the spotify-d device, then suddenly it appears in the device list on spotify-tui. But before that it doesn't

**Comment by Peterkmoss** [comment]
What version of spotifyd and spotify-tui are you running?

**Comment by snst-p** [comment]
spotify-tui 0.21.0 
spotifyd 0.2.24

**Comment by snst-p** [comment]
also i saw a typo in my original post i corrected it

**Comment by piotrcalus** [comment]
> When i run spotifyd, spotify-tui does not list it as a device. However spotifyd is running correctly, because on my phone it is listed as a device.

Run the spotifyd without detaching (_--no-daemon_) and check that configuration file is loaded correctly and the daemon is connected and authenticated. You can add _--device-name_ for easier identification - _temporary_device_name_ shoud be visible in spotify-tui devices list.
```
$ spotifyd --no-daemon --device-name temporary_device_name
Loading config from "/home/user/path/to/spotifyd.cfg"
[...]
Connecting to AP "gew1-accesspoint-b-v4hx.ap.spotify.com:443"
Authenticated as "_spotify_user_name_" !
```
If you do not get info about configuration file loading add the `--config-path` to the run command and try again.
```
$ spotifyd --no-daemon --config-path ~/.config/spotifyd/spotifyd.cfg
```

If config file is loaded but daemon is not connected/authenticated verify your config file:
- cache_path (with _full path_, do not use **~**)  e.g. `cache_path = /home/user/.cache/spotifyd`
   and/or
- username and password

The _<cache_path>/credentials.json_ file is created after (first) correct authorization.

Let us know what works / doesn't work. Good luck.

**Comment by Rigellute** [comment]
Any luck @snst-p?

**Comment by Yazir** [comment]
Had the same issue, config wasn't loading.

What I needed to do is to change filename of ~/.config/spotifyd/spotifyd to spotifyd.conf (default cfg path)
