### ISSUE TITLE
How to disable italic

### ISSUE THREAD

**Issue by danielfalbo** [Rigellute/spotify-tui#568]
It would be great to have an option to disable italic. See what it looks like in my terminal (I haven't yet found an easy and dotfiles-automated way to add italic support to my $TERM without losing truecolors in nvim+tmux)

![output](https://user-images.githubusercontent.com/39460524/92003265-1ccbd900-ed41-11ea-92ca-7576f51428e4.gif)

**Comment by Rigellute** [comment]
Ah interesting problem! We can make italics configurable, so you can disable them.

**Comment by Rigellute** [comment]
Closed by #573
