### ISSUE TITLE
Spotify auth failed

### ISSUE THREAD

**Issue by swarfega** [Rigellute/spotify-tui#569]
I have installed spotify-tui by AUR and followed the instructions but the link provided gives an INVALID_CLIENT: Invalid redirect URI error.

(I also have a login problem with ncspot).

**Comment by fnuttens** [comment]
I have the same problem on Windows.

**Comment by miku86** [comment]
> I have installed spotify-tui by AUR and followed the instructions but the link provided gives an INVALID_CLIENT: Invalid redirect URI error.
> 
> (I also have a login problem with ncspot).

I had the same problem.

I had to copy the `client_id` and `client_secret` into `${HOME}/.config/spotify-tui/client.yml` manually.

**Comment by oising** [comment]
did you add the redirect url in your spotifiy develop app settings? You have to explicitly add http://localhost:8888/callback as a redirect uri on spotify dev dashboard or it won't work (as well as providing the clientid + secret to the tui app)

**Comment by Rigellute** [comment]
Thanks for the tips @oising @miku86. Any luck @swarfega? It does sound like the callback wasn't registered in the spotify dev console

**Comment by swarfega** [comment]
This time around I just installed the AUR and it worked fine.

**Comment by Rigellute** [comment]
Great, thanks

**Comment by acewave** [comment]
> > I have installed spotify-tui by AUR and followed the instructions but the link provided gives an INVALID_CLIENT: Invalid redirect URI error.
> > (I also have a login problem with ncspot).
> 
> I had the same problem.
> 
> I had to copy the `client_id` and `client_secret` into `${HOME}/.config/spotify-tui/client.yml` manually.

This worked for me too.
