### ISSUE TITLE
Add volume controls

### ISSUE THREAD

**Issue by Rigellute** [Rigellute/spotify-tui#57]
Could use `D` for down and `U` for up to control volume?

**Comment by jfaltis** [comment]
The + and - keys could also be used.

**Comment by jfaltis** [comment]
Or maybe v and V for volume?

**Comment by Rigellute** [comment]
I like your suggestion to use `+` and `-`.

PR here implementing volume control https://github.com/Rigellute/spotify-tui/pull/59
