### ISSUE TITLE
Error produced when using search feature

### ISSUE THREAD

**Issue by scoogii** [Rigellute/spotify-tui#570]
Hey! I was trying out spotify-tui and when I tried to search for a song this error was displayed on my screen:

![Screen Shot 2020-09-07 at 11 09 35 pm](https://user-images.githubusercontent.com/60502807/92390960-344efb80-f15f-11ea-8bc4-a8533e8808aa.png)

In this case, I searched "a song". I can reproduce the same error whenever I search for anything really - it seems like the search feature isn't working for me. I'm pretty sure I followed the setup steps correctly for MacOS and my `client.yml` and `config.yml` files look fine, so I'm not sure what's going on here. Some pointers on what could be the problem would be great and I'll gladly provide further information if needed.

Cheers :)

**Comment by ifpleti** [comment]
Same error in the snap package

**Comment by lucacorbucci** [comment]
Same here, I've just installed spotify-tui and I have this problem when I search for a song or an artist

**Comment by stevensonmt** [comment]
+1. I can play my playlists and anything from the Library widget except for Made For You which produces the same error as searching.

**Comment by ifpleti** [comment]
It may be that Spotify made some sort of change in the content of the JSON retrieved by the "API" or scraping result (not sure how spotify-tui works with the service) ¿?

**Comment by scoogii** [comment]
Just hopped on today to check and it currently seems that the search feature is working once again - could anyone also double-check for me before I close this issue? Thanks

**Comment by Rigellute** [comment]
Looks like search is working for me - perhaps spotify made some changes on their end that broke it for a while. But looks good now.

**Comment by scoogii** [comment]
Awesome, I'll close it then :D
