### ISSUE TITLE
Help page behaviour with moving event column

### ISSUE THREAD

**Issue by meerasndr** [Rigellute/spotify-tui#577]
Is there a way to disable the moving Event column? (apart from maximising the terminal window)
![weird help page behaviour](https://user-images.githubusercontent.com/38532591/93019034-14ea1f80-f5f2-11ea-99d4-5cfe1391aa5f.gif)

**Comment by sputnick1124** [comment]
Looks like this is a duplicate of https://github.com/Rigellute/spotify-tui/issues/533?

**Comment by meerasndr** [comment]
You're right @sputnick1124. I did not notice #533 . Closing this now.

**Comment by sputnick1124** [comment]
The GIF really helps illustrate the problem clearly! Thanks for posting it!
