### ISSUE TITLE
Pressing Enter before a screen has loaded crashes the application

### ISSUE THREAD

**Issue by ericonr** [Rigellute/spotify-tui#590]
If I press Enter three times consecutively, the final key press, which happens before the `Made For You` screen has loaded, crashes `spotify-tui`.

Can be seen here: https://asciinema.org/a/bKrlOAK9VmXWvZrrsmE492mGE

**Comment by sputnick1124** [comment]
Looks like it's coming from [this unwrap](https://github.com/Rigellute/spotify-tui/blob/0e8f3723ad3b91725d04b460ae6b511ac6ffac1c/src/handlers/made_for_you.rs#L49).

**Comment by Rigellute** [comment]
Good bug report thank you.

And good stuff debugging the error @sputnick1124
