### ISSUE TITLE
Split 'local' actions from 'online' actions

### ISSUE THREAD

**Issue by Toaster192** [Rigellute/spotify-tui#593]
What I mean is, I can't even pause the song when my internet gives up on me for a few seconds.

Does the app really have to send a request just to pause the song locally or is it because while any other request is being 'processed' (waits for the network request to come through) any other commands get put in queue (including 'local' ones like pausing the song)

**Comment by sputnick1124** [comment]
Yes, a request really does have to go out in order for a pause to happen. `spt` doesn't handle playback, it is just a front-end interface to spotify's web api. 

Since the advent of async, there shouldn't be any blocking of local actions due to network delays since all network calls are now run in a non blocking context.

**Comment by Rigellute** [comment]
As @sputnick1124 rightly says, there aren't really any 'local' actions in spotify-tui since everything must go through the spotify API (spotify-tui doesn't handle playback). So a network connection is required.

**Comment by kubukoz** [comment]
One thing spotify-tui could be doing is make decisions on what the space button means based on the remote state - currently it seems to be basing that entirely on the local playback stat. Here's what I mean:

1. <music is playing>
2. tap space, tui knows it's playing so it sends a PAUSE request
3. remote stops playing, hasn't responded yet so tui think it's playing
4. tap space
5. tui thinks it's playing so it sends a PAUSE request

In the ideal scenario, tui would check for the status every time before making a pause/play request, and use that to make the decision.
