### ISSUE TITLE
Songs played don't show up in "Recently Played"

### ISSUE THREAD

**Issue by Jake-Gillberg** [Rigellute/spotify-tui#602]
Not sure if this is a spotify-tui issue or spotifyd issue

**Comment by Jake-Gillberg** [comment]
https://github.com/Spotifyd/spotifyd/issues/687

**Comment by sputnick1124** [comment]
This actually stems from [`librespot`](https://github.com/librespot-org/librespot), the library on which spotifyd builds. This issue in particular has been long standing one which ultimately is an issue of trying to reverse engineer the appropriate comms from the player client back to the server to update it with current progress.

See https://github.com/librespot-org/librespot/issues/342

**Comment by Jake-Gillberg** [comment]
Thanks!
