### ISSUE TITLE
Artists pagination is not implemented

### ISSUE THREAD

**Issue by Utagai** [Rigellute/spotify-tui#603]
First off, great work on this. I was having some memory usage issues on my old laptop and this project shaved off an entire gigabyte of memory usage that the official Spotify desktop client was hogging!

# Steps to reproduce
* Go to the `Artists` page from the `Library` section.
* Try to use `<ctrl+d>`/`<ctrl+u>` to paginate the `Artists` page.
* Note that nothing happens.

Looking at the code this seems to be because we have no handlers for the next and previous page actions. I'll have a PR up for this soon, but I thought that I should probably file the issue first.

**Comment by Rigellute** [comment]
Great to hear that you managed to save some memory usage by using spotify-tui!

And pagination is one major problem at the moment. We don't yet have a nice abstraction for every view. @sputnick1124 has an interesting proposal for this https://github.com/Rigellute/spotify-tui/issues/527
