### ISSUE TITLE
Make the liked icon configurable

### ISSUE THREAD

**Issue by Utagai** [Rigellute/spotify-tui#625]
Currently, the icon `spt` uses to mark liked items, such as a liked song, is the heart character: ♥.

For any variety of reasons, the user may want to change their preferred icon. e.g.:
1. Their font family does not support the glyph.
2. Their terminal does not render it properly.
3. Preference

For me, #1 applies, so I unfortunately have an empty space whenever I see a liked song. I was thinking that we could make the default value stay as the ♥, but allow users to configure a replacement string if they wish.

**Comment by Utagai** [comment]
@Rigellute Let me know if this is something you'd be OK with in `spotify-tui`. I would be more than willing to work on this as it affects me currently.

If not, that's cool too. I can work off of my fork.

**Comment by Rigellute** [comment]
Yep, happy for this to be added to the config 👍

**Comment by Utagai** [comment]
Great to hear. I'll take a crack at this soon.
