### ISSUE TITLE
Select song plays song from another playlist

### ISSUE THREAD

**Issue by diegoulloao** [Rigellute/spotify-tui#628]
When another playlist is highlighted in the Playlist menu but not selected in the song list, it plays a random song from the other playlist and not the song selected to play

**Comment by Ebsz** [comment]
Yeah, i have what i assume is the same issue. Though (at least in my case) it's not random, but rather it plays the song that is at the same index as the selected song, in the highlighted playlist.

**Comment by Utagai** [comment]
I was able to reproduce this. I also think I see what's wrong. I might have a PR up for this soon.

**Comment by diegoulloao** [comment]
> Yeah, i have what i assume is the same issue. Though (at least in my case) it's not random, but rather it plays the song that is at the same index as the selected song, in the highlighted playlist.

yes, I amend: is not random, is the song with the same index

**Comment by diegoulloao** [comment]
Why is this closed? Problem was resolved?

**Comment by Rigellute** [comment]
@diegoulloao this is fixed in #632
