### ISSUE TITLE
Help shortcut info (Top right) shows "loading ..." sometimes

### ISSUE THREAD

**Issue by Bios-Marcel** [Rigellute/spotify-tui#636]
This randomly happens from time to time. I doubt that there's anything for that component that needs to be asychronously loaded 🤔 

![grafik](https://user-images.githubusercontent.com/19377618/97191127-d9bd3d80-17a6-11eb-8cd6-f83de34f9a8f.png)

**Comment by FreddieRa** [comment]
This happens when it is communicating with the Spotify API.

**Comment by Bios-Marcel** [comment]
If this is like a global loading indicator, it's quite a weird place imo. If it's a feature exactly intended like this, feel free to close this.

**Comment by sputnick1124** [comment]
That is exactly what this loading indicator is. It indicates anytime there is a network event happening in the background. Nothing broken here.
