### ISSUE TITLE
Pressing 'd' doesn't open a device selection menu

### ISSUE THREAD

**Issue by Tragyn** [Rigellute/spotify-tui#639]
When I open spt and try to play a song, I get an error:

![10 28 20-11:26:23](https://user-images.githubusercontent.com/5403547/97474744-0b064c80-1912-11eb-9ee4-c5877bdca93e.png)

When I press 'd', nothing happens.

I've tried multiple keyboards and terminals with no success.

`wu% spt --version
spotify-tui 0.4.0`

`wu% uname -a
Linux wu 5.9.1-arch1-1 #1 SMP PREEMPT Sat, 17 Oct 2020 13:30:37 +0000 x86_64 GNU/Linux`

**Comment by sputnick1124** [comment]
Wow that version is ancient! What method did you use to install?

**Comment by Tragyn** [comment]
> Wow that version is ancient! What method did you use to install?

I installed spotify-tui-git from the AUR.

**Comment by Tragyn** [comment]
I reinstalled it and now I'm on 0.22.0.  I have no idea what happened there, but it works now, thanks!

**Comment by sputnick1124** [comment]
Yeah that's weird that it was so out of date somehow. Great to hear that it's working now, though!
