### ISSUE TITLE
Cant return from Podcasts

### ISSUE THREAD

**Issue by mathiasrw** [Rigellute/spotify-tui#657]
When I navigate to Podcasts I cant "exit" the selected panel to move to Library or Playlists. Its like the escape button is not doing anyting. 

![image](https://user-images.githubusercontent.com/1063454/98885231-f2f60780-2491-11eb-946d-9a50acdfd2c8.png)

**Comment by Rigellute** [comment]
Closing as podcasts are implemented now, from which can also return
