### ISSUE TITLE
thread '<unnamed>' panicked at 'called `Result::unwrap()`

### ISSUE THREAD

**Issue by tamert** [Rigellute/spotify-tui#66]
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by haitech** [comment]
Getting similar error.
Seems like the http-server is not running?

On osx 10.14.4, installed with brew
```
 ~  spt
Opened https://accounts.spotify.com/authorize?scope=playlist-read-private%20user-library-modify%20user-library-read%20user-modify-playback-state%20user-read-currently-playing%20user-read-playback-state%20user-read-private%20user-read-recently-played&client_id=XYZ&response_type=code&state=XYZ&redirect_uri=http:%2F%2Flocalhost:8888%2Fcallback& in your browser
Enter the URL you were redirected to:
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:999:5
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::continue_panic_fmt
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: spt::redirect_uri::redirect_uri_web_server
   8: __rust_maybe_catch_panic
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  11: std::sys::unix::thread::Thread::new::thread_start
  12: _pthread_body
  13: _pthread_start

Spotify auth failed
```

**Comment by haitech** [comment]
Got it to work with running `sudo spt`. And then after `spt` (without sudo) worked.

**Comment by tamert** [comment]
i am waiting  for a very long time but not response
--

**Comment by tamert** [comment]
![Screen Shot 2019-10-15 at 12 35 22](https://user-images.githubusercontent.com/1997933/66820022-964fb280-ef48-11e9-8baa-1796b00ad522.png)

**Comment by tigrato** [comment]
@tamert copy the url and paste into the terminal

**Comment by Rigellute** [comment]
Sorry about this. Something must be going wrong with the local webserver on first set up.

Will investigate.

**Comment by tamert** [comment]
> @tamert copy the url and paste into the terminal

:) yes i see now .. i  was couldnt see because i  just focus error

**Comment by Rigellute** [comment]
Did you install via `brew` and running on macOS? 

Or are you on linux and installed via `cargo`?

**Comment by abusch** [comment]
Seeing this as well on Linux (Arch), `spt` installed via `cargo`. It opens up a web browser, then panics with the error above.

**Comment by Rigellute** [comment]
I know the issue, will create fix shortly.

**Comment by Rigellute** [comment]
Apologies once again, the fix is here https://github.com/Rigellute/spotify-tui/commit/ca79472fa253025152c76c0b53dce9437fc18fd2 and is release to brew and cargo, you can now update.

**Comment by Rigellute** [comment]
Looks like this is only fixed for macOS, reopening.

**Comment by Rigellute** [comment]
Latest release `0.6.2` now finally contains the fix 👍
