### ISSUE TITLE
Repeat: Track setting seems to be arbitraily reverted 

### ISSUE THREAD

**Issue by sriniv27** [Rigellute/spotify-tui#661]
I like to have a particular white noise track playing and being able to loop just one track is important to me. I'm noticing that the Repeat setting is simply discarded

**Comment by sriniv27** [comment]
I'm cycling the repeat settings using Ctrl+R. It looks like the repeat setting falls back to Repeat: All after just a few seconds

**Comment by suruaku** [comment]
I have same problem while playing brown noice. spotify-tui 0.22.0

**Comment by gebba** [comment]
Seeing the same issue, repeating a single track seems to not work at all atm.

**Comment by sputnick1124** [comment]
This is a [`librespot`](https://github.com/Spotifyd/spotifyd/issues/514) problem, it seems (assuming you're using `spotifyd`). You could verify this by temporarily using the web gui to control your `spotifyd` player and try to cycle through repeat options. It will only toggle between "Repeat All" and "Off".

**Comment by suruaku** [comment]
> it seems (assuming you're using `spotifyd`). 

Yes, totally forgot about spotifyd... The issue is gone when used with web player.

**Comment by Rigellute** [comment]
Thanks for updating
