### ISSUE TITLE
Question about device_id

### ISSUE THREAD

**Issue by fourstepper** [Rigellute/spotify-tui#665]
Hi,

What is the purpose of device_id, e.g. in which context is it used? Is it only a unique random ID, or does it have any meaning?

Thanks!

**Comment by Rigellute** [comment]
The `device_id` is the identifier of the device you wish to control with `spotify-tui`. 

`spotify-tui` does not handle the playback directly, instead it uses the Spotify API to control a plaback device (you might be running the official client or `spotifyd`). This is the device identified by `device_id`.
