### ISSUE TITLE
Cannot install: `Error: Address already in use (os error 48)`

### ISSUE THREAD

**Issue by CaspianA1** [Rigellute/spotify-tui#669]
I get this error when trying to configure it via `spt`:

```
$ spt
Error: Address already in use (os error 48)
Starting webserver failed. Continuing with manual authentication
```

From there it tries to open a very large Spotify link: `Opened https://accounts.spotify.com/authorize` ...

This page hangs and does nothing. For each time I uninstall `spotify-tui` this link works once (by asking me to confirm a lot of permissions regarding what `spt` can do). After I click `accept` then that page hangs as well.

This is so frustrating - Does anyone know what I am doing wrong?

**Comment by Seltonu** [comment]
The exact same thing happens to me, except the error says "os error 98" instead of 48. But huge link, page hang, all of it

**Comment by OrangeFran** [comment]
You can try to change your port, I don't know if it helps though. Normally these `address already in use` messages appear, if a process is already using the port, in this case `8888`. To investigate, maybe have a loot at `netstat -l` to see all listening processes or even `lsof -i :8888` to look at the port and see which processes are using it. I hope this helps. These commands definetely work on macOS and probably on linux too.

**Comment by CaspianA1** [comment]
I'll try that out.

**Comment by CaspianA1** [comment]
Thank you, changing the port resolved my problem.

**Comment by Seltonu** [comment]
Just commenting to also add it works for me too now, I was going to test a different port as you mentioned but before doing that I tried "lsof -i :8888" and saw nothing was using the port so I went with the default 8888 and it worked. Must've been as you say, some program was using the port and restarting my PC must've cleared it at some point. Thank you!
