### ISSUE TITLE
No devices found

### ISSUE THREAD

**Issue by EldarionDev** [Rigellute/spotify-tui#674]
I tried to run spotifyd system-wide and on user-level, added and edited the config file as specified on their webpage but spotify-tui refuses to acknowledge the device. Maybe I am just having a little issue and it is not even the fault of spotfy-tui but I can not figure out what it could be. I am using systemd(sadly) as my init system.

**Comment by EldarionDev** [comment]
Sorry, this was a copy of issue 530.

**Comment by MurrayGroves** [comment]
Link issue: #530
