### ISSUE TITLE
Default volume

### ISSUE THREAD

**Issue by Pomegranate123** [Rigellute/spotify-tui#689]
Every time I restart my computer, the volume is at 100%, which is way too loud. I don't want to lower the volume every time I restart (because it's quite slow),  and I also don't want to lower my master volume just for this app. Is there a way to specify a default volume it loads on startup?

**Comment by OrangeFran** [comment]
I'm not aware of that feature. But it should be easy to implement.
I see two options: **saving** the last used volume or letting the **user specify** the volume in the config file.
What do you prefer?

**Comment by Pomegranate123** [comment]
I'd say remember the last used volume, that would save the hassle if going to the config file whenever you want to change it.

**Comment by OrangeFran** [comment]
Do you want to work on it or should I pick it up? It won't be hard.

**Comment by Pomegranate123** [comment]
I've never used rust and I'm unfamiliar with the codebase, so you go ahead and do it :)

**Comment by OrangeFran** [comment]
It seems that this setting is device specific. I don't think it makes sense to implement this in `spotify-tui`.
Hava a look at `spotifyd`, they have an `initial_volume` option that allows you to change the initial volume.

**Comment by Pomegranate123** [comment]
Thank you! I'll look into it.

**Comment by Rigellute** [comment]
Indeed, this sounds like an issue with the playback device itself. For example, the official spotify client "remembers" the correct volume setting after restarts.

@Pomegranate123 did setting `initial_volume` on for `spotifyd` work for you?
