### ISSUE TITLE
Connection Refused - Linux 

### ISSUE THREAD

**Issue by delirehberi** [Rigellute/spotify-tui#7]
You said it only works for mac, but I want to try in Linux, it seems working but returns an error at the below after facebook log in.

`Could not connect: Connection refused.`

**Comment by Rigellute** [comment]
Hmm... how did you install it on Linux? via `cargo install spotify-tui`?

This app does work on Linux (I've tested myself), however I've only published a binary for macOS so the homebrew installation will only work on macOS.

At which point do you get that error?

**Comment by QuinnFreedman** [comment]
I'm getting the same problem. I installed from cargo on Ubuntu 19.04

It seems to be at the very last step. I logged in to my Spotify dev console and got my id and secret and added the redirect url. Then I added the redirect URL. Then I ran `spt`. I entered my info and it opened a login page in my browser. I clicked "Log in with Facebook" and it redirected me to `http://localhost:8888/callback?code=...` but I can't connect to localhost. Chrome says:
```
```

**Comment by delirehberi** [comment]
I installed it with cargo. I runned the app in the same way as @QuinnFreedman. minibuffer.lisp opened Spotify login page, I clicked the facebook login. Returned "connection refused" after success login with facebook. OS: ubuntu 18.04.2 LTS

**Comment by alxdb** [comment]
I just had this same issue, although it isn't really an issue. You will be redirected to a page that doesn't exist (hence connection refused). Just copy paste the url you are redirected to into stdin (as spt instructs you do to after you close the page) and things should work. Perhaps the instructions should be made a little more clear though.

**Comment by Rigellute** [comment]
Exactly @alxdb. 
I will explore creating a localhost server for a small webpage to land you on after the redirect.
It definitely feels wrong landing on a page that says it's not loading.

**Comment by delirehberi** [comment]
thanks @alxdb it works c/p the redirected url. how I missed that :)
