### ISSUE TITLE
No theme option for the track length indicator in the progress bar

### ISSUE THREAD

**Issue by noir-Z** [Rigellute/spotify-tui#706]
Either I'm blind and just don't see it or there is no option to change the colour of the text/time in the progress bar.

**Comment by OrangeFran** [comment]
I think this is what you want:  #656.

**Comment by noir-Z** [comment]
Unfortunately i have to set it to 'Black' to be transparent which then forces(?) the default colour, I guess.
![Screenshot_20210115_170733](https://user-images.githubusercontent.com/45096516/104750635-a90cf480-5754-11eb-9a31-f013c0e279f0.png)

**Comment by noir-Z** [comment]
Okay so it's not mentioned in the readme.md but I looked at the source code and saw that there is actually a theme option for it.

`  playbar_progress_text: `

I think this should be added to the readme so i'll leave the issue open for now.
