### ISSUE TITLE
Linking error with Ubuntu 18.04

### ISSUE THREAD

**Issue by bmiller59** [Rigellute/spotify-tui#71]
Thanks for this great app! I am trying to build for Ubuntu 18.04 but getting this error. Thank you for any guidance.

`  
 Compiling spotify-tui v0.6.2
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/brendan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/tmp/cargo-install4Cfs9h/release/deps/spt-7ec6f893f06f5561.spt.9nqlk0j9-cgu.0.rcgu.o" "/tmp/cargo-install4Cfs9h/release/deps/spt-7ec6f893f06f5561.spt.9nqlk0j9-cgu.1.rcgu.o" "/tmp/cargo-install4Cfs9h/release/deps/spt-7ec6f893f06f5561.spt.9nqlk0j9-cgu.10.rcgu.o" "/tmp/cargo-install4Cfs9h/release/deps/spt-7ec6f893f06f5561.spt.9nqlk0j9-cgu.11.rcgu.o" "/tmp/cargo-install4Cfs9h/release/deps/spt-7ec6f893f06f5561.spt.9nqlk0j9-cgu.12.rcgu.o" "/tmp/cargo-install4Cfs9h/release/deps/spt-7ec6f893f06f5561.spt.9nqlk0j9-cgu.13.rcgu.o" "/tmp/cargo-install4Cfs9h/release/deps/spt-7ec6f893f06f5561.spt.9nqlk0j9-cgu.14.rcgu.o" "/tmp/cargo-install4Cfs9h/release/deps/spt-7ec6f893f06f5561.spt.9nqlk0j9-cgu.15.rcgu.o" "/tmp/cargo-install4Cfs9h/release/deps/spt-7ec6f893f06f5561.spt.9nqlk0j9-cgu.2.rcgu.o" "/tmp/cargo-install4Cfs9h/release/deps/spt-7ec6f893f06f5561.spt.9nqlk0j9-cgu.3.rcgu.o" "/tmp/cargo-install4Cfs9h/release/deps/spt-7ec6f893f06f5561.spt.9nqlk0j9-cgu.4.rcgu.o" "/tmp/cargo-install4Cfs9h/release/deps/spt-7ec6f893f06f5561.spt.9nqlk0j9-cgu.5.rcgu.o" "/tmp/cargo-install4Cfs9h/release/deps/spt-7ec6f893f06f5561.spt.9nqlk0j9-cgu.6.rcgu.o" "/tmp/cargo-install4Cfs9h/release/deps/spt-7ec6f893f06f5561.spt.9nqlk0j9-cgu.7.rcgu.o" "/tmp/cargo-install4Cfs9h/release/deps/spt-7ec6f893f06f5561.spt.9nqlk0j9-cgu.8.rcgu.o" "/tmp/cargo-install4Cfs9h/release/deps/spt-7ec6f893f06f5561.spt.9nqlk0j9-cgu.9.rcgu.o" "-o" "/tmp/cargo-install4Cfs9h/release/deps/spt-7ec6f893f06f5561" "/tmp/cargo-install4Cfs9h/release/deps/spt-7ec6f893f06f5561.47pxari3l4vn7782.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/tmp/cargo-install4Cfs9h/release/deps" "-L" "/tmp/cargo-install4Cfs9h/release/build/backtrace-sys-6335e9cbc5f67c4d/out" "-L" "/home/brendan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/cargo-install4Cfs9h/release/deps/libserde_yaml-8d44eac82564392d.rlib" "/tmp/cargo-install4Cfs9h/release/deps/libyaml_rust-d81429449dc24cbb.rlib" "/tmp/cargo-install4Cfs9h/release/deps/liblinked_hash_map-e4890eadedeb8224.rlib" "/tmp/cargo-install4Cfs9h/release/deps/libclap-ea086e5ba1a1d381.rlib" "/tmp/cargo-install4Cfs9h/release/deps/libvec_map-31dc9a693a4a81e3.rlib" "/tmp/cargo-install4Cfs9h/release/deps/libtextwrap-bdab6b89a06c723b.rlib" "/tmp/cargo-install4Cfs9h/release/deps/libstrsim-4dcff5113b2146ff.rlib" "/tmp/cargo-install4Cfs9h/release/deps/libansi_term-32b6666dc48e585a.rlib" "/tmp/cargo-install4Cfs9h/release/deps/libdirs-bab61cddd523db62.rlib" "/tmp/cargo-install4Cfs9h/release/deps/libdirs_sys-639bdc321521283b.rlib" "/tmp/cargo-install4Cfs9h/release/deps/libtui-20e40b0d40cfb4e2.rlib" "/tmp/cargo-install4Cfs9h/release/deps/libcassowary-d86a96321c02898a.rlib" "/tmp/cargo-install4Cfs9h/release/deps/libunicode_width-9f3924e3e3141e72.rlib" "/tmp/cargo-install4Cfs9h/release/deps/libunicode_segmentation-9a919c577d642cc2.rlib" "/tmp/cargo-install4Cfs9h/release/deps/libtermion-e7792cde031aadd5.rlib" "/tmp/cargo-install4Cfs9h/release/deps/libnumtoa-7557d30a5e9b1a6d.rlib" "/tmp/cargo-install4Cfs9h/release/deps/librspotify-698216f05d0e1fb4.rlib" "/tmp/cargo-install4Cfs9h/release/deps/libdotenv-e89e02bb033aec32.rlib" "/tmp/cargo-install4Cfs9h/release/deps/libitertools-c80bad646a5eab1d.rlib" "/tmp/cargo-install4Cfs9h/release/deps/libwebbrowser-daebd74259dba216.rlib" "/tmp/cargo-install4Cfs9h/release/deps/libchrono-0805c79bb7ee4099.rlib" "/tmp/cargo-install4Cfs9h/release/deps/librustc_serialize-5b0f76bcae5f9800.rlib" "/tmp/cargo-install4Cfs9h/release/deps/libnum_integer-d4c1ffdd4e03d0ed.rlib" "/tmp/cargo-install4Cfs9h/release/deps/libnum_traits-1e075d15ab2edabd.rlib" "/tmp/cargo-install4Cfs9h/release/deps/libreqwest-a596dff68d420d29.rlib" "/tmp/cargo-install4Cfs9h/release/deps/libuuid-5470b3f4ddf64c15.rlib" "/tmp/cargo-install4Cfs9h/release/deps/librand-77ebb0d412a3eec8.rlib" "/tmp/cargo-install4Cfs9h/re
  = note: /tmp/cargo-install4Cfs9h/release/deps/libreqwest-a596dff68d420d29.rlib(reqwest-a596dff68d420d29.reqwest.f36917vf-cgu.15.rcgu.o): In function `core::ptr::real_drop_in_place':
          reqwest.f36917vf-cgu.15:(.text._ZN4core3ptr18real_drop_in_place17h8541869b63f84185E+0x4d): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.15:(.text._ZN4core3ptr18real_drop_in_place17h8541869b63f84185E+0x60): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.15:(.text._ZN4core3ptr18real_drop_in_place17h8541869b63f84185E+0x8f): undefined reference to `sk_free'
          /tmp/cargo-install4Cfs9h/release/deps/libreqwest-a596dff68d420d29.rlib(reqwest-a596dff68d420d29.reqwest.f36917vf-cgu.15.rcgu.o): In function `core::ptr::real_drop_in_place':
          reqwest.f36917vf-cgu.15:(.text._ZN4core3ptr18real_drop_in_place17hecff3f6f06deb1d7E+0x2f): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.15:(.text._ZN4core3ptr18real_drop_in_place17hecff3f6f06deb1d7E+0x42): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.15:(.text._ZN4core3ptr18real_drop_in_place17hecff3f6f06deb1d7E+0x6d): undefined reference to `sk_free'
          /tmp/cargo-install4Cfs9h/release/deps/libreqwest-a596dff68d420d29.rlib(reqwest-a596dff68d420d29.reqwest.f36917vf-cgu.3.rcgu.o): In function `core::ptr::real_drop_in_place':
          reqwest.f36917vf-cgu.3:(.text._ZN4core3ptr18real_drop_in_place17h8541869b63f84185E+0x4d): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.3:(.text._ZN4core3ptr18real_drop_in_place17h8541869b63f84185E+0x60): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.3:(.text._ZN4core3ptr18real_drop_in_place17h8541869b63f84185E+0x8f): undefined reference to `sk_free'
          /tmp/cargo-install4Cfs9h/release/deps/libreqwest-a596dff68d420d29.rlib(reqwest-a596dff68d420d29.reqwest.f36917vf-cgu.3.rcgu.o): In function `core::ptr::real_drop_in_place':
          reqwest.f36917vf-cgu.3:(.text._ZN4core3ptr18real_drop_in_place17hbca00f17854cfa86E+0x33): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.3:(.text._ZN4core3ptr18real_drop_in_place17hbca00f17854cfa86E+0x46): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.3:(.text._ZN4core3ptr18real_drop_in_place17hbca00f17854cfa86E+0x67): undefined reference to `sk_free'
          /tmp/cargo-install4Cfs9h/release/deps/libreqwest-a596dff68d420d29.rlib(reqwest-a596dff68d420d29.reqwest.f36917vf-cgu.3.rcgu.o): In function `core::ptr::real_drop_in_place':
          reqwest.f36917vf-cgu.3:(.text._ZN4core3ptr18real_drop_in_place17hecff3f6f06deb1d7E+0x2f): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.3:(.text._ZN4core3ptr18real_drop_in_place17hecff3f6f06deb1d7E+0x42): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.3:(.text._ZN4core3ptr18real_drop_in_place17hecff3f6f06deb1d7E+0x6d): undefined reference to `sk_free'
          /tmp/cargo-install4Cfs9h/release/deps/libreqwest-a596dff68d420d29.rlib(reqwest-a596dff68d420d29.reqwest.f36917vf-cgu.3.rcgu.o): In function `reqwest::connect::Connector::new_default_tls':
          reqwest.f36917vf-cgu.3:(.text._ZN7reqwest7connect9Connector15new_default_tls17h8d3027f3120d2e3cE+0x257): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.3:(.text._ZN7reqwest7connect9Connector15new_default_tls17h8d3027f3120d2e3cE+0x26a): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.3:(.text._ZN7reqwest7connect9Connector15new_default_tls17h8d3027f3120d2e3cE+0x288): undefined reference to `sk_free'
          reqwest.f36917vf-cgu.3:(.text._ZN7reqwest7connect9Connector15new_default_tls17h8d3027f3120d2e3cE+0x3b5): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.3:(.text._ZN7reqwest7connect9Connector15new_default_tls17h8d3027f3120d2e3cE+0x3c8): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.3:(.text._ZN7reqwest7connect9Connector15new_default_tls17h8d3027f3120d2e3cE+0x3e8): undefined reference to `sk_free'
          /tmp/cargo-install4Cfs9h/release/deps/libreqwest-a596dff68d420d29.rlib(reqwest-a596dff68d420d29.reqwest.f36917vf-cgu.4.rcgu.o): In function `core::ptr::real_drop_in_place':
          reqwest.f36917vf-cgu.4:(.text._ZN4core3ptr18real_drop_in_place17h03f22d935e3f560bE+0x4d): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.4:(.text._ZN4core3ptr18real_drop_in_place17h03f22d935e3f560bE+0x60): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.4:(.text._ZN4core3ptr18real_drop_in_place17h03f22d935e3f560bE+0x8f): undefined reference to `sk_free'
          /tmp/cargo-install4Cfs9h/release/deps/libreqwest-a596dff68d420d29.rlib(reqwest-a596dff68d420d29.reqwest.f36917vf-cgu.4.rcgu.o): In function `core::ptr::real_drop_in_place':
          reqwest.f36917vf-cgu.4:(.text._ZN4core3ptr18real_drop_in_place17hecff3f6f06deb1d7E+0x2f): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.4:(.text._ZN4core3ptr18real_drop_in_place17hecff3f6f06deb1d7E+0x42): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.4:(.text._ZN4core3ptr18real_drop_in_place17hecff3f6f06deb1d7E+0x6d): undefined reference to `sk_free'
          /tmp/cargo-install4Cfs9h/release/deps/libreqwest-a596dff68d420d29.rlib(reqwest-a596dff68d420d29.reqwest.f36917vf-cgu.5.rcgu.o): In function `core::ptr::real_drop_in_place':
          reqwest.f36917vf-cgu.5:(.text._ZN4core3ptr18real_drop_in_place17hbca00f17854cfa86E+0x33): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.5:(.text._ZN4core3ptr18real_drop_in_place17hbca00f17854cfa86E+0x46): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.5:(.text._ZN4core3ptr18real_drop_in_place17hbca00f17854cfa86E+0x67): undefined reference to `sk_free'
          /tmp/cargo-install4Cfs9h/release/deps/libreqwest-a596dff68d420d29.rlib(reqwest-a596dff68d420d29.reqwest.f36917vf-cgu.5.rcgu.o): In function `core::ptr::real_drop_in_place':
          reqwest.f36917vf-cgu.5:(.text._ZN4core3ptr18real_drop_in_place17he55c792f297e5e24E+0x28): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.5:(.text._ZN4core3ptr18real_drop_in_place17he55c792f297e5e24E+0x3b): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.5:(.text._ZN4core3ptr18real_drop_in_place17he55c792f297e5e24E+0x5d): undefined reference to `sk_free'
          /tmp/cargo-install4Cfs9h/release/deps/libreqwest-a596dff68d420d29.rlib(reqwest-a596dff68d420d29.reqwest.f36917vf-cgu.5.rcgu.o): In function `core::ptr::real_drop_in_place':
          reqwest.f36917vf-cgu.5:(.text._ZN4core3ptr18real_drop_in_place17hecff3f6f06deb1d7E+0x2f): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.5:(.text._ZN4core3ptr18real_drop_in_place17hecff3f6f06deb1d7E+0x42): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.5:(.text._ZN4core3ptr18real_drop_in_place17hecff3f6f06deb1d7E+0x6d): undefined reference to `sk_free'
          /tmp/cargo-install4Cfs9h/release/deps/libreqwest-a596dff68d420d29.rlib(reqwest-a596dff68d420d29.reqwest.f36917vf-cgu.5.rcgu.o): In function `reqwest::async_impl::client::ClientBuilder::build':
          reqwest.f36917vf-cgu.5:(.text._ZN7reqwest10async_impl6client13ClientBuilder5build17hf413fe8b04345345E+0x2c6): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.5:(.text._ZN7reqwest10async_impl6client13ClientBuilder5build17hf413fe8b04345345E+0x2d9): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.5:(.text._ZN7reqwest10async_impl6client13ClientBuilder5build17hf413fe8b04345345E+0x2fe): undefined reference to `sk_free'
          reqwest.f36917vf-cgu.5:(.text._ZN7reqwest10async_impl6client13ClientBuilder5build17hf413fe8b04345345E+0xa62): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.5:(.text._ZN7reqwest10async_impl6client13ClientBuilder5build17hf413fe8b04345345E+0xa75): undefined reference to `sk_pop'
          reqwest.f36917vf-cgu.5:(.text._ZN7reqwest10async_impl6client13ClientBuilder5build17hf413fe8b04345345E+0xa9e): undefined reference to `sk_free'
          /tmp/cargo-install4Cfs9h/release/deps/libnative_tls-6bd62f1981dbd61d.rlib(native_tls-6bd62f1981dbd61d.native_tls.1u6r82qc-cgu.0.rcgu.o): In function `native_tls::imp::TlsConnector::new':
          native_tls.1u6r82qc-cgu.0:(.text._ZN10native_tls3imp12TlsConnector3new17h6c93eca07e6cb695E+0x484): undefined reference to `sk_num'
          native_tls.1u6r82qc-cgu.0:(.text._ZN10native_tls3imp12TlsConnector3new17h6c93eca07e6cb695E+0x4aa): undefined reference to `sk_value'
          /tmp/cargo-install4Cfs9h/release/deps/libnative_tls-6bd62f1981dbd61d.rlib(native_tls-6bd62f1981dbd61d.native_tls.1u6r82qc-cgu.2.rcgu.o): In function `native_tls::TlsConnectorBuilder::identity':
          native_tls.1u6r82qc-cgu.2:(.text._ZN10native_tls19TlsConnectorBuilder8identity17hebf2175177689622E+0x43): undefined reference to `sk_pop'
          native_tls.1u6r82qc-cgu.2:(.text._ZN10native_tls19TlsConnectorBuilder8identity17hebf2175177689622E+0x56): undefined reference to `sk_pop'
          native_tls.1u6r82qc-cgu.2:(.text._ZN10native_tls19TlsConnectorBuilder8identity17hebf2175177689622E+0x78): undefined reference to `sk_free'
          /tmp/cargo-install4Cfs9h/release/deps/libopenssl-f1d462493160d7b7.rlib(openssl-f1d462493160d7b7.openssl.cdqq66go-cgu.0.rcgu.o): In function `openssl::ssl::SslMethod::tls':
          openssl.cdqq66go-cgu.0:(.text._ZN7openssl3ssl9SslMethod3tls17hae668f941a8dc151E+0x2): undefined reference to `SSLv23_method'
          /tmp/cargo-install4Cfs9h/release/deps/libopenssl-f1d462493160d7b7.rlib(openssl-f1d462493160d7b7.openssl.cdqq66go-cgu.0.rcgu.o): In function `<openssl::ssl::SslContext as core::clone::Clone>::clone':
          openssl.cdqq66go-cgu.0:(.text._ZN63_$LT$openssl..ssl..SslContext$u20$as$u20$core..clone..Clone$GT$5clone17h97f995de37326510E+0x24): undefined reference to `CRYPTO_add_lock'
          /tmp/cargo-install4Cfs9h/release/deps/libopenssl-f1d462493160d7b7.rlib(openssl-f1d462493160d7b7.openssl.cdqq66go-cgu.0.rcgu.o): In function `openssl::ssl::Ssl::new':
          openssl.cdqq66go-cgu.0:(.text._ZN7openssl3ssl3Ssl3new17h1ea4689978bace7aE+0x9a): undefined reference to `CRYPTO_add_lock'
          /tmp/cargo-install4Cfs9h/release/deps/libopenssl-f1d462493160d7b7.rlib(openssl-f1d462493160d7b7.openssl.cdqq66go-cgu.15.rcgu.o): In function `std::sync::once::Once::call_once::{{closure}}':
          openssl.cdqq66go-cgu.15:(.text._ZN3std4sync4once4Once9call_once28_$u7b$$u7b$closure$u7d$$u7d$17h5677c6dfbb7094a0E+0x1a): undefined reference to `SSL_get_ex_new_index'
          /tmp/cargo-install4Cfs9h/release/deps/libopenssl-f1d462493160d7b7.rlib(openssl-f1d462493160d7b7.openssl.cdqq66go-cgu.15.rcgu.o): In function `std::sync::once::Once::call_once::{{closure}}':
          openssl.cdqq66go-cgu.15:(.text._ZN3std4sync4once4Once9call_once28_$u7b$$u7b$closure$u7d$$u7d$17h7f9137704afd4bd0E+0x3e): undefined reference to `SSL_get_ex_new_index'
          /tmp/cargo-install4Cfs9h/release/deps/libopenssl-f1d462493160d7b7.rlib(openssl-f1d462493160d7b7.openssl.cdqq66go-cgu.15.rcgu.o): In function `core::ops::function::FnOnce::call_once{{vtable-shim}}':
          openssl.cdqq66go-cgu.15:(.text._ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17h2bf8105945cea7d0E+0x3e): undefined reference to `SSL_get_ex_new_index'
          /tmp/cargo-install4Cfs9h/release/deps/libopenssl-f1d462493160d7b7.rlib(openssl-f1d462493160d7b7.openssl.cdqq66go-cgu.15.rcgu.o): In function `core::ops::function::FnOnce::call_once{{vtable-shim}}':
          openssl.cdqq66go-cgu.15:(.text._ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17h3a60acbce837a2ffE+0x1a): undefined reference to `SSL_get_ex_new_index'
          /tmp/cargo-install4Cfs9h/release/deps/libopenssl-f1d462493160d7b7.rlib(openssl-f1d462493160d7b7.openssl.cdqq66go-cgu.15.rcgu.o): In function `openssl::ssl::connector::SslConnector::builder':
          openssl.cdqq66go-cgu.15:(.text._ZN7openssl3ssl9connector12SslConnector7builder17h0c046c5b88fa9875E+0x39): undefined reference to `SSLeay'
          /tmp/cargo-install4Cfs9h/release/deps/libopenssl-f1d462493160d7b7.rlib(openssl-f1d462493160d7b7.openssl.cdqq66go-cgu.2.rcgu.o): In function `<openssl::x509::X509Ref as alloc::borrow::ToOwned>::to_owned':
          openssl.cdqq66go-cgu.2:(.text._ZN65_$LT$openssl..x509..X509Ref$u20$as$u20$alloc..borrow..ToOwned$GT$8to_owned17h0b86f3b926f154f6E+0x21): undefined reference to `CRYPTO_add_lock'
          /tmp/cargo-install4Cfs9h/release/deps/libopenssl-f1d462493160d7b7.rlib(openssl-f1d462493160d7b7.openssl.cdqq66go-cgu.2.rcgu.o): In function `<openssl::x509::X509 as core::clone::Clone>::clone':
          openssl.cdqq66go-cgu.2:(.text._ZN58_$LT$openssl..x509..X509$u20$as$u20$core..clone..Clone$GT$5clone17h162fdad7cc6a69a7E+0x21): undefined reference to `CRYPTO_add_lock'
          /tmp/cargo-install4Cfs9h/release/deps/libopenssl_sys-870c6348f4aa41df.rlib(openssl_sys-870c6348f4aa41df.openssl_sys.2czsmp8s-cgu.13.rcgu.o): In function `std::sync::once::Once::call_once::{{closure}}':
          openssl_sys.2czsmp8s-cgu.13:(.text._ZN3std4sync4once4Once9call_once28_$u7b$$u7b$closure$u7d$$u7d$17ha5097da62f58cce2E+0x1f): undefined reference to `SSL_library_init'
          openssl_sys.2czsmp8s-cgu.13:(.text._ZN3std4sync4once4Once9call_once28_$u7b$$u7b$closure$u7d$$u7d$17ha5097da62f58cce2E+0x25): undefined reference to `SSL_load_error_strings'
          openssl_sys.2czsmp8s-cgu.13:(.text._ZN3std4sync4once4Once9call_once28_$u7b$$u7b$closure$u7d$$u7d$17ha5097da62f58cce2E+0x2b): undefined reference to `OPENSSL_add_all_algorithms_noconf'
          openssl_sys.2czsmp8s-cgu.13:(.text._ZN3std4sync4once4Once9call_once28_$u7b$$u7b$closure$u7d$$u7d$17ha5097da62f58cce2E+0x31): undefined reference to `CRYPTO_num_locks'
          openssl_sys.2czsmp8s-cgu.13:(.text._ZN3std4sync4once4Once9call_once28_$u7b$$u7b$closure$u7d$$u7d$17ha5097da62f58cce2E+0x220): undefined reference to `CRYPTO_set_locking_callback'
          openssl_sys.2czsmp8s-cgu.13:(.text._ZN3std4sync4once4Once9call_once28_$u7b$$u7b$closure$u7d$$u7d$17ha5097da62f58cce2E+0x23b): undefined reference to `CRYPTO_set_id_callback'
          collect2: error: ld returned 1 exit status

error: aborting due to previous error

error: failed to compile `spotify-tui v0.6.2`, intermediate artifacts can be found at `/tmp/cargo-install4Cfs9h`

Caused by:
  Could not compile `spotify-tui`.

`

**Comment by Rigellute** [comment]
Ah sorry about this.

Seems `openssl` is causing a few problems (see https://github.com/Rigellute/spotify-tui/issues/65).

Perhaps you've already done this, but could you try this?
```bash
sudo apt-get update
sudo apt-get install build-essential
```

**Comment by bmiller59** [comment]
@Rigellute Thank you for the suggestion, but I was already up to date (no effect, same result). Please let me know if you have any other suggestions.

**Comment by synth-ruiner** [comment]
installing libssl-dev fixed this for me on Mint 19.2 (based on Ubuntu 18.04).
`sudo apt-get install libssl-dev`

**Comment by synth-ruiner** [comment]
you'll need `pkg-config` too apparently.

**Comment by bmiller59** [comment]
I am still getting this error with v0.8.0 and the various recommendations have not helped.

The good news is that I was able to download and run the release! So I will use that instead.

**Comment by Rigellute** [comment]
Thanks for the update @bmiller59
