### ISSUE TITLE
Like Emoji ♥ not showing with no configuration file config.yml

### ISSUE THREAD

**Issue by Andful** [Rigellute/spotify-tui#725]
`spt` shows □ (blank) character instead of ♥.
When installing `spotify-tui` with `cargo install spotify-tui` and even after playing `spt` a few times there was no `config.yml` file generated. I don't know if it is an intended behavior. Only after I created a `config.yml` file at the path `$HOME/.config/spotify-tui/` with the sample configuration in the `README.md` file I start seeing the ♥ emoji.

**Comment by Andful** [comment]
NVM, e471bb7  should fix it. I did not try it myself but if it fixes the issue feel free to close it

**Comment by Rigellute** [comment]
Indeed this is now fixed
