### ISSUE TITLE
Default setting clashes "shuffle" command  with "saving track in list or table" command

### ISSUE THREAD

**Issue by Andful** [Rigellute/spotify-tui#726]
Currently both the "shuffle" and the "saving track in list or table" are mapped to the `s` key. This prevents for the "saving track in list or table" command to be ran. It works fine if the "shuffle" command is mapped to a different key though.

**Comment by Rigellute** [comment]
Ah it looks like the README documentation is wrong. `ctrl-s` should be for cycling through shuffle, and `s` is for saving.
