### ISSUE TITLE
Liked songs have U+F7D0 () next to them

### ISSUE THREAD

**Issue by UnlimitedCookies** [Rigellute/spotify-tui#740]
All my liked songs have a weird looking Unicode character next to them. Is this on purpose?

![image](https://user-images.githubusercontent.com/49200216/108527478-9c8b3700-72d2-11eb-9c6d-b3cd03c5d887.png)

**Comment by OrangeFran** [comment]
This got fixed with a3e214cac84fe36dd2ba62b4d627ced972dda390. You are probably on an older version. If you can't update for any reason, just put these lines into `~/.config/spotify-tui/config.yml`:

``` yaml
behavior:
    liked_icon: "♥"
```

**Comment by UnlimitedCookies** [comment]
Amazing. Somehow I missed this PR when looking through the issues beforehand.

Then, I am just waiting for the next release.

**Comment by UnlimitedCookies** [comment]
@Rigellute I would be humbled to see a new release so that a3e214c reaches us.

**Comment by Rigellute** [comment]
Apologies for the delay. This is now released [v0.24.0](https://github.com/Rigellute/spotify-tui/releases/tag/v0.24.0)

**Comment by UnlimitedCookies** [comment]
Awesome sauce
