### ISSUE TITLE
Cannot initialize headlessly: "Error: no context available"

### ISSUE THREAD

**Issue by j-hui** [Rigellute/spotify-tui#741]
I run spotifyd as a service that starts automatically on boot. When I boot up my machine, I'd like it so that I can immediately start using spt's CLI to interact with spotifyd without having to first go into the UI and select a device.

I was trying to do this via: `spt playback --device <device-name>`, but it would tell me `Error: no context available`. If I go into the UI to select a device, the CLI works as normal.

I'm wondering if there's something I'm missing here, or if what I'm trying is at all possible?

**Comment by OrangeFran** [comment]
The command line interface and the terminal user interface do not share functionality. The `playback` command is there to control the playback of a device. By default, `spt playback --device <device-name>` will just output the current song on the specified device. If nothing is playing, it will output the error message you received.

Maybe you want to start a playlist? Then you can just use `spt play --playlist --name <playlist-name> --device <device-name>`. Now regarding the device selection: I think spotify-tui stores the last used device id in a file so you do not always have to use the `--device` flag. I hope I could help.

**Comment by OrangeFran** [comment]
The `playback` subcommand is just there to pause, shuffle, repeat, skip and other stuff. You play something with `play`. And to list or search you can use `list` and `search`.

**Comment by j-hui** [comment]
I think I understand now, thanks @OrangeFran . I suppose what I was trying won't work, but that's ok.

Another thing that I wanted to do was just to be able to start playing on my current machine after it reboots (or in any other situation where Spotify believes nothing is playing on my current device). And I wanted to this without invoking the `spt` GUI (e.g., so that I can just run it via Rofi). What seems to work is to run `spt playback --transfer <device-name>`, which will allow me to continue playing whatever was playing before on my current device.

**Comment by trbKnl** [comment]
I am trying to do the exactly same thing, this is also relevant if for whatever reason spotifyd has been restarted (in case of system resume after sleep for example).
Steps to reproduce:
```
$ systemctl --user restart spotifyd.service
$ spt playback --toggle
Error: no context available
```
With info in the answer of j-hui I created a "toggle" script which works for my purposes:
```
#!/bin/bash
device="spotifyd_pulseaudio"
if spt playback --toggle; then
    exit
else
    echo "spt playback --toggle, didnt work, trying spt playback --transfer "$device
    spt playback --transfer $device
fi
```
