### ISSUE TITLE
Keyboard shortcut to save (ie like) currently playing track

### ISSUE THREAD

**Issue by ewen-lbh** [Rigellute/spotify-tui#744]
I'd like to have another shortcut to save the _currently playing_ track.
This is useful every time you're listening to new stuff: if you stumble upon a track you like, you can directly mark it as such.

No, pressing `o` then `s` is not equivalent, since `o` will not highlight the currently playing track, but the one that was highlighted before switching contexts

**Comment by OrangeFran** [comment]
You could just press `escape` and then go down to the currently playing track, press `enter` and then `s`.
Or using the cli, you could type `spt pb --like`. Maybe `b` and `s` works too, but I haven't tried.

**Comment by ewen-lbh** [comment]
Wow, I didn't know about `spt pb` ! thanks!
