### ISSUE TITLE
No config (config.yml) in windows install (scoop)

### ISSUE THREAD

**Issue by HaxWire** [Rigellute/spotify-tui#745]
Hi there.

Cant seem to find any config files or any files other than install files in scoop.
Is the spt-tui config files being added to a diffrent dir than scoop?

Not sure if its human error or app error.

**Comment by Rigellute** [comment]
I'm not very familiar with windows, but there should be a config file in the windows equivalent of `${HOME}/.config/spotify-tui/config.yml`

**Comment by notnavindu** [comment]
Create a new file called `config.yml` in `C:\Users\<user>\.config\spotify-tui` and add your config there

**Comment by rithwikjc** [comment]
I also have the same issue. I found the config directory at ` C:\Users\<user>\.config\spotify-tui` but there's no `config.yml`.
It would be great if the default configuration is generated at this location or if there was a copy of it. Currently I copied the config from the readme.

**Comment by 0x-h4x** [comment]
Update: 
As [rithwikjc](https://github.com/rithwikjc) said; you'll need to add your own config file when installing using windows.
I just copied the config file in the readme and did my changes.
