### ISSUE TITLE
Stop playing upon exit

### ISSUE THREAD

**Issue by petobens** [Rigellute/spotify-tui#754]
Hi! I'm using spt with spotifyd. I've noticed that if a song is playing and I exit spt then the music continues until I actually exit spotifyd (i'm running it with `--no-daemon`). I would've expected the music to stop upon exiting spt. Is this a feature? Thanks in advance.

**Comment by OrangeFran** [comment]
`spotify-tui` is just a frontend to the spotify web api. It doesn't actually play the songs. That is done by `spotifyd`.
So closing spotify-tui should not stop the other process that actually plays the songs provided by spotify. Imagine this: You want to change the song playing on your phone through your computer. If you open spotify-tui, change the song and then close spotify-tui again, the music should not stop, right?

Anyway, if you want to just stop spotifyd upon exiting spotify-tui on your local computer, you could just create a wrapper script.
```bash
#!/usr/bin/env bash
spotifyd && spt && killall spotifyd
```

**Comment by petobens** [comment]
Thanks. I guess it makes total sense.

**Comment by petobens** [comment]
Feel free to close if there is nothing else to do from spt side.

**Comment by petobens** [comment]
Feel free to close if there is nothing else to do from spt side.

**Comment by Rigellute** [comment]
Thank you both 👍
