### ISSUE TITLE
crash on non-ascii symbols in search input 

### ISSUE THREAD

**Issue by kumekay** [Rigellute/spotify-tui#77]
Application exits on any keypress after first appearance of non-ascii symbol in search bar, like ž, Ф, or 🥰

Steps to reproduce:
Just press `/` and try to enter any non-ascii character

Version: spotify-tui 0.6.2
Os: Macos 10.15
Terminal: iterm2 Build 3.3.3

**Comment by Rigellute** [comment]
A fix for this got merged today. https://github.com/Rigellute/spotify-tui/pull/30

Will be in the next release 👍
