### ISSUE TITLE
Configures icons in status message

### ISSUE THREAD

**Issue by AckslD** [Rigellute/spotify-tui#781]
I've set the following icons in my config:
```
behavior:
    playing_icon:  
    pause_icon:  
```

When a song is playing `spt pb -s -f "%s"` correctly gives ``, however when paused gives `` instead of my configured icon. Is this the intended behaviour?

I would like to use `spt pb -s -f "%s"` in some of my scripts to know if spotify is playing or not and for this reason would like to know what output I can expect.
For this reason I would actually prefer getting an output e.g. `Playing`/`Paused` rather than an icon. But icons are fine, if they could be configured.

**Comment by OrangeFran** [comment]
Try `paused_icon` instead of `pause_icon`. I think this is the correct name.

**Comment by AckslD** [comment]
Thanks a lot @OrangeFran! Stupid typo by me... Also really nice that one can use "Playing"/"Paused" as "icons 👍
