### ISSUE TITLE
[Feature Request] Search in help screen

### ISSUE THREAD

**Issue by XPhyro** [Rigellute/spotify-tui#786]
When on the help screen, search the help text (like in NeoMutt) instead of in Spotify. When I forget a key binding, I have to manually find the action I'm looking for. This would speed up the process and also allow newcomers to adjust faster.

**Comment by OrangeFran** [comment]
#431, i don't know if there's still someone working on it though

**Comment by XPhyro** [comment]
Didn't notice that issue, thanks. Closing as duplicate.
