### ISSUE TITLE
Windows error on setup (device)

### ISSUE THREAD

**Issue by g-avalos** [Rigellute/spotify-tui#787]
I've installed on windows 10, i complete all the data but when i accept on spotify and callback localhost:8888 i got a not connection.
In the readme says i must copy and paste the url in the prompt but it doesnt work.
I check client.yml got all data except device it got - 
I delete the app, re install, redo de process but always are the same.
Spt stops running
![image](https://user-images.githubusercontent.com/57682251/114544129-965d6b00-9c30-11eb-90f9-4e6dc26fcc53.png)

**Comment by auchtopus** [comment]
I'm also having the same problem on mac

I copied the link in and it resulted in the same problem

**Comment by souxd** [comment]
Win10 user here. Check if the spotify app redirect link is there
https://i.imgur.com/8q93GSb.png
Also you can edit your client ID and client secret at C:\Users\Username\.config

**Comment by aleksanderwalczuk** [comment]
@g-avalos in my case it was a trailing slash in the localhost port. To fix it I've added both `http://localhost:8888/callback/` and `http://localhost:8888/callback` as whitelisted URIs

**Comment by g-avalos** [comment]
Thanks to souxd and aleksander
i put both with / and without, rerun and works

**Comment by aleksanderwalczuk** [comment]
Great! Then you can close the issue I guess 🙂

**Comment by g-avalos** [comment]
yes so sorry!!!!
