### ISSUE TITLE
spotify-tui renders  next to every song.

### ISSUE THREAD

**Issue by dmilith** [Rigellute/spotify-tui#792]
How to change that wrong utf next to every song on the list? After selection it's "", looks like this: http://s.verknowsys.com/fd91fcca44183ef28d3903ea41585bee.png

**Comment by UnlimitedCookies** [comment]
I already pointed this out in #740 
This already has been fixed, but not yet made its way into a release.

**Comment by Rigellute** [comment]
Apologies for the delay. This is now released [v0.24.0](https://github.com/Rigellute/spotify-tui/releases/tag/v0.24.0)
