### ISSUE TITLE
Liked symbol does not load

### ISSUE THREAD

**Issue by jvataja** [Rigellute/spotify-tui#794]
<img width="248" alt="kuva" src="https://user-images.githubusercontent.com/47065445/115423405-774d7300-a206-11eb-8275-f438308fc777.png">
Symbol for a liked song does not load correctly, see attachment.

**Comment by UnlimitedCookies** [comment]
I already pointed this out in #740
This already has been fixed, but not yet made its way into a release.

**Comment by Rigellute** [comment]
Apologies for the delay. The fix for this is now released [v0.24.0](https://github.com/Rigellute/spotify-tui/releases/tag/v0.24.0)
