### ISSUE TITLE
Error 504/503

### ISSUE THREAD

**Issue by Rus1s** [Rigellute/spotify-tui#799]
Hi, when I use spotify-tui it connect and works fine but when I do somethig, like change song or anything else, it loads for some seconds and then it gives me an error 503 (sometimes for like a second is 504 then it instantly change to 503). I have a premium account and everything seems correct in the developer page. Am I missing something? Seems like a problem with API but I don't know what it could be

**Comment by samtell21** [comment]
I am also experiencing this problem.  Music is playing fine, but the playback cli only ever returns the following:
`Error: Spotify API reported error code 503`
I can still interact with the music, toggle, skip song, etc, but it doesn't want to give me the any of the formatted output.
Also the actual tui keeps dropping me into that red error screen.  I can just escape out of it, but it is a nuisance.

**Comment by adesprez** [comment]
Same here. Using version 0.23.0.
I noticed that behavior at the beginning of the week. I'm using spotify-tui + spotifyd.

**Comment by hisbaan** [comment]
Exact same thing here, whether using the web player or spotifyd.

I'm on arch linux, using version 0.23.0-1.

**Comment by daMelody** [comment]
According to [Spotify Web API](https://developer.spotify.com/documentation/web-api/), it seems like 503 is a server error:

> Service Unavailable - The server is currently unable to handle the request due to a temporary condition which will be alleviated after some delay. You can choose to resend the request again.

I couldn't find any documentation on the 504 error on Spotify's developer portal

**Comment by Rus1s** [comment]
> According to [Spotify Web API](https://developer.spotify.com/documentation/web-api/), it seems like 503 is a server error:
> 
> > Service Unavailable - The server is currently unable to handle the request due to a temporary condition which will be alleviated after some delay. You can choose to resend the request again.

I know, but I cant't find a fix.
 
> I couldn't find any documentation on the 504 error on Spotify's developer portal

Error 504 should be "Gateway timeout"

**Comment by samtell21** [comment]
Everything seems back to normal for me now.  Guess it was a problem on spotify's end.

**Comment by Rus1s** [comment]
> Everything seems back to normal for me now. Anyone else?

Back to normal for me too
> Guess it was a problem on spotify's end.

I'm thinking the same thing, I think I can close the issue.
Thanks everyone!
