### ISSUE TITLE
Problems selecting playable track

### ISSUE THREAD

**Issue by jq-rs** [Rigellute/spotify-tui#8]
Selecting track to be played does not work when spotify-tui is running on Ubuntu and Spotify-app in Windows.

![image](https://user-images.githubusercontent.com/23149473/66308566-1efa9d00-e910-11e9-898e-d545c3de779a.png)

**Comment by Rigellute** [comment]
Hmm... one more thing to check is if you have a Spotify Premium account?

Unfortunately, Spotify requires a Premium account to control playback.

I have added this point to that error message here https://github.com/Rigellute/spotify-tui/commit/8068b15f81d7d85fdf90d89ed03ddb8a7928c1a8

**Comment by jq-rs** [comment]
Seems I need to create the app id under premium. After that it works! Some songs are duplicated on the play list, but just a minor thing. Thanks for this cool application!

**Comment by Rigellute** [comment]
Thank you! 
Are the duplicated tracks in the "Recently played" list? Or somewhere else?

**Comment by jq-rs** [comment]
Yes, they are on Recently played list.
