### ISSUE TITLE
Missing client_id parameter

### ISSUE THREAD

**Issue by mrq-andras** [Rigellute/spotify-tui#815]
I accidentally missed my client ID in the setup, and have tried uninstalling it, but every time i try to run spotify-tui i get this webpage:
https://accounts.spotify.com/authorize?response_type=code&scope=playlist-read-collaborative%20playlist-read-private%20playlist-modify-private%20playlist-modify-public%20user-follow-read%20user-follow-modify%20user-library-modify%20user-library-read%20user-modify-playback-state%20user-read-currently-playing%20user-read-playback-state%20user-read-playback-position%20user-read-private%20user-read-recently-played&state=5IgDUdTQvK1X0IGh&client_id=&redirect_uri=http:%2F%2Flocalhost:8888%2Fcallback&

and all it says is  "missing required parameter: client_id

how can i reset spotify-tui for a fresh installation?

**Comment by Soulayrol** [comment]
You can edit this file ${HOME}/.config/spotify-tui/config.yml

**Comment by codemeatloaf** [comment]
> You can edit this file ${HOME}/.config/spotify-tui/config.yml

How should I edit it? do I just put in my client ID and client secret?
