### ISSUE TITLE
Please add keybinding to directly exit

### ISSUE THREAD

**Issue by pezcurrel** [Rigellute/spotify-tui#817]
Hi and thanks all for the great program :)
I think it would be useful to have the possibility to exit the program at any time by pressing a specific key or key-combo, without having to press the "back" key multiple times.

**Comment by Rigellute** [comment]
Thanks @pezcurrel.

You can exit `spotify-tui` by pressing `ctrl-c`. This is the "global" exit binding.

**Comment by pezcurrel** [comment]
Thanks Rigellute :)
Is this "global exit" binding assignable to other keys/key combos?
If so, what keyword should I use in the "keybindings:" section of config.yml?

**Comment by Rigellute** [comment]
Just double checked and ctrl-c is currently hardcoded, I'm afraid.

We could expose this binding in the keybind config though.

**Comment by pezcurrel** [comment]
It would be great :)
Sadly I know too little to help.
