### ISSUE TITLE
No devices are listed in the device selection menu

### ISSUE THREAD

**Issue by zeroeightysix** [Rigellute/spotify-tui#83]
Probably a duplicate of #14 .
Even with the official spotify client open (or with `spotifyd` running), the device list shows no devices.

Running on arch linux, compiled `spotify-tui` as of commit ef39431.

```
$ spotify --version
Spotify version 1.1.10.546.ge08ef575, Copyright (c) 2019, Spotify Ltd
```
```
$ spotifyd --version
spotifyd 0.2.18
```

**Comment by Rigellute** [comment]
Hmm... working well for me.

Only thing I can think of is that the client id and secret are for a different spotify account to the one you're logged in to with the official client or spotifyd?

**Comment by zeroeightysix** [comment]
> Only thing I can think of is that the client id and secret are for a different spotify account to the one you're logged in to with the official client or spotifyd?

Wow, on the dot. After carefully checking the client id and secret, I realised I made them on my old spotify account, with an identical name as my premium one. Thanks!
