### ISSUE TITLE
Download songs like the spotify desktop client

### ISSUE THREAD

**Issue by mustaphazorgati** [Rigellute/spotify-tui#849]
Is there a way to download songs like in the spotify client, so that I can play some music offline?

If yes: where and how can I configure it?

If not: is this even possible? I think that it'll be a great additon

**Comment by fennewald** [comment]
This project doesn't actually output any sound -- it controls something that does. Offline caching would have to be managed by whatever tool you're using to play audio, not spt.

**Comment by mustaphazorgati** [comment]
Thank you for the clarification. :)
