### ISSUE TITLE
Recently Played API error

### ISSUE THREAD

**Issue by Myhat2you** [Rigellute/spotify-tui#855]
When I open "Recently Played" I get this error:
![err](https://user-images.githubusercontent.com/43269765/129977922-a5fc95c8-c9d5-4b4b-9391-0a069a81e168.png)
`convert result failed, reason: Error("invalid type: null, expected struct Cursor", line: 4, column: 18); content: ["{\n  \"items\" : [ ],\n \"next\" : null,\n \"cursors\" : null,\n \"limit\" : 32,\n \"href\" : \"https://api.spotify.com/v1/me/player/recently-played?limit=32\"\n}"]`

Obligatory notes:
- Arch Linux 5.13.10
- Using spotifyd
- Installed via AUR

**Comment by bree29** [comment]
Same error when searching "Valhalla" (or shorter) ; didn't find any other word provoking that issue.

```
$ yay -Si spotify-tui                                                                                     
:: Querying AUR...
Repository      : aur
Name            : spotify-tui
Keywords        : None
Version         : 0.24.0-1
Description     : Spotify client for the terminal written in Rust
URL             : https://github.com/Rigellute/spotify-tui
AUR URL         : https://aur.archlinux.org/packages/spotify-tui
Groups          : None
Licenses        : MIT
Provides        : spotify-tui
Depends On      : openssl  libxcb
Make Deps       : cargo  python
Check Deps      : None
Optional Deps   : None
Conflicts With  : spotify-tui
Maintainer      : Conni2461
Votes           : 46
Popularity      : 0.580273
First Submitted : Mon 07 Oct 2019 08:28:05 PM CEST
Last Modified   : Mon 26 Apr 2021 01:37:55 PM CEST
Out-of-date     : No
```

AFAIC "Recently played" won't get me into that error on my side. It could be related to some error parsing the items (invalid char, i don't know...).

Both running from Spotify app (flatpak) or spotifyd.

**Comment by Myhat2you** [comment]
After updating to version 0.25.0-1 I'm no longer getting this issue. I also tried searching for "Valhalla" and got no error, so hopefully this is resolved.
