### ISSUE TITLE
No device Id Selected

### ISSUE THREAD

**Issue by Rassska** [Rigellute/spotify-tui#857]
![Screenshot from 2021-08-20 14-32-28](https://user-images.githubusercontent.com/73281386/130227154-69346ae2-b785-4782-a157-def5db238e92.png)

**Comment by Myhat2you** [comment]
If you're gonna post an issue please add as many relevant details as you can, i.e.
- Do you have a premium Spotify account?
- Are you using Spotifyd or the official Spotify client?
- What's your device name and does it contain spaces?
- Has spotify-tui worked for you before or is this error new?
- What OS (and OS version) are you running?
- What have you tried to do to solve this issue?

Make sure you've read through the [installation instructions](https://github.com/Rigellute/spotify-tui#installation) and look for solved issues similar to your problem (#679).

**Comment by Rassska** [comment]
I'm sry, I got it, thanks for #679

**Comment by Myhat2you** [comment]
> I'm sry, I got it, thanks for #679

No problem :) Glad you got it fixed
