### ISSUE TITLE
error: linking with `cc` failed: exit status: 1

### ISSUE THREAD

**Issue by AshutoshSajan** [Rigellute/spotify-tui#888]
Error while installing the program

```sh
> cargo install spotify-tui           
    Updating crates.io index
   Installing spotify-tui v0.25.0
   Compiling autocfg v1.0.1
   Compiling libc v0.2.102
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.29
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.76
   Compiling log v0.4.14
   Compiling memchr v2.4.1
   Compiling cc v1.0.70
   Compiling bitflags v1.2.1
error: linking with `cc` failed: exit status: 1


/usr/bin/ld: cannot find Scrt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
collect2: error: ld returned 1 exit status
```

**Comment by Anonymboy20700** [comment]
> Error while installing the program
> 
> 
> 
> ```sh
> 
> > cargo install spotify-tui           
> 
>     Updating crates.io index
> 
>    Installing spotify-tui v0.25.0
> 
>    Compiling autocfg v1.0.1
> 
>    Compiling libc v0.2.102
> 
>    Compiling cfg-if v1.0.0
> 
>    Compiling proc-macro2 v1.0.29
> 
>    Compiling unicode-xid v0.2.2
> 
>    Compiling syn v1.0.76
> 
>    Compiling log v0.4.14
> 
>    Compiling memchr v2.4.1
> 
>    Compiling cc v1.0.70
> 
>    Compiling bitflags v1.2.1
> 
> error: linking with `cc` failed: exit status: 1
> 
> 
> 
> 
> 
> /usr/bin/ld: cannot find Scrt1.o: No such file or directory
> 
> /usr/bin/ld: cannot find crti.o: No such file or directory
> 
> collect2: error: ld returned 1 exit status
> 
> ```
> 
>

**Comment by AshutoshSajan** [comment]
`sudo apt install gcc-multilib` fixed that for me
