### ISSUE TITLE
Unable to authorize

### ISSUE THREAD

**Issue by p1g30n** [Rigellute/spotify-tui#9]
Every time I try to authorize I get `INVALID_CLIENT: Invalid redirect URI` as a reply from Spotify.

The URL generated by spotify-tui is:
`https://accounts.spotify.com/authorize?redirect_uri=http:%2F%2Flocalhost:8888%2Fcallback&client_id=[CLIENT_ID]&response_type=code&state=[STATE]&scope=playlist-read-private%20user-library-modify%20user-library-read%20user-modify-playback-state%20user-read-currently-playing%20user-read-playback-state%20user-read-private%20user-read-recently-played&`

This happens independent of browser with the homebrew version on MacOs 10.14.5

**Comment by Rigellute** [comment]
It's a shame the auth process is so strange, but it seems this is the only way at the moment.

As @QuinnFreedman says, adding ``http://localhost:8888/callback` to `Redirect URIs` is essential.

**Comment by Rigellute** [comment]
It feels wrong when this lands you back on `localhost`, which doesn't do anything. 

I'll explore starting a localhost server to show a simple webpage.
