### ISSUE TITLE
Playback stuttering

### ISSUE THREAD

**Issue by stevensonmt** [Rigellute/spotify-tui#917]
Just noticed today tracks begin to play, go about 3 - 10 seconds and then restart. Doesn't matter which track. Version 0.25.0. For comparison ncspot plays tracks correctly.

**Comment by stevensonmt** [comment]
Appears to have been an error in my systemd service configuration for spotifyd. Closing this and apologies for cluttering the issue tracker. Thanks for spotify-tui!

**Comment by kublaios** [comment]
> Appears to have been an error in my systemd service configuration for spotifyd. Closing this and apologies for cluttering the issue tracker. Thanks for spotify-tui!

Is this something you could share? I applied the fix in https://github.com/Spotifyd/spotifyd/issues/1020 but to no avail.
