### ISSUE TITLE
Cant select device, 404 not found

### ISSUE THREAD

**Issue by stacyharper** [Rigellute/spotify-tui#931]
I'm trying to select a spotifyd device on an aarch64 (which seems to compile and works correctly now). I got this message when selecting the device : 

```
Api response: Spotify API error code 404: Not found.
If you are trying to play a track, please check that
1. You have a Spotify Premium Account
2. Your playback device is active and selected - press `d` to go to device selection menu
3. If you're using spotifyd as a playback device, your device name must not contain spaces
Hint: a playback device must be either an official spotify client or a light weight alternative such as spotifyd
Press <Esc> to return
```

No log seems to be output by spotifyd.

Am I missing something ?

edit: I got the exact same issue on an x86_64 voidlinux distro. spotifyd command `spotifyd -b pulseaudio -u myuuser -P "pass Web/accounts.spotify.com/myuser" --no-daemon --verbose`

edit2: I got the same issue using the Web client on https://client.spotify.com on Firefox. So it probably is a spotify-tui issue ?

**Comment by stacyharper** [comment]
It seems to works today o_O Dunno what happen yersterday. I'll re-open if needed !

**Comment by RezhaBlue** [comment]
Please consider re-opening. I am also on Mac M1 which uses aarch64 and experiencing this behavior. I used brew to install and everything build and runs fine but occasionally this behavior happens. 

I will be listening to a song and it'll just randomly stop and spotify-tui will tell me the device cant be found and I can verify spotifyd (as a process or a brew service) is still running when this happens. Sometimes as soon as I start spotifyd, then start spotify-tui I will try to look up a song or play a song and immediately be hit with the 404. Sometimes it takes a few minutes, sometimes a few hours of listening. 

When this happens I will try to:
-  stop and start spotifyd, 
-  kill and start it, 
-  restart the brew service, 
-  or kill both spotifyd and spotify-tui

and relaunch both processes. Regardless of method this behavior will reappear randomly (anywhere from right at launch to minutes to hours in).

The only insight I can give that feels pseudo-random is **this seems to happen with increased frequency if I use spotify-tui to perform a search and play a song directly from the search results songs section**. This could be coincidence I do not have a good way of testing.

If anyone has any idea for what logs or config changes or anything else I can try I'm all ears and can dedicate time to regularly update on this issue. I love both these apps and want to see them succeed and they are part of my daily workflow.
