### ISSUE TITLE
Can't see spotifyd client in tui

### ISSUE THREAD

**Issue by roberthilleck** [Rigellute/spotify-tui#951]
I cannot find my spotifyd client in the device list. 
The Spotifyd client is started and working correctly. I can connect to the spotifyd client e.g. via my smartphone with the spotify app. 
As soon as I connect to the spotifyd client with another device, it appears in the spotify-tui device list.
How can I connect to the client directly in tui without connecting another device first?

**Comment by nikitamounier** [comment]
Use `brew services start spotifyd` to keep it running as a background daemon – that should work. And don't worry, it barely uses any memory.

Also, just in case, double check the `spotifyd.conf` file is inside `~/.config/spotifyd`.

**Comment by scouw** [comment]
I'm having the same exact issue with librespot. 
Connecting to the client via my phone and then using spotify-tui works flawlessly but spotify-tui will not find the librespot client by itself, my phone does however show up. Tried setting librespot to show up as a phone to no avail. 
Once I've connected to the client once it also works flawlessly; I can change to listening on my phone, restart spt and my librespot client still shows up. The second I restart the librespot client however it won't show up by itself in spotify-tui.

**Comment by scouw** [comment]
Setting the `--username` and `--password` options for librespot fixed it for me. I'd assume doing the same thing for spotifyd would do it as well. As a nice side effect this also lets you connect to the device even when being connected to a VPN without letting local network stuff go through it.

I assume this is more an "issue" on spotify's end, especially considering the same thing also happens in other comparable programs such as spotify-qt.

**Comment by roberthilleck** [comment]
Since the last update it now works for me...
