### ISSUE TITLE
spt in gibberish words

### ISSUE THREAD

**Issue by azinsharaf** [Rigellute/spotify-tui#953]
Not sure what has changed in my settings but if I run `spt` in Windows Command Prompt it works but recently it stopped working on Git Bash for Windows (which used to work). It shows gibberish words. I deleted the config folder and set the new app/secret id but it didn't help. 

![image](https://user-images.githubusercontent.com/10101468/155567693-d4ad459b-0b80-4e53-8228-951177cbf873.png)

**Comment by fennewald** [comment]
Those are raw escape sequences. This is a bug within your terminal, or possibly with a misconfigured terminfo. Try opening spt in a different emulator.
