### ISSUE TITLE
Automaticy Fill In Redirect Code for New Users

### ISSUE THREAD

**Issue by ironhaven** [Rigellute/spotify-tui#96]
When you first open the program you need to authorize Spotify-tui in your webbrower and copy the redirect URL into the terminal. Because we already have a mock http server that sends a friendly html page it should be easy to retrieve the used callback URL.

Some cursory examination shows that the redirect and terminal input is handed in the rspotify crate.

## Steps

1. Parse http request header and return the URI in from redirect_uri.rs
2. Call the functions around [get_token](https://github.com/ramsayleung/rspotify/blob/6048e3deaa32d9c55e9e83f21592426ceffc7637/src/spotify/util.rs#L83)

**Comment by Rigellute** [comment]
Yes this could be nice improvement!

**Comment by jfaltis** [comment]
I am not that experienced with Rust but I will take a look at it.
