### ISSUE TITLE
[Feature Request] Interactive Interface with Mouse!

### ISSUE THREAD

**Issue by p0ryae** [Rigellute/spotify-tui#961]
It would be great if we could interact using the mouse and not the keyboard only.

Is that possible?

**Comment by Staninna** [comment]
This would be awesome not needed bet sick

**Comment by yadunandanbhat** [comment]
yes totally not needed, as this is just for terminal, adding interactive support would make it diverge from what it was

**Comment by p0ryae** [comment]
I don't see how? Lots of things like btop have interactive interface at least to a minor extent.

**Comment by aromeronavia** [comment]
Hard to think it can be implemented, rust-tui does not support that, and assume the effort to support that will be huge

**Comment by p0ryae** [comment]
Very well then. 
Closing this Feature Request.
