### ISSUE TITLE
Useless

### ISSUE THREAD

**Issue by yurikodesu** [Rigellute/spotify-tui#963]
May I know what is the use of this cli tool if I can't play tracks at all?
![image](https://user-images.githubusercontent.com/96462198/159626993-3d1cf34b-0005-461e-96e6-1ccd3522770a.png)

**Comment by evelez7** [comment]
It says there, as well as on the README: 

> This app uses the [Web API](https://developer.spotify.com/documentation/web-api/) from Spotify, which doesn't handle streaming itself. So you'll need either an official Spotify client open or a lighter weight alternative such as [spotifyd](https://github.com/Spotifyd/spotifyd).

It also says at the top of the README: 

> A Spotify client for the terminal written in Rust.

It needs to be connected to something that talks to the Spotify API to have any useful functionality.

**Comment by yurikodesu** [comment]
> It says there, as well as on the README:
> 
> > This app uses the [Web API](https://developer.spotify.com/documentation/web-api/) from Spotify, which doesn't handle streaming itself. So you'll need either an official Spotify client open or a lighter weight alternative such as [spotifyd](https://github.com/Spotifyd/spotifyd).
> 
> It also says at the top of the README:
> 
> > A Spotify client for the terminal written in Rust.
> 
> It needs to be connected to something that talks to the Spotify API to have any useful functionality.

I know that, is there a way to get this working without spotify premium?

**Comment by p0ryae** [comment]
> I know that, is there a way to get this working without spotify premium?

No 
![image](https://user-images.githubusercontent.com/59381835/159812455-a273cfc9-c7b3-48b6-bc2d-570dcc7475d4.png)

**Comment by yurikodesu** [comment]
> > I know that, is there a way to get this working without spotify premium?
> 
> No ![image](https://user-images.githubusercontent.com/59381835/159812455-a273cfc9-c7b3-48b6-bc2d-570dcc7475d4.png)

Why does this project exist then?

**Comment by p0ryae** [comment]
This project may seem useless to you but that's not the case for everyone.

Don't open issues to complain.

**Comment by yurikodesu** [comment]
> This project may seem useless to you but that's not the case for everyone.
> 
> Don't open issues to complain.

Ok
