### ISSUE TITLE
Error: API Response

### ISSUE THREAD

**Issue by Eccomi21** [Rigellute/spotify-tui#970]
I am using spotify-tui together with spotifyd.
However spotify tui doesn't recognize spotifyd as a playback device until i control my PC/spotifyd from my phone as example. it then throws the API response attached below (couldn't copy it out, i know screenshots aren't the way to go). sometimes i can simply quit out of the error and use spotify tui as intended, it works great, but right now i cant, it keeps reverting back to the error screen which makes using spotify tui impossible.
distro is Arch. if you need any more information i'd be happy to provide it.
![2022-04-13_15-39](https://user-images.githubusercontent.com/55301370/163193346-f37be118-d8e2-4e4f-aaaf-d232de781091.png)

**Comment by Mehmetali345Dev** [comment]
I'm also getting the same error. It started 5 days ago. It makes spotify-tui unusable. I'm using Fedora and I installed spotify-tui from copr repos.

**Comment by ashiq54689** [comment]
Same issue in macOS, I am using binary download v0.25.0 with Spotify Desktop. However, I have switched to v0.24.0, which is working fine.

**Comment by sewnie** [comment]
duplicate of https://github.com/Rigellute/spotify-tui/issues/960

but since nothing is being done we can only just wait.

**Comment by Eccomi21** [comment]
> duplicate of #960

Issue closed because of duplicate, refer to issue listed above
