### ISSUE TITLE
Change volume up keybinding

### ISSUE THREAD

**Issue by CharlesYiu** [Rigellute/spotify-tui#981]
I find that pressing shift+"=" ("+") is counter-intuitive and should be changed to just "=".

**Comment by DJTai** [comment]
@charlesyiu - that would only make sense for keyboards where the `=` and `+` share the same key, so while that's probably more common it's not always going to be the case.

**Comment by CharlesYiu** [comment]
Thanks for your reply, because I understand your reason behind the decision, I will dismiss and close this issue.
